### PR TITLE
refactor(tae): rename hidden column to phyAddr

### PR DESCRIPTION
**Pull request by aptend**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

this is a part work of #3415, making it easier to distinguish rowid column and hidden column from compute layer

**Special notes for your reviewer:**

The hidden column in tae has been renamed to PhyAddr, while GetHideKeys method remains untouched.
As nnsgmsone suggests, it is better to only retain TableDefs and discard other column-info-related methods.
Might that can be done in the future

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by aptend** [comment]
@Mergifyio refresh

**Comment by aptend** [comment]
@mergify requeue

**Comment by aptend** [comment]
@Mergifyio requeue

**Pull request merged**
