### PR TITLE
Fix the MergeGroup operator never sync the chunksize between groupby and aggresult.

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

https://github.com/matrixorigin/matrixone/issues/20766
https://github.com/matrixorigin/MO-Cloud/issues/4646

## What this PR does / why we need it:
1. MergeGroup算子没有同步group by列，和Agg Result的分块size，这会最终结果不符合要求。
2. 移除了MergeGroup算子直接拿走第一个Agg结果的优化，避免出现该Agg行数大于sync chunksize的情况。

### CODE REVIEW

**Review by aunjgr — APPROVED** [review]

**Comment by m-schen** [comment]
先加个标签

**Comment by m-schen** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/12369928166

跑个tpch 100g进行测试。

**Comment by m-schen** [comment]
daily环境好像网络有点问题，go mod vendor操作一直执行失败。

**Comment by aunjgr** [comment]
我本地测试已经通过

**Comment by m-schen** [comment]
daily:
https://github.com/matrixorigin/ci-test/actions/runs/12371025670

merge run:
https://github.com/matrixorigin/mo-auto-test/actions/runs/12371060379

都跑过的话，我会去除该标签。

**Comment by m-schen** [comment]
跑过了

**Pull request merged**
