### PR TITLE
fix an insert-select bug when query contains null values

### PR DESCRIPTION
**Pull request by m-schen**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

1.  fix bug that 'insert into t1 select varchar from t2' will cause panic.
2. constExpand function will expand the col part for scalar null but not only Nsp part now.

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
No test?

**Comment by m-schen** [comment]
> No test?

I will add ut for colexec2/insert.go later

**Comment by fengttt** [comment]
> > No test?
> 
> I will add ut for colexec2/insert.go later

later?   no …

**Comment by m-schen** [comment]
> > > No test?
> > 
> > 
> > I will add ut for colexec2/insert.go later
> 
> later? no …

yeah, I forgot this pr. And I add ut now. these pr fix a bug that may cause panic when

**Review by fengttt — APPROVED** [review]

**Pull request merged**
