### PR TITLE
Agg sum with decimal

### PR DESCRIPTION
**Pull request by qingxinhome**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4493

## What this PR does / why we need it:
Declaration of supplementary C function

### CODE REVIEW

**Review by nnsgmsone — APPROVED** [review]

**Comment by qingxinhome** [comment]
C function 'decimal64_ Vecsumtodecimal128' has only definitions but no declarations. This PR supplements the function declaration in mo.h

**Review by fengttt — COMMENTED** [review]
How is this possible?   You missed this one and build does not fail?

**Comment by qingxinhome** [comment]
> How is this possible? You missed this one and build does not fail?



> How is this possible? You missed this one and build does not fail?

Sorry, yes！I implemented the C function according to Mo Chen's requirements, and he called it！

**Review by fengttt — APPROVED** [review]

**Comment by qingxinhome** [comment]
> possible

Sorry, yes！I implemented the C function according to Mo Chen's requirements, and he called it！

**Comment by nnsgmsone** [comment]
> How is this possible? You missed this one and build does not fail?

Because there is no single test 。。。。 There is a single test this is exposed. Haha

**Pull request merged**
