### PR TITLE
Vectorize for  arm add

### PR DESCRIPTION
**Pull request by NTH19**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
For this kind of work, can you please add a BenchmarkXXX in a test?   We want to quantify the improvements.    Thank you.

**Comment by NTH19** [comment]
> 



> For this kind of work, can you please add a BenchmarkXXX in a test? We want to quantify the improvements. Thank you.

okay,I will add

**Comment by NTH19** [comment]
> For this kind of work, can you please add a BenchmarkXXX in a test? We want to quantify the improvements. Thank you.

Just add the func Benchmark?I am not familiar with go.And I think SVE may be faster.

**Comment by NTH19** [comment]
What is the error in Format Check Error?

**Comment by broccoliSpicy** [comment]
> What is the error in Format Check Error?

we apply format check on pull request now, run "make fmt" in the matrixone repo directory before pr would solve your problem

**Comment by yingfeng** [comment]
Fix the static check before it's merged

**Comment by yingfeng** [comment]
fmt check

**Comment by NTH19** [comment]
I don't know why mistake happens

**Comment by yingfeng** [comment]
> I don't know why the mistake happens

It doesn't matter

**Pull request merged**
