### PR TITLE
Debug 8741 luofei

### PR DESCRIPTION
**Pull request by triump2020**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

### CODE REVIEW

**Comment by triump2020** [comment]
@matrix-meow refresh

**Comment by triump2020** [comment]
@matrix-meow refresh

**Comment by triump2020** [comment]
@matrix-meow rerun all

**Comment by triump2020** [comment]
@matrix-meow rerun all

**Review by fengttt — COMMENTED** [review]
I think you are logging too much -- can we set it at debug level?

**Comment by m-schen** [comment]
I have fix the bug at pr #8915.
the debug pr can be closed.

**Pull request closed without merging**
