### PR TITLE
Delete TestIOSchedule1 case for ut

### PR DESCRIPTION
**Pull request by LeftHandCold**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [x] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
This case is no longer used, and there may be a timeout, so delete it.

### CODE REVIEW

**Review by fengttt — CHANGES_REQUESTED** [review]
Do you understand the problem?   Is it a really bad test, or, we are masking something?

**Comment by LeftHandCold** [comment]
> Do you understand the problem? Is it a really bad test, or, we are masking something?

This case will be used in the development phase. There may be a timeout when the container resources are few, so delete it or increase the timeout period.

**Comment by LeftHandCold** [comment]
> > Do you understand the problem? Is it a really bad test, or, we are masking something?
> 
> This case will be used in the development phase. There may be a timeout when the container resources are few, so delete it or increase the timeout period.

This case does not take into account the delay caused by the lack of various system resources.

**Review by fengttt — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Pull request merged**
