### PR TITLE
update GetColumnDataById

### PR DESCRIPTION
**Pull request by jiangxinmeng1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
1. fill deletes from delta
2. update GetVisibleRow

### CODE REVIEW

**Comment by jiangxinmeng1** [comment]
All failed jobs are rerun ----- @matrix-meow

**Comment by jiangxinmeng1** [comment]
> @matrix-meow rerun failed

**Comment by jiangxinmeng1** [comment]
`@matrix-meow rerun failed`

**Comment by jiangxinmeng1** [comment]
@matrix-meow rerun failed

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Pull request merged**
