### PR TITLE
HandleParseTimeMissingIssue

### PR DESCRIPTION
**Pull request by qingxinhome**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/matrixone/issues/19295

## What this PR does / why we need it:
1. Handle parse start time missing Issue
2. Update the default price of S resource CU

### CODE REVIEW

**Review by xzxiong — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by heni02 — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
how did you get all these magics and what is the process of changing them.    need a comment and a link to process.

**Comment by qingxinhome** [comment]
> how did you get all these magics and what is the process of changing them. need a comment and a link to process.

@fengttt  这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了

**Review by LiSong0214 — APPROVED** [review]

**Comment by fengttt** [comment]
> > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> 
> @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了

Are you serious?   For all those 123, 456, 789, and you guys had a meeting to decided 567 and 678 are really bad ...   Cannot believe this.

> > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> 
> @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了


> > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> 
> @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了



> > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> 
> @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了

**Comment by qingxinhome** [comment]
> > > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> > 
> > 
> > @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了
> 
> Are you serious? For all those 123, 456, 789, and you guys had a meeting to decided 567 and 678 are really bad ... Cannot believe this.
> 
> > > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> > 
> > 
> > @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了
> 
> > > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> > 
> > 
> > @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了
> 
> > > how did you get all these magics and what is the process of changing them. need a comment and a link to process.
> > 
> > 
> > @fengttt 这些magics修改产品同事李松 @LiSong0214 @xzxiong 开会对过了

OK，let me organize a meeting @fengttt

**Review by xzxiong — APPROVED** [review]

**Pull request closed without merging**
