### PR TITLE
optimize cn push model code. and turn on push model.

### PR DESCRIPTION
**Pull request by nnsgmsone**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [X] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
* parallel consumption logtail
* lazy process ckpt
* turn on push model.

### CODE REVIEW

**Comment by fengttt** [comment]
what is open push?

**Comment by m-schen** [comment]
> what is open push?

maybe he want to say he turn on the push model.

**Comment by nnsgmsone** [comment]
> what is open push?

The default is to run Push to get the logtail

**Comment by m-schen** [comment]
I will make a new pr today. the branch is failed too often.
I don't want to wast the server resource.

**Pull request closed without merging**
