### PR TITLE
add privilege switch

### PR DESCRIPTION
**Pull request by daviszhen**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

Add a switch to close the privilege check if needed.

### CODE REVIEW

**Review by iamlinjunhong — APPROVED** [review]

**Comment by daviszhen** [comment]
@mergifyio refresh

**Comment by daviszhen** [comment]
https://github.com/Mergifyio refresh

**Comment by daviszhen** [comment]
@aressu1985 found that sysbench test will lead to the hang.

**Comment by daviszhen** [comment]
i will re open the pr again.

**Pull request closed without merging**
