### PR TITLE
Solve AOE function panic

### PR DESCRIPTION
**Pull request by qingxinhome**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2863

**What this PR does / why we need it:**
Panics related to functions appear in AOE pipeline testing, which need to be solved uniformly. The functions involved include: power, lpad, round, rpad, unary_ minus

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by ouyuanning — APPROVED** [review]

**Review by yingfeng — CHANGES_REQUESTED** [review]
Fix errors in BVT Compare, which means newly introduced failure cases by this PR

typo: Slove => Solve

**Comment by qingxinhome** [comment]
> Fix errors in BVT Compare, which means newly introduced failure cases by this PR
> 
> typo: Slove => Solve

**Comment by qingxinhome** [comment]
> Fix errors in BVT Compare, which means newly introduced failure cases by this PR
> 
> typo: Slove => Solve

Sorry, I will correct the word errors, then download the BVT test document, confirm the problem and deal with it

**Comment by yingfeng** [comment]
no need to close, just add extra commits to fix the failed BVT compare, additionally, do not need to download bvt logs, the failed cases are directly shown in the CI console

**Comment by qingxinhome** [comment]
> no need to close, just add extra commits to fix the failed BVT compare, additionally, do not need to download bvt logs, the failed cases are directly shown in the CI console

OK，I see

**Pull request merged**
