### PR TITLE
refactor the function evaluate framework.

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6827 

## What this PR does / why we need it:

the old function evaluate framework requires developers allocate the use the memory carefully. it's too difficult and too hard to debug when bug occurs.

New framework can let developers needn't care about if the function parameter is scalar or not, and needn't care about how to allocate the memory for vector (for much built-in functions, developers has no need to know what is vector and how to use vector.).
it brings new way to implement a built-in function, we support GetValue and Append method to get value of function parameter and set value for function result even though it's Null.

and I rewrite the built-in function `CAST` and `rand()` as a demo at this pr.

### CODE REVIEW

**Comment by m-schen** [comment]
there is no need to review it now.

I will make a design doc to describe how to use the new framework tomorrow.

for BVT, I think it's a good update for expected results.

**Comment by m-schen** [comment]
the implement of rand is wrong. I will remove it soon.

**Comment by m-schen** [comment]
I will support a suitable test util for built-in-function-ut today.

**Comment by m-schen** [comment]
> I will support a suitable test util for built-in-function-ut today.

I'm sorry I can not finish it today.

**Comment by m-schen** [comment]
> > I will support a suitable test util for built-in-function-ut today.
> 
> I'm sorry I can not finish it today.

I have support the general test tools (file path is /testutil/util_function.go) for built-in function which was developed under the new framework. and I make a demo to test 'cast bool to varchar' (file path is cast2_test.go).

**Review by nnsgmsone — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Pull request merged**
