### PR TITLE
[MatrixCamp] Add Aggregate function bit_or

### PR DESCRIPTION
**Pull request by NTH19**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1994 

**What this PR does / why we need it:**

Add aggregate function bit_or

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by NTH19** [comment]
Performance Test:
 
 mysql> select avg(LO_SUPPKEY) from lineorder_flat;
+-----------------+
| avg(LO_SUPPKEY) |
+-----------------+
|        100.5914 |
+-----------------+
1 row in set (0.11 sec)

mysql> select sum(LO_SUPPKEY) from lineorder_flat;
+-----------------+
| sum(LO_SUPPKEY) |
+-----------------+
|       337987183 |
+-----------------+
1 row in set (0.04 sec)

mysql> select bit_or(LO_SUPPKEY) from lineorder_flat;
+--------------------+
| bit_or(LO_SUPPKEY) |
+--------------------+
|                255 |
+--------------------+
1 row in set (0.04 sec)

**Comment by domingozhang** [comment]
BVT passed

**Comment by NTH19** [comment]
> BVT passed

Is something else need to do?

**Comment by NTH19** [comment]
> BVT passed

Is there something else need to do?

**Comment by m-schen** [comment]
1. Unlike function Max, the Bit_or function should return a type of uint64 for all types of columns. I think you can just implement one ring structure, or you should return uint64 by every ring, but not uint8, uint16, uint32 and so on.
May be you can refer to the  implementation of 'bit_and'.

2. obey the Golang's code rule, '_' is not recommended in package name. You can change all names of the package and directory to be `bitor`.

3.there is a name error at test function for ring. 

4.other logic is good.

@NTH19

**Review by m-schen — APPROVED** [review]
1. Unlike function Max, the Bit_or function should return a type of uint64 for all types of columns. I think you can just implement one ring structure, or you should return uint64 by every ring, but not uint8, uint16, uint32 and so on.
May be you can refer to the  implementation of 'bit_and'.

2. obey the Golang's code rule, '_' is not recommended in package name. You can change all names of the package and directory to be `bitor`.

3.there is a name error at test function for ring. 

4.other logic is good.

@NTH19

**Review by m-schen — CHANGES_REQUESTED** [review]
1. Unlike function Max, the Bit_or function should return a type of uint64 for all types of columns. I think you can just implement one ring structure, or you should return uint64 by every ring, but not uint8, uint16, uint32 and so on.
May be you can refer to the  implementation of 'bit_and'.

2. obey the Golang's code rule, '_' is not recommended in package name. You can change all names of the package and directory to be `bitor`.

3.there is a name error at test function for ring. 

4.other logic is good.

@NTH19

**Comment by NTH19** [comment]
> 1. Unlike function Max, the Bit_or function should return a type of uint64 for all types of columns. I think you can just implement one ring structure, or you should return uint64 by every ring, but not uint8, uint16, uint32 and so on.
>    May be you can refer to the  implementation of 'bit_and'.
> 2. obey the Golang's code rule, '_' is not recommended in package name. You can change all names of the package and directory to be `bitor`.
> 
> 3.there is a name error at test function for ring.
> 
> 4.other logic is good.
> 
> @NTH19

Okay.I thought Uint64 just for float.Now I have changed all types to  uint64

**Review by m-schen — CHANGES_REQUESTED** [review]
I'm sorry I forgot that we should determine what type the aggregate function supports at last review.  I also forgot about this when I was making the tutorial. 
you can make a new Function in transformer.go like `NewBitAnd`.

And I think the file name`bitor.go` is good than `Uint64Ring.go` since we have only a ring for bit_or ? @NTH19

**Comment by NTH19** [comment]
> I'm sorry I forgot that we should determine what type the aggregate function supports at last review. I also forgot about this when I was making the tutorial. you can make a new Function in transformer.go like `NewBitAnd` or refer to my pull request #2162
> 
> And I think the file name`bitor.go` is good than `Uint64Ring.go` since we have only a ring for bit_or ? @NTH19

Okay,I have change the name and add NewBitOr @m-schen

**Review by m-schen — APPROVED** [review]
looks good to me. thanks for your contribution.

**Pull request merged**
