### PR TITLE
Year function implementation with lookup tables

### PR DESCRIPTION
**Pull request by broccoliSpicy**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Theoretically speaking, the original implementation of year function is already O(1)(four integer division operation dominates the computation time, about 200 clock cycles). 
using ssb lineorder.tbl(6million rows), Testing results shows that implement year function with lookup tables does not accelerate the execution at all.

### CODE REVIEW

**Comment by broccoliSpicy** [comment]
query: select year(d1) from ssb_t2;

**Comment by broccoliSpicy** [comment]
Empirical evidence does show that this year function is faster than the original one(by a factor of 2), request merge,

**Review by aunjgr — APPROVED** [review]

**Review by m-schen — COMMENTED** [review]
LGTM

**Comment by nnsgmsone** [comment]
lgtm

**Pull request merged**
