### PR TITLE
use spool to instead of batch.dup for the communication between pipelines.

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #17944 

## What this PR does / why we need it:
1. 实现了一个支持send, get, close方法的简单spool给pipeline使用。
2. pipeline之间的通信由dup后直接传递修改为copy到spool中，然后发送signal.
3. 移除旧的merge receivers等代码。
4. pipeline通信的内存修改为统一由发送端释放。
5. 新增了recursiveCTE等tag。
6. 移除了一些cte的冗余代码。

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Implemented a new `PipelineSignal` and `PipelineSignalReceiver` for efficient pipeline communication.
- Introduced `pipelineSpool` for managing batch sending and synchronization.
- Refactored send functions to use `PipelineSignal`, simplifying batch handling.
- Removed `ReceiverOperator` and related methods, simplifying receiver logic.
- Enhanced remote run client and connector logic for better performance.
- Updated various components to integrate with the new pipeline signal mechanism.
- Added utility functions for vector data management.
- Improved error handling and recursive batch logic in merge operations.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>process_spoolr.go</strong><dd><code>Implement pipeline signal and receiver for communication</code>&nbsp; </dd></summary>
<hr>

pkg/vm/process/process_spoolr.go

<li>Implemented a new <code>PipelineSignal</code> and <code>PipelineSignalReceiver</code> for <br>pipeline communication.<br> <li> Added methods for managing pipeline signals and actions.<br> <li> Introduced a mechanism to handle pipeline signals efficiently.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-0716d905d11f19e3a46dbc975418aa00b60e9387f0bc7d11f35b5b21104abe38">+380/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>copy.go</strong><dd><code>Introduce cachedBatch for batch caching and copying</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/container/pSpool/copy.go

<li>Added <code>cachedBatch</code> struct for batch caching.<br> <li> Implemented methods for caching and copying batches.<br> <li> Introduced batch management and memory optimization techniques.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-ea64d2c2139dbfc7bb8d875b0ec271a49de6ff8a1e69d0d379f8c2627d34be16">+280/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>compile.go</strong><dd><code>Update pipeline communication to use new signal mechanism</code></dd></summary>
<hr>

pkg/sql/compile/compile.go

<li>Replaced <code>Ch</code> with <code>Ch2</code> for pipeline signal communication.<br> <li> Removed redundant context handling in <code>WaitRegister</code>.<br> <li> Updated pipeline communication logic.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-1f95b23a5c61734c0686b47c14583f114fe66c015310f43992c517fa62c76f3d">+13/-29</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sendfunc.go</strong><dd><code>Refactor send functions to use PipelineSignal</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/dispatch/sendfunc.go

<li>Refactored send functions to use <code>PipelineSignal</code>.<br> <li> Simplified logic for sending batches to local and remote receivers.<br> <li> Removed redundant code for batch duplication.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-6bbcbe692f0f11ca8a189d32e18e4334f74c139121bebb9d2cad719dea586d54">+49/-111</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sender.go</strong><dd><code>Implement pipelineSpool for batch management and sending</code>&nbsp; </dd></summary>
<hr>

pkg/container/pSpool/sender.go

<li>Implemented <code>pipelineSpool</code> for managing batch sending.<br> <li> Added methods for sending batches to all or specific receivers.<br> <li> Introduced synchronization mechanisms for batch management.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-6b8dd5ebdd90f0a96fa426bb2f3ab6be0d40a36de6a9bbb30c85abd3ea8d63e3">+143/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>receiver_operator.go</strong><dd><code>Remove ReceiverOperator and simplify receiver logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/receiver_operator.go

<li>Removed <code>ReceiverOperator</code> and related methods.<br> <li> Simplified receiver logic using new pipeline signal mechanism.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-603dbffae9276e0a3e1d422a7c4489596d62e6db42d245c218eb6012aca798f6">+3/-189</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>dispatch.go</strong><dd><code>Update dispatch logic to integrate with pipelineSpool</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/dispatch/dispatch.go

<li>Updated dispatch logic to use <code>pipelineSpool</code>.<br> <li> Simplified batch handling and error management.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-dad5b5bad674d30aeeeb8ea79ea4b646eab52bd32abbb281022ca7047d67e1c6">+16/-59</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>remoterunClient.go</strong><dd><code>Enhance remote run client for connector optimization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/compile/remoterunClient.go

<li>Enhanced remote run client to handle connector optimization.<br> <li> Improved data receiving and forwarding logic.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-e027434536257765c13ae824cfa8138e56c758db4365d2706ae5889ed1db14e2">+50/-38</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>connector.go</strong><dd><code>Integrate pipelineSpool with connector logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/connector/connector.go

<li>Integrated <code>pipelineSpool</code> with connector logic.<br> <li> Improved batch sending and signal handling.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-1dcfbf5a976a22b5e5c5e654d59f562490e231008ff98cfdcc4606daa894f29b">+14/-31</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>merge.go</strong><dd><code>Update merge logic to use PipelineSignalReceiver</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/merge/merge.go

<li>Updated merge logic to use <code>PipelineSignalReceiver</code>.<br> <li> Simplified batch processing and error handling.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-91df55e29b79c5ebcbe86d75c14b8dd560c9944bbe4d5ef9c990d0e5fdd1fa46">+9/-30</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>mergecte.go</strong><dd><code>Add error handling and improve recursive batch logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/mergecte/mergecte.go

<li>Added error handling for vector operations.<br> <li> Improved recursive batch creation logic.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-57645058bac862fe1f3e8724091ae3fcded268d0c9616c298ae4fb5665e9b4c0">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>scope.go</strong><dd><code>Update scope cleanup and notification logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/compile/scope.go

<li>Updated scope cleanup to use <code>CleanRootOperator</code>.<br> <li> Simplified notify message sending logic.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-1a84d311b058e390f8c70e84f5e0c59dbd42736a85d022e2a283d926d43f5bd6">+7/-24</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pSpoolTools.go</strong><dd><code>Add utility functions for vector data management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/container/vector/pSpoolTools.go

<li>Added utility functions for vector data management.<br> <li> Introduced methods for setting and clearing vector data and area.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-1a708278b84207f3e90fb716cc25a4af02fbb3156100a9614c6550efaceb7cfa">+40/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>join.go</strong><dd><code>Update bitmap receiving logic and remove process init</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/rightsemi/join.go

<li>Updated bitmap receiving logic to use context.<br> <li> Removed initialization of process in container.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-18752303c0e5060a73d6e79f699dfe05b20f3f76584d2edc0122dac030f3a20f">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>join.go</strong><dd><code>Update bitmap receiving logic and remove process init</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/rightanti/join.go

<li>Updated bitmap receiving logic to use context.<br> <li> Removed initialization of process in container.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-51a110fbc63ab6f176ddf4b6e7fb0f28747b400fc627fa0a37410f2e034924db">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Additional files (token-limit)</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>plan.pb.go</strong><dd><code>...</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/pb/plan/plan.pb.go

...

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-33f2cd3e1c50f35dec893cbff56b5ff6cd269b0b239e51463d4c93f7afdab924">+437/-393</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pipeline.pb.go</strong><dd><code>...</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/pb/pipeline/pipeline.pb.go

...

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18709/files#diff-966f3a64eaa6e8c3a8815332fec622b1e79c9d999ed32198a74e0038c17a25ec">+371/-329</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by m-schen** [comment]
先打个not-merge标签跑一些测试，后续我会自己去掉。

**Review by badboynt1 — APPROVED** [review]

**Review by reusee — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Comment by m-schen** [comment]
再做一点简单的测试工作再去掉tag.

**Comment by m-schen** [comment]
先做个关于copy的优化。避免常量被展开。

**Comment by m-schen** [comment]
先合并吧 有需要优化的地方后面再加

**Comment by m-schen** [comment]
下午会再跑一次tpch100g tpcc10仓 和benchmark

**Comment by m-schen** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/10828252577

新起了一个测试去检查tpch100g, sysbench10w, tpcc10-10, tpcc10-100的性能。如果和main差不多的话，我将去掉标签。

commit id:  1a8c54eae0c9709503ad77a04e669788721eaf77

**Comment by m-schen** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/10846798688

修改了部分逻辑，再跑一次看看。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/10850050011

**Comment by m-schen** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/10860203559

tpcc等性能已恢复，去除not-merge标签。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/10860203559

tpcc等性能已恢复，去除not-merge标签。

**Review by ouyuanning — APPROVED** [review]

**Pull request merged**
