### PR TITLE
Fix bug: NewConstNull don't set vector.data.

### PR DESCRIPTION
**Pull request by ouyuanning**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5772 

## What this PR does / why we need it:
this pr will fixed:
1、old logical will only set vector.Col when get NewConstNull(xx)， that will panic in disttae.

and this pr will not fixed:
1、constantFold have no mpool.  that will be changed in future
2、I really think about that.  T_any is any type we don't known sometime.   that will be not null.   we can add T_null type for null.

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
Wait -- why do you need mpool for null?   const null will never have data, and or area, so why is that useful?

**Comment by ouyuanning** [comment]
> Wait -- why do you need mpool for null? const null will never have data, and or area, so why is that useful?

yes.  null constant will not have data.  but sometime we use default value like null.
like:  table t1(a int, b int)
insert into t1 (a) select 1.     => here, MO use NewConstNull create column b's default value.   when disttae's table write this vector. that'll make panic.

**Comment by ouyuanning** [comment]
and now logical like that:
when that's a null,   we get Col's with their default value.  but have no data.   that's weird too.
maybe we will get a really null value.  and get a really any value.

**Comment by nnsgmsone** [comment]
I want all vectors to be built with vector.New and then vec.Append. As for the null thing, I think we can wait until all vectors are built using methods like Append and then add their special handling.

**Comment by ouyuanning** [comment]
ok， i will fixed #5772 from another way

**Pull request closed without merging**
