### PR TITLE
add some system variable and enable where

### PR DESCRIPTION
**Pull request by iamlinjunhong**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4937 

## What this PR does / why we need it:

### CODE REVIEW

**Review by daviszhen — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
This is fine.   However did you thought of the following strategy,

create a table function that returns all varialbles.    
show translated into a select.
where is free.
you can even group by, join, etc.

**Comment by iamlinjunhong** [comment]
> This is fine. However did you thought of the following strategy,
> 
> create a table function that returns all varialbles. show translated into a select. where is free. you can even group by, join, etc.

I'm not sure whether this method is implemented by creating a temporary table, inserting all variables into it, and finally selecting

**Comment by iamlinjunhong** [comment]
Secondly, each variable has its own type. If you convert variables to the same type and then place them in the same column for selection, the priority of type conversion is not easy to adjust under the current framework, such as show variables where value=0; The value of some variables is of varchar type, and its value cannot be converted to int64. At this time, an error will be reported and an interrupt will occur, resulting in no query of the variables that meet the conditions.

**Comment by iamlinjunhong** [comment]
Thanks for your explanation. I understand your method. At present, MySQL's show stmt only needs to support simple where. If you need to extend it later, I will try to use your method

**Pull request merged**
