### PR TITLE
memorycache: evict before allocate

### PR DESCRIPTION
**Pull request by reusee**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #17214 

## What this PR does / why we need it:
evict before allocating to avoid over-allocate too much

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
It is ok -- but I am not convinced this fix the root cause. 

The fix should be there should be an IO queue.   There may at most a fixed number of outstanding I/Os, more than that, should be queued.    This fix, won't help with explosion from io/compression buffers.

**Comment by reusee** [comment]
> It is ok -- but I am not convinced this fix the root cause.
> 
> The fix should be there should be an IO queue. There may at most a fixed number of outstanding I/Os, more than that, should be queued. This fix, won't help with explosion from io/compression buffers.

too many I/O is a bug that the TAE team will fix. Queuing I/O will cover that kinds of bugs, making them harder to expose.

Objects have different sizes so a fixed-size queue may cause suboptimal I/O performance.

**Comment by reusee** [comment]
> It is ok -- but I am not convinced this fix the root cause.
> 
> The fix should be there should be an IO queue. There may at most a fixed number of outstanding I/Os, more than that, should be queued. This fix, won't help with explosion from io/compression buffers.

We can make the IOAllocator a SizeBoundedAllocator and delay allocations if it reaches the bound.

**Comment by fengttt** [comment]
> > It is ok -- but I am not convinced this fix the root cause.
> > The fix should be there should be an IO queue. There may at most a fixed number of outstanding I/Os, more than that, should be queued. This fix, won't help with explosion from io/compression buffers.
> 
> too many I/O is a bug that the TAE team will fix. Queuing I/O will cover that kinds of bugs, making them harder to expose.
> 
> Objects have different sizes so a fixed-size queue may cause suboptimal I/O performance.

Queuing is a basic requirement for robustness of the system.  It does not cover anything.   Whatever should be exposed, should be exposed by metrics.

**Review by fengttt — APPROVED** [review]

**Pull request merged**
