### PR TITLE
refactor: use pkg/catalog in other packages

### PR DESCRIPTION
**Pull request by aptend**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #5247

## What this PR does / why we need it:

maintain only one catalog definition

- move column name constants from tae/catalog to pkg/catalog
- packages (except tae) will import pkg/catalog to get catalog-related constants
- modification on some ut

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
What is changed exactly?    Can you put in more details in commit message?

**Review by fengttt — COMMENTED** [review]
Please Ping Mo Chen.    I hope he knows what you are doing already ...

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Review by reusee — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Comment by aptend** [comment]
> What is changed exactly? Can you put in more details in commit message?

commit message is updated:
> - move column name constants from tae/catalog to pkg/catalog
> - packages (except tae) will import pkg/catalog to get catalog-related constants
> - modification on some ut

**Review by fengttt — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Comment by aptend** [comment]
@matrix-meow rerun failed

**Pull request merged**
