### PR TITLE
fileservice: write to disk cache in S3FS.Write and Read

### PR DESCRIPTION
**Pull request by reusee**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11569 

## What this PR does / why we need it:
fileservice: add FileCache

fileservice: rename DiskCache.entryDataFilePath to pathForIOEntry

fileservice: sketch FileCache impl for DiskCache

fileservice: remove S3FS.writeDiskCacheOnWrite

fileservice: add DiskCache.writeFile

fileservice: remove FileCache.GetFile; try get full file in DiskCache.Read

fileservice: add DiskCache.SetFile tests

fileservice: write to disk file cache in S3FS.write

### CODE REVIEW

**Review by nnsgmsone — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
This change seems to be different from the issue mentioned in pr message.

**Comment by reusee** [comment]
> This change seems to be different from the issue mentioned in pr message.

The issue number is correct.

**Review by fengttt — COMMENTED** [review]
We replace all S3 cache to whole file?     Don't we want some kind of config?   What about AP cache, we said later it may need to cache all blocks of one column.    What about metadata/zonemap, are they in a totally different cache system and not use disk cache at all?

I cannot tell from this change and not sure what we do.

**Comment by reusee** [comment]
> We replace all S3 cache to whole file? Don't we want some kind of config? What about AP cache, we said later it may need to cache all blocks of one column. What about metadata/zonemap, are they in a totally different cache system and not use disk cache at all?
> 
> I cannot tell from this change and not sure what we do.

The file service doesn't know about AP, blocks/column/zonemap. They're handled at the call site.
This change adds file/object cache to the disk cache, not replacing existed IOEntry caches.

**Pull request merged**
