### PR TITLE
fix build show columns

### PR DESCRIPTION
**Pull request by YANGGMM**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #13845 

## What this PR does / why we need it:
fix build show columns

### CODE REVIEW

**Comment by matrix-meow** [comment]
@YANGGMM Thanks for your contributions!

Review:

Title: fix build show columns

Body: This pull request fixes an issue (#13845) related to building show columns.

Changes:
1. In `buildShowColumns` function in `build_show.go` file, a map `uniqueColName` is introduced to keep track of unique column names. The loop that iterates over `tableDef.Indexes` is modified to check if the column name already exists in the `uniqueColName` map before adding it to the `keyStr`. This ensures that duplicate column names are not added to the `keyStr`.

2. In `mysql_ddl_2.result` file, a new test case is added to create a table `table_basic_for_alter_100m` with various column types and keys. The `desc` command is used to display the table structure.

3. In `mysql_ddl_2.sql` file, the same test case as in `mysql_ddl_2.result` is added to create the `table_basic_for_alter_100m` table and display its structure using the `desc` command.

Overall, the changes in this pull request seem to address the issue and add a new test case. However, there are a few suggestions for improvement:

1. In the `buildShowColumns` function, instead of using a map `uniqueColName` to check for duplicate column names, it would be more efficient to use a set data structure. This would eliminate the need for the `continue` statement inside the loop and improve the performance of the code.

2. In the new test case added, it would be helpful to include some comments explaining the purpose of the test case and the expected output. This would make it easier for future developers to understand the intention of the test case.

3. It would be good to add some additional test cases to cover different scenarios, such as tables with no indexes or tables with multiple unique indexes.

4. It is recommended to follow a consistent coding style throughout the codebase. In this pull request, there are some inconsistencies in indentation and spacing. It would be good to fix these inconsistencies to maintain a clean and readable codebase.

5. It is important to ensure that the changes made in this pull request do not introduce any security vulnerabilities. It would be helpful to conduct a security review of the code changes to identify and address any potential security issues.

Overall, the changes in this pull request are satisfactory, but there is room for improvement in terms of code efficiency, test coverage, and code style.

**Review by ouyuanning — APPROVED** [review]

**Review by heni02 — APPROVED** [review]

**Comment by YANGGMM** [comment]
@mergify refresh

**Review by aunjgr — APPROVED** [review]

**Comment by YANGGMM** [comment]
@mergify refresh

**Comment by YANGGMM** [comment]
@mergify refresh

**Pull request merged**
