### PR TITLE
explain marshal support table function

### PR DESCRIPTION
**Pull request by qingxinhome**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9558

## What this PR does / why we need it:
1. explain execute plan support table function
2. Serialized execution plan, supporting table function nodes

### CODE REVIEW

**Review by ouyuanning — APPROVED** [review]

**Comment by qingxinhome** [comment]
The issue has been resolved and submitted to PR, please follow @xzxiong

**Comment by qingxinhome** [comment]
@mergify refresh

**Review by aunjgr — APPROVED** [review]

**Review by xzxiong — APPROVED** [review]
Well done

**Comment by qingxinhome** [comment]
@mergify refresh

**Pull request merged**
