### PR TITLE
malloc: enable metrics defaultly

### PR DESCRIPTION
**Pull request by reusee**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16057 

## What this PR does / why we need it:
always enable malloc metrics

___

### **PR Type**
Enhancement

___

### **Description**
- Renamed `EnableMetrics` to `DontUse_EnableMetrics` for config file compatibility and added a new `DisableMetrics` field to control metrics exposure.
- Updated logic to enable metrics by default unless `DisableMetrics` is set.
- Changed log level from `Info` to `Debug` for malloc stats.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>config.go</strong><dd><code>Add `DisableMetrics` field and rename `EnableMetrics`</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/common/malloc/config.go

<li>Renamed <code>EnableMetrics</code> to <code>DontUse_EnableMetrics</code> for config file <br>compatibility.<br> <li> Added <code>DisableMetrics</code> field to control metrics exposure.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16612/files#diff-027c638b29ffcd6238052355868e13dcfc3bc8eb6d082b9b64e167f656146ac4">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>default.go</strong><dd><code>Enable metrics by default unless `DisableMetrics` is set</code>&nbsp; </dd></summary>
<hr>
      
pkg/common/malloc/default.go

<li>Replaced checks for <code>EnableMetrics</code> with <code>DisableMetrics</code>.<br> <li> Metrics are now enabled by default unless <code>DisableMetrics</code> is set.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16612/files#diff-110177878567ae1db46fdf591a13b48924175e186c7ec2057cf2c8cd7b2fe60e">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>metrics_allocator.go</strong><dd><code>Change malloc stats log level to Debug</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/common/malloc/metrics_allocator.go

- Changed log level from `Info` to `Debug` for malloc stats.

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16612/files#diff-b17f9a80586b482474191c433159b845cf88a8a53e2ad039ffa605523b23c97f">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by fengttt — CHANGES_REQUESTED** [review]
What is the performance impact of this flag?

**Review by fengttt — CHANGES_REQUESTED** [review]
This is a VERY strange way of change a config default.    The config default cannot be YES for enableMetrics?   You have to change enableMetrics to disableMetrics?   Looks like the config code is broken.

**Comment by reusee** [comment]
> This is a VERY strange way of change a config default. The config default cannot be YES for enableMetrics? You have to change enableMetrics to disableMetrics? Looks like the config code is broken.

我想只保留 disable，但不想破坏已有的配置文件

**Comment by reusee** [comment]
性能影响较大，默认不开启吧

**Pull request closed without merging**
