### PR TITLE
fix data race in newReader

### PR DESCRIPTION
**Pull request by ouyuanning**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6335

## What this PR does / why we need it:
fix data race in newReader.

### CODE REVIEW

**Review by aptend — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
I browsed the code, seems the reason is the code will modify the deletes during merge read, is this correct?   I think this API is broken, reader should not mutate block meta.

What is the cost of this copy?

**Review by nnsgmsone — CHANGES_REQUESTED** [review]
Please wait until I find the exact reason before merging this pr

**Comment by nnsgmsone** [comment]
> I browsed the code, seems the reason is the code will modify the deletes during merge read, is this correct? I think this API is broken, reader should not mutate block meta.
> 
> What is the cost of this copy?

I just wonder where there is competition causing this, my understanding is that the blocks here are exclusive and should not have this problem. I think the cause must be found and then modified.

**Comment by fengttt** [comment]
> > I browsed the code, seems the reason is the code will modify the deletes during merge read, is this correct? I think this API is broken, reader should not mutate block meta.
> > What is the cost of this copy?
> 
> I just wonder where there is competition causing this, my understanding is that the blocks here are exclusive and should not have this problem. I think the cause must be found and then modified.

disttae/reader.go,  blockMergerReader Read, line 154.
```
		if len(r.blks[0].deletes) > 0 && i == r.blks[0].deletes[0] {
			r.blks[0].deletes = r.blks[0].deletes[1:]
			continue
		}
```

**Review by nnsgmsone — APPROVED** [review]

**Comment by fengttt** [comment]
> disttae/reader.go, blockMergerReader Read, line 154.

https://github.com/matrixorigin/matrixone/issues/6469

Tracking new task here.

**Pull request merged**
