### PR TITLE
set sum in zonemap when flush to disk

### PR DESCRIPTION
**Pull request by w-zr**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10856

## What this PR does / why we need it:
Set sum in zonemap when batch is flushing in to disk.

### CODE REVIEW

**Review by aunjgr — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
Add test.    Esp, check result using metadata scan.

**Comment by w-zr** [comment]
> Add test. Esp, check result using metadata scan.

The Min, Max and Sum field in zonemap cannot be printed in a readable format.
I do not know how to write bvt tests.

**Review by LeftHandCold — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
Please add a few test cases of different data types, int, float, decimal.

thank you

**Comment by w-zr** [comment]
> Please add a few test cases of different data types, int, float, decimal.
> 
> thank you

more tests added.

**Review by fengttt — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Pull request merged**
