### PR TITLE
parsers: add syntax values statement

### PR DESCRIPTION
**Pull request by e1ijah1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5183

## What this PR does / why we need it:

add syntax values statement

### CODE REVIEW

**Comment by iamlinjunhong** [comment]
Add some bvt cases, thanks.

**Review by fengttt — COMMENTED** [review]
Changes like this must have a bvt test.

**Comment by e1ijah1** [comment]
> Add some bvt cases, thanks.

Added bvt test case, PTAL.

**Review by iamlinjunhong — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Comment by guguducken** [comment]
@matrix-meow rerun failed

**Review by daviszhen — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Pull request merged**
