### PR TITLE
First proposal of cn cache: catalog cache

### PR DESCRIPTION
**Pull request by nnsgmsone**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [X] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6825 

## What this PR does / why we need it:

### CODE REVIEW

**Comment by nnsgmsone** [comment]
The original btree is currently used as the data structure for kv, and can be replaced more naturally if a better option is available. Then this proposal assumes that the catalog can all be put down in memory.

**Review by ouyuanning — APPROVED** [review]

**Comment by nnsgmsone** [comment]
The core purpose of the catalog cache is to convert all operations of the catlog into a memory kv lookup(without decode). (The main note is that queries like select * from mo_columns do not go catalog cache, the only purpose of this cache is to speed up the construction of plan)

**Review by reusee — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
This is OK, but how do you plan to use it?  During optimization?   Execution?

**Comment by nnsgmsone** [comment]
> This is OK, but how do you plan to use it? During optimization? Execution?
> 
> And how do you do invalidation? On DDL?

during buid plan.

**Comment by nnsgmsone** [comment]
> This is OK, but how do you plan to use it? During optimization? Execution?
> 
> And how do you do invalidation? On DDL?

I do invalidation by logtail.

**Comment by nnsgmsone** [comment]
all cache writes are log based

**Pull request merged**
