### PR TITLE
do not send sys tables logtail when launching

### PR DESCRIPTION
**Pull request by aptend**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5799

## What this PR does / why we need it:

### CODE REVIEW

**Comment by XuPeng-SH** [comment]
The related unit test need to be changed

**Review by XuPeng-SH — CHANGES_REQUESTED** [review]
The related unit test needs to be changed

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Review by fengttt — COMMENTED** [review]
I don't understand -- now, isn't that DN starts sending when CN polls?

**Comment by XuPeng-SH** [comment]
> I don't understand -- now, isn't that DN starts sending when CN polls?
I thought so, but CN didn't need it now. So we excludes these sys tables from logtail.

**Pull request merged**
