### PR TITLE
add metric sql_transaction_errors, sql_transaction_total

### PR DESCRIPTION
**Pull request by xzxiong**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5658

### 2. metirc sql_transaction_errors collection logic:
- column `type` 
means which type transaction error it is.
there will be 6 valid value in column `type` for `sql_transaction_errors` metric

| # | type |  means |
| -- | -- | -- |
| 1 | begin | exec cmd `begin` failed |
| 2 | commit | exec cmd `commit` failed |
| 3 | rollback | exec cmd `rollback` failed |
| 4| auto_commit | in autocommit txn, commit failed |
| 5| auto_rollback | in autocommit txn, rollback failed |
| 6| other | number of txn rollback executions, including autocommit=1 or 0 txn. |

> PS: `other`中可能包含对 `begin; rollback;`执行了回滚的空事务；包括链接断开导致回滚的事务；

- how to calculate txn error cnt ?
val = sum of (type begin, type commit, type auto_commit, type other)

- example

```
mysql> select * from system_metrics.sql_transaction_errors ; select * from system_metrics.sql_statement_errors ;
+----------------------------+-------+--------------------------------------+------+---------+-------+
| collecttime                | value | node                                 | role | account | type  |
+----------------------------+-------+--------------------------------------+------+---------+-------+
| 2022-10-16 01:15:59.243863 |     0 | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | LOG  | sys     | other |
| 2022-10-16 01:16:14.244053 |     0 | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | LOG  | sys     | other |
| 2022-10-16 01:16:29.247705 |     1 | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | LOG  | sys     | other |
| 2022-10-16 01:16:44.246648 |     1 | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | LOG  | sys     | other |
...
```

### 3. add metric sql_transaction_total
含义：事务结束个数

统计方法：通过统计执行commit、rollback、auto commit、auto rollback的执行次数。其中包括了在执行 `Begin`语句时，未结束的事务自动触发的`commit` 操作.

-  example
```
mysql> select * from system_metrics.sql_transaction_total;
+----------------------------+-------+--------------------------------------+------+---------+
| collecttime                | value | node                                 | role | account |
+----------------------------+-------+--------------------------------------+------+---------+
| 2022-10-16 12:24:25.317899 |     0 | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | LOG  | sys     |
| 2022-10-16 12:24:40.313935 |    57 | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | LOG  | sys     |
...
```

### CODE REVIEW

**Comment by sukki37** [comment]
sql_transaction_total is required as well.

**Comment by xzxiong** [comment]
> sql_transaction_total is required as well.

Consider it done.

**Review by daviszhen — APPROVED** [review]

**Comment by xzxiong** [comment]
> sql_transaction_total is required as well.

done. please review.

**Comment by fengttt** [comment]
@mergifyio refresh

**Review by aptend — APPROVED** [review]

**Pull request merged**
