### PR TITLE
Metadata related optimization

### PR DESCRIPTION
**Pull request by cnutshell**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #8016 #8865

## What this PR does / why we need it:
Refactor metadata related code in order to optimize AP load.

### CODE REVIEW

**Review by LeftHandCold — APPROVED** [review]

**Review by badboynt1 — APPROVED** [review]

**Comment by cnutshell** [comment]
WeChatWorkScreenshot_00e32852-280d-46e1-a87f-69cdc0c0b7eb

Time cost for explain q1 has reduce from 12.98s to 0.23s.

**Review by ouyuanning — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]

**Comment by aunjgr** [comment]
@mergify queue

**Comment by cnutshell** [comment]
@mergify queue

**Comment by cnutshell** [comment]
@mergeify refresh

**Comment by cnutshell** [comment]
@mergify refresh

**Comment by cnutshell** [comment]
@mergify queue

**Comment by cnutshell** [comment]
@mergify refresh

**Comment by cnutshell** [comment]
@mergify refresh

**Comment by cnutshell** [comment]
@mergify requeue

**Comment by cnutshell** [comment]
@mergify refresh

**Comment by cnutshell** [comment]
@mergify requeue

**Pull request merged**
