### PR TITLE
Fix 3320: result error in subquery

### PR DESCRIPTION
**Pull request by ouyuanning**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3320 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

1、some sql statement's expect result or issue number had changed.
details in comment, see: https://github.com/matrixorigin/matrixone/issues/3320

2、thanks @aunjgr @nnsgmsone 

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by yingfeng — APPROVED** [review]

**Review by sukki37 — CHANGES_REQUESTED** [review]
https://github.com/ouyuanning/matrixone/blob/b9ed3bb3dc2b169f0b410ed8f3bfaf7e51c1f385/test/cases/subquery/subquery-with-in.sql#L642

please remove all `bvt:issue#3320` tags.

**Comment by ouyuanning** [comment]
> https://github.com/ouyuanning/matrixone/blob/b9ed3bb3dc2b169f0b410ed8f3bfaf7e51c1f385/test/cases/subquery/subquery-with-in.sql#L642
> 
> please remove all `bvt:issue#3320` tags.

thanks.   my mistake.

**Comment by ouyuanning** [comment]
> https://github.com/ouyuanning/matrixone/blob/b9ed3bb3dc2b169f0b410ed8f3bfaf7e51c1f385/test/cases/subquery/subquery-with-in.sql#L642
> 
> please remove all `bvt:issue#3320` tags.

it's a complicated case。  I  need some time to check and fix

**Comment by sukki37** [comment]
> > https://github.com/ouyuanning/matrixone/blob/b9ed3bb3dc2b169f0b410ed8f3bfaf7e51c1f385/test/cases/subquery/subquery-with-in.sql#L642
> > please remove all `bvt:issue#3320` tags.
> 
> it's a complicated case。 I need some time to check and fix

I've checked #3556 and #3570, and both of them are not linked with `bvt` tag and `0.5.0` milestone, you should add ·
`bvt` tag and choose a milestone(default is 0.5.0 if you think it cannot be solved in the 0.5.0 release, please ask Dr. Tian/Yingfeng/JinHai and the product team for permission first).

**Pull request merged**
