### PR TITLE
add cfg to set max prepare stmt count

### PR DESCRIPTION
**Pull request by ouyuanning**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/MO-Cloud/issues/960

## What this PR does / why we need it:
1、add cfg to set max prepare stmt count

2、base CN.Txn.Mode to set the default value of CN.txn.isolation 
         set SI when mode is optimistic,  set  RC when mode is pessimistic

### CODE REVIEW

**Review by daviszhen — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
can you please update the other config params, like we discussed.

1. make the default isolation level auto, 
2. make the default dup check as auto,

if isolation level == auto:
    if optmistic set isolation level to SI
    if pessimistic set to RC

if dup check is auto:
   if optimistic set dup check to dn full
   if pessimistic set dup check to dn incr

Basically, only set optimisitic or pessimistic, everything else automagically have a good value.   Can still override.

**Comment by ouyuanning** [comment]
> can you please update the other config params, like we discussed.
> 
> 1. make the default isolation level auto,
> 2. make the default dup check as auto,
> 
> if isolation level == auto: if optmistic set isolation level to SI if pessimistic set to RC
> 
> if dup check is auto: if optimistic set dup check to dn full if pessimistic set dup check to dn incr
> 
> Basically, only set optimisitic or pessimistic, everything else automagically have a good value. Can still override.

ok.  I will confirm with @domingozhang then change that.

**Comment by domingozhang** [comment]
this is fine to me

**Review by reusee — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Review by reusee — APPROVED** [review]

**Comment by ouyuanning** [comment]
if dup check is auto:
if optimistic set dup check to dn full
if pessimistic set dup check to dn incr

这个部分暂未实现，等另外提PR处理。

**Review by fengttt — APPROVED** [review]

**Pull request merged**
