### PR TITLE
[MatrixCamp] Add built-in function startswith

### PR DESCRIPTION
**Pull request by whileskies**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2117

**What this PR does / why we need it:**

Add built-in function startsWith

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by domingozhang** [comment]
bvt passed

**Review by broccoliSpicy — APPROVED** [review]
this is excellent,
perhaps add some type casting rule may simplify your function implementation, the builtin power function may offer some examples, but I think your approach is also cool

**Comment by broccoliSpicy** [comment]
the ends with pr have this neat approach to handle the redundant part, could you like to check it out.

**Comment by whileskies** [comment]
Ok, I'm done.
And current implementation doesn't work well if the parameter is NULL constant, but the current parser does not support the NULL constant, do I need to consider?

**Comment by broccoliSpicy** [comment]
I think this is cool, support null in parser may not be a trivial task, you may try it if interested

**Pull request merged**
