### PR TITLE
fix user account can show all the databases

### PR DESCRIPTION
**Pull request by qingxinhome**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7383

## What this PR does / why we need it:
Solve the following problems：
1. The system tenant can see all the combined information
2. Ordinary tenants can only see the data of the current tenant
3. Common tenants can see and access the mo_ Catalog database, and you can see the
mo_ database,mo_ tables,mo_ Columns Three tables

### CODE REVIEW

**Review by daviszhen — APPROVED** [review]

**Comment by sukki37** [comment]
could you add some bvt test cases please.

**Comment by qingxinhome** [comment]
> could you add some bvt test cases please.

OK, I will add bvt test cases. @sukki37

**Comment by ouyuanning** [comment]
better to have some bvt test

**Comment by qingxinhome** [comment]
I will deal with it as soon as possible

**Review by aressu1985 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by heni02 — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Pull request merged**
