### PR TITLE
Support parallel insert only for Load statement

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

### CODE REVIEW

**Comment by m-schen** [comment]
do not merge this pr, until issue #5302 is fixed.

**Comment by m-schen** [comment]
> do not merge this pr, until issue #5302 is fixed.

and should change the code `insertParallelNumber = 2` in file `compile.go` to be flexible.

**Review by fengttt — COMMENTED** [review]
You know this thing does not work, as of TAE today, right?   We need to make "directly write S3" operation working.

**Comment by m-schen** [comment]
does not need this work now.

**Pull request closed without merging**
