### PR TITLE
fix: desc table key error

### PR DESCRIPTION
**Pull request by xmh1011**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #14166 #14168 

## What this PR does / why we need it:
When the unqiue key meet the following conditions, it is the primary key of the table.
1. There is no primary key in the table.
2. The unique key is the only unique key of the table.
3. The column of the unique key is not null by default.

### CODE REVIEW

**Comment by matrix-meow** [comment]
@xmh1011 Thanks for your contributions!

Title: fix: desc the primary key of the table as unique key

Body: This pull request fixes an issue (#14166) where the primary key of a table was not being correctly described as a unique key. The changes made in this pull request include adding a new function `isPrimaryKey` to check if a unique key is the primary key of the table, and modifying the `buildShowColumns` function to correctly describe the primary key as "PRI" instead of "UNI" in the output.

Changes:
- Added a new function `isPrimaryKey` to check if a unique key is the primary key of the table.
- Modified the `buildShowColumns` function to correctly describe the primary key as "PRI" instead of "UNI" in the output.
- Updated test cases to reflect the correct description of the primary key.

Review:

1. In the `isPrimaryKey` function, the variable `uniqueKeyCount`

**Review by YANGGMM — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by aunjgr — COMMENTED** [review]
Is this behavior well discussed?

**Comment by xmh1011** [comment]
> Is this behavior well discussed?

测试过程和测试用例可以参见 #14168 ，研究了mysql中MUL、PRI和UNI三种键的定义，重新修改了逻辑。

**Comment by xmh1011** [comment]
> Is this behavior well discussed?

在Mysql中，CREATE TABLE时创建的UNIQUE KEY在DESC TABLE是，会有三种表现形式，分别为：

- PRI 符合在pr描述内提到的三个条件是，UNIQUE KEY为主键。
- MUL 当UNIQUE KEY包含两列且不是主键时（譬如UNIQUE KEY(a, b)），则a列的键为MUL。
- 当不符合以上两种情况时，UNIQUE KEY显示为UNI。

对于MUL KEY。譬如创建时KEY (a, b)，则只有a列的键显示为MUL，b列没有键。

**Pull request merged**
