### PR TITLE
txn: initialize the clock in main

### PR DESCRIPTION
**Pull request by zhangxu19830126**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
initialize the clock in main

### CODE REVIEW

**Review by nnsgmsone — APPROVED** [review]

**Review by reusee — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by reusee — APPROVED** [review]

**Comment by xzxiong** [comment]
@zhangxu19830126 is there any way to close clock check, for debug sometime ?

**Comment by reusee** [comment]
> @zhangxu19830126 is there any way to close clock check, for debug sometime ?

No reason to close clock checking since it's exposing bugs.

**Review by cnutshell — APPROVED** [review]

**Comment by zhangxu19830126** [comment]
@matrix-meow rerun failed

**Comment by xzxiong** [comment]
> > @zhangxu19830126 is there any way to close clock check, for debug sometime ?
> 
> No reason to close clock checking since it's exposing bugs.

actually, yesterday, i need debug step-by-step ON IDE.goland with etc `./mo-service -launch ./etc/launch-dist-tae/launch.toml`.
clock checking make process stop almost everytime.

**Comment by zhangxu19830126** [comment]
> 

Set clock maxOffset to math.MaxInt64.

**Comment by xzxiong** [comment]
> @xzxiong Set clock maxOffset to math.MaxInt64.

got it.

**Pull request merged**
