### PR TITLE
fix load local hung

### PR DESCRIPTION
**Pull request by daviszhen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/MO-Cloud/issues/3034

## What this PR does / why we need it:

之前对autoflush的使用有错误。load 也没有回归，导致问题没抓住。

后面网络的调整pr，会再这一块做调整。

load已经加入到回归中。https://github.com/daviszhen/morunner

ci regression。 https://github.com/matrixorigin/ci-test/actions/runs/8739151861

### CODE REVIEW

**Review by qingxinhome — APPROVED** [review]

**Comment by daviszhen** [comment]
@mergify refresh

**Comment by daviszhen** [comment]
@mergify refresh

**Comment by daviszhen** [comment]
@mergify refresh

**Comment by daviszhen** [comment]
@mergify refresh

**Comment by daviszhen** [comment]
@mergifyio refresh

**Pull request merged**
