### PR TITLE
udf execution

### PR DESCRIPTION
**Pull request by chrisxu333**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

### CODE REVIEW

**Review by aressu1985 — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by reusee — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]
lgtm

**Review by sukki37 — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
test cases are too weak.

At lease you should have something like,

select sum(col1, col2) from t where col3 > 0;

select sum(t1.col1, t2.col2) from t1, otherschema.t2 where t1.id = t2.id

**Comment by chrisxu333** [comment]
> test cases are too weak.
> 
> At lease you should have something like,
> 
> select sum(col1, col2) from t where col3 > 0;
> 
> select sum(t1.col1, t2.col2) from t1, otherschema.t2 where t1.id = t2.id

Okay will do

**Comment by fengttt** [comment]
> test cases are too weak.
> 
> At lease you should have something like,
> 
> select sum(col1, col2) from t where col3 > 0;
> 
> select sum(t1.col1, t2.col2) from t1, otherschema.t2 where t1.id = t2.id

And some function like create function xxx(x) as select sum(col) from t where colx = x
then test the function.

**Review by heni02 — APPROVED** [review]

**Pull request merged**
