### PR TITLE
replay code refactor to process log entry as a normal transaction

### PR DESCRIPTION
**Pull request by XuPeng-SH**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

1. Fix a deadlock bug
2. Refactor transaction code
3. Refactor replay code to process every replay log entry as a normal transaction

### CODE REVIEW

**Review by LeftHandCold — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
How will this affect CN?   Is there a test at all?

**Comment by XuPeng-SH** [comment]
> How will this affect CN? Is there a test at all?

This has nothing to do with CN, it is just to refactor the implementation of the log replay

**Comment by fengttt** [comment]
> 

no test, no comment, nothing?

**Comment by XuPeng-SH** [comment]
> > 
> 
> no test, no comment, nothing?

The main purpose here is to reorganize some code for log replay, and the related unit tests have always existed:
https://github.com/XuPeng-SH/matrixone/blob/refactor-1015-1/pkg/vm/engine/tae/db/replay_test.go

Comment was not added due to time constraints

**Review by reusee — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by fengttt — APPROVED** [review]

**Pull request merged**
