### PR TITLE
delay ranges call for dml queries

### PR DESCRIPTION
**Pull request by badboynt1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #15598 

## What this PR does / why we need it:
delay ranges call for dml queries

### CODE REVIEW

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/10662523187

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/10662523187/job/29768050067
又跑了一次，这次跑的过程中没有报错，但是跑完以后依然有数据不一致现象。
2024-09-06 07:14:21 INFO  ConsistencyCheck:192 - user=tpcc_test:admin
2024-09-06 07:14:27 ERROR ConsistencyCheck:99 - Consistency verification failed for sql : select s_w_id, s_i_id,count(1) from bmsql_stock group by s_w_id, s_i_id having count(1) > 1 limit 10;
2024-09-06 07:14:27 ERROR ConsistencyCheck:100 - The exceptional result are :
2	96972	2	
9	12885	2	
9	62037	2	
9	47924	2	
4	2733	2	
7	23118	2	
6	85334	2	
4	79694	2	
8	5046	2	
7	27476	2

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/10914561416/job/30293034879   即使单跑tpcc也能复现问题

**Comment by gouhongshen** [comment]
> https://github.com/matrixorigin/ci-test/actions/runs/10914561416/job/30293034879 即使单跑tpcc也能复现问题

本地多 cn 也能跑出来

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/11314096409

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/11400550004

**Pull request merged**
