### PR TITLE
tae sort refactor

### PR DESCRIPTION
**Pull request by aptend**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #7565 

## What this PR does / why we need it:

remove redundant sort codes and support sort null

### CODE REVIEW

**Review by fengttt — APPROVED** [review]
Thank you ...

**Review by aressu1985 — APPROVED** [review]

**Comment by sukki37** [comment]
please resolve conflicts

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by aptend** [comment]
> please resolve conflicts

@sukki37 resolved, PTAL

**Review by sukki37 — APPROVED** [review]

**Pull request merged**
