### PR TITLE
remove indexes of sys_async_task & truncate completed tasks

### PR DESCRIPTION
**Pull request by w-zr**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #18494

## What this PR does / why we need it:

remove some indexes of sys_async_task.
truncate completed tasks when schedule new tasks.

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Removed indexes from the `sys_async_task` table to optimize performance.
- Added a new method `TruncateCompletedTasks` in `taskService` to delete completed tasks.
- Integrated task truncation logic into the task scheduler.
- Updated the `TaskService` interface to include the new truncation method.
- Added mock methods for testing the truncation of completed tasks.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>service.go</strong><dd><code>Remove indexes from sys_async_task table</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/bootstrap/service.go

- Removed several index creation statements for `sys_async_task`.

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18495/files#diff-039df642b3e87d67d13b390b18fdd973de5404f34ffecbfa38da6eb4ea06969c">+0/-11</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task_scheduler.go</strong><dd><code>Implement task truncation in scheduler</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/hakeeper/task/task_scheduler.go

- Added logic to truncate completed tasks in the scheduler.

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18495/files#diff-d2fda06e3820871d9c91abe96bbd162230ca3607d9f9899bcb3955c93981962d">+18/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task_service.go</strong><dd><code>Add method to truncate completed tasks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/taskservice/task_service.go

- Added method to truncate completed tasks in task service.

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18495/files#diff-f38b75a2fbc93d540b0bc58427e36a4c8dc1481120dc39819ed282e90f530cc9">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>types.go</strong><dd><code>Extend TaskService interface with truncation method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/taskservice/types.go

- Added `TruncateCompletedTasks` method to `TaskService` interface.

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18495/files#diff-1e281a929a767be8d9226fe111a72e856b2b4f7ae3cbe16bb7e6cd31833dede7">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>types.go</strong><dd><code>Add mock methods for truncating completed tasks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/frontend/test/mock_task/types.go

- Added mock methods for truncating completed tasks.

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18495/files#diff-0d1f4f1f51fd5864bd5ae2079ad70c347d8afce1ca90ece521da3d8328223ccb">+14/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by fengttt — CHANGES_REQUESTED** [review]
predefine.go must be fixed as well.

**Comment by w-zr** [comment]
> predefine.go must be fixed as well.

The indexes are defined in `pkg/bootstrap/service.go`. They are removed.

**Review by zhangxu19830126 — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by LeftHandCold — APPROVED** [review]

**Review by qingxinhome — APPROVED** [review]

**Comment by w-zr** [comment]
unique constraint is removed from sys_async_task.

**Review by qingxinhome — COMMENTED** [review]
need add upgrade entry for this pr

**Review by qingxinhome — CHANGES_REQUESTED** [review]
need add upgrade entry for this pr

**Review by qingxinhome — APPROVED** [review]

**Review by fengttt — APPROVED** [review]

**Pull request merged**
