### PR TITLE
Remove dump stmt

### PR DESCRIPTION
**Pull request by mooleetzi**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [X] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
now we use an executable to handle dump, modump stmt need to remove

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
What are you doing?   You created a new command mo_dump, correct?   So the command is still there?   This one just REMOVED a feature?

Fine, then how is mo_dump tested?

**Comment by mooleetzi** [comment]
> What are you doing? You created a new command mo_dump, correct? So the command is still there? This one just REMOVED a feature?
> 
> Fine, then how is mo_dump tested?

Remove stmt, use mo-dump(binary) to handle dump.
I now do not know how to test mo-dump, it cannot be in bvt.

**Review by aressu1985 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Comment by fengttt** [comment]
> 

Ask Su Dong, if the test framework allows calling an external command.    For example, this.

System Command
The \system (\!) command runs the operating system command that you specify as an argument to the command, then displays the output from the command in MySQL Shell. MySQL Shell returns an error if it was unable to execute the command. The output from the command is returned as given by the operating system, and is not processed by MySQL Shell's JSON wrapping function or by any external pager tool that you have specified to display output.

Then you can call the command it the test and check dumped result.

**Comment by mooleetzi** [comment]
> Ask Su Dong, if the test framework allows calling an external command. For example, this.
> 
> System Command The \system (!) command runs the operating system command that you specify as an argument to the command, then displays the output from the command in MySQL Shell. MySQL Shell returns an error if it was unable to execute the command. The output from the command is returned as given by the operating system, and is not processed by MySQL Shell's JSON wrapping function or by any external pager tool that you have specified to display output.
> 
> Then you can call the command it the test and check dumped result.

Ok, I will check with Su Dong. Thx.

**Comment by fengttt** [comment]
> 

Either ask Su Dong to implmeent this, or better, do it yourself.    Enable dump test, before you can remove this feautre.

**Comment by mooleetzi** [comment]
> Either ask Su Dong to implmeent this, or better, do it yourself. Enable dump test, before you can remove this feautre.

Ok, I will do this

**Review by daviszhen — APPROVED** [review]

**Pull request closed without merging**
