### PR TITLE
add engine type in Query

### PR DESCRIPTION
**Pull request by ouyuanning**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

as discuss with @nnsgmsone .
add query type in Query Struct.

that will be Set by optimizer.  Be used in executor

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by nnsgmsone — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
Why do we need this?   This does not need to be a field -- why not just a function on the plan?

**Comment by nnsgmsone** [comment]
> Why do we need this? This does not need to be a field -- why not just a function on the plan?

I think either is fine, as long as can state whether a plan is tp or ap

**Comment by ouyuanning** [comment]
> Why do we need this? This does not need to be a field -- why not just a function on the plan?

if it's a status for long life and used many times.  that will be a field better.

**Comment by fengttt** [comment]
> 

I think it is a one time thing -- and actually I am not sure letting optimizer set it is a good thing.    I can imagine executor need more flexibility.   For example, executor may want such a function.

func getExecType(plan, Flags) ExecInfo

Where flags can say let me know if this is AP or TP, or AP and run on big memroy machine, or AP run with GPU, etc. etc, ExecType may return yeah, run as AP, and suggest executor to run on 4, or 8, or whatever the appropriate number of CNs.

**Comment by ouyuanning** [comment]
> > 
> 
> I think it is a one time thing -- and actually I am not sure letting optimizer set it is a good thing. I can imagine executor need more flexibility. For example, executor may want such a function.
> 
> func getExecType(plan, Flags) ExecInfo
> 
> Where flags can say let me know if this is AP or TP, or AP and run on big memroy machine, or AP run with GPU, etc. etc, ExecType may return yeah, run as AP, and suggest executor to run on 4, or 8, or whatever the appropriate number of CNs.

ok.

**Pull request closed without merging**
