### PR TITLE
fix nil data issue of const vector

### PR DESCRIPTION
**Pull request by dongdongyang33**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5268

## What this PR does / why we need it:

Const vector only records the data in Col[] while its data[] is nil
so it will panic when we try to get data/pointer from const vector data[].

Fix this issue by making the behavior of const vector the same as the vector.

### CODE REVIEW

**Review by nnsgmsone — APPROVED** [review]

**Comment by dongdongyang33** [comment]
@matrix-meow rerun failed

**Comment by dongdongyang33** [comment]
@matrix-meow rerun failed

**Comment by dongdongyang33** [comment]
@matrix-meow rerun failed

**Comment by dongdongyang33** [comment]
@matrix-meow rerun failed

**Pull request merged**
