### PR TITLE
support bool logic operator and compare operator in pipeline

### PR DESCRIPTION
**Pull request by jianwan0214**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2419 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by nnsgmsone** [comment]
FixedLength for bool must be implemented;

**Review by fengttt — COMMENTED** [review]
I am confused -- are you saying we need to implement a quick sort for
1. asc and desc,
2. every type?

This is 2*N copy of quicksort!

**Comment by jianwan0214** [comment]
> I am confused -- are you saying we need to implement a quick sort for
> 
> 1. asc and desc,
> 2. every type?
> 
> This is 2*N copy of quicksort!

yes, this is the current code logic. I think these code can be restructured later.

**Comment by nnsgmsone** [comment]
Please be mindful of performance and use batch processing.

**Review by fengttt — APPROVED** [review]
Approve based on the assumption that we will fix/resolve all the sorts later.

**Pull request merged**
