### PR TITLE
rewrite the operator dispatch.

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

maybe about issue #14009 

## What this PR does / why we need it:
rewrite all the codes and unit-tests of the dispatch.
move the action `wait remote receivers ready` to the prepare stage.
removed unused codes.

### CODE REVIEW

**Comment by m-schen** [comment]
只是先提pr简单跑跑看，没有做代码整理等工作。不需要真正合并。

**Comment by matrix-meow** [comment]
@m-schen Thanks for your contributions!

**Here are review comments for file pkg/common/hashmap/joinmap.go:**
Title: rewrite the operator dispatch.

Body: This pull request is a code refactoring that aims to rewrite the operator dispatch. The changes include moving the action "wait remote receivers ready" to the prepare stage and removing unused code. It may also address issue #14009.

Changes in file pkg/common/hashmap/joinmap.go:
- Added a new method `SetRef(ref int64)` that sets the reference count of the JoinMap using atomic operations.
- Modified the `IncRef(ref int64)` method to use atomic operations to increment the reference count of the JoinMap.
- Added a new method `SetDupCount(ref int64)` that sets the duplicate count of the JoinMap using atomic operations.
- Modified the `IncDupCount(ref int64)` method to use atomic operations to increment the duplicate count of the JoinMap.

Review:

1. Inconsistent naming convention: The new methods `SetRef` and `SetDupCount` use a different naming convention compared to the existing methods in the JoinMap struct. It would be better to follow the same naming convention to maintain consistency.

Suggestion: Rename `SetRef` to `SetCnt` and `SetDupCount` to `SetDupCnt` to match the existing method names.

2. Lack of error handling: The new methods `SetRef` and `SetDupCount` do not handle any potential errors that may occur during the atomic operations. It is important to handle errors properly to ensure the reliability of the code.

Suggestion: Add error handling to the new methods, such as checking the return value of the atomic operations and handling any errors that may occur.

3. Unused code: The pull request mentions that unused code has been removed, but the diff provided does not show any removal of code. It would be helpful to provide more information about the specific unused code that was removed.

Optimization:

1. Consolidate atomic operations: The methods `IncRef` and `IncDupCount` both use atomic operations to increment the respective counters. Since these operations are similar, it would be more efficient to consolidate them into a single method that takes the counter and the increment value as parameters.

Suggestion: Create a new method, such as `IncCounter`, that takes the counter and the increment value as parameters and performs the atomic increment operation. This would reduce code duplication and improve maintainability.

2. Use constants for magic numbers: The methods `SetRef` and `SetDupCount` use magic numbers as parameters. It would be better to define constants for these numbers to improve code readability and maintainability.

Suggestion: Define constants for the magic numbers used in the `SetRef` and `SetDupCount` methods.

Overall, the code refactoring in this pull request seems to be focused on improving the dispatch logic and making use of atomic operations. However, there are some issues that need to be addressed, such as inconsistent naming, lack of error handling, and the need for more information about the removed unused code. Additionally, there are opportunities for optimization, such as consolidating atomic operations and using constants for magic numbers.

**Here are review comments for file pkg/sql/colexec/dispatch/dispatch.go:**
Title: rewrite the operator dispatch.

Body: The pull request is a code refactoring that aims to rewrite the operator dispatch. It also includes moving the action "wait remote receivers ready" to the prepare stage and removing unused code.

Changes made in the file pkg/sql/colexec/dispatch/dispatch.go:
- Removed unused imports and variables.
- Removed the Prepare() function, which was responsible for preparing the dispatch operation.
- Removed the printShuffleResult() function, which was used to print the shuffle result.
- Removed the Call() function, which was responsible for executing the dispatch operation.
- Removed the waitRemoteRegsReady() function, which was used to wait for remote receivers to be ready.
- Removed the prepareRemote() function, which was used to prepare the dispatch operation for remote receivers.
- Removed the prepareLocal() function, which was used to prepare the dispatch operation for local receivers.
- Modified the makeEndBatch() function to handle errors when appending bytes to the batch vector.

Overall, the changes made in this pull request remove unused code and simplify the dispatch operation by removing unnecessary functions and logic.

Potential problems and suggestions:
1. The pull request removes the Prepare() function, which was responsible for preparing the dispatch operation. It is unclear how the dispatch operation is now being prepared. It would be helpful to provide an explanation or update the code to show the new approach for preparing the dispatch operation.

2. The pull request removes the waitRemoteRegsReady() function, which was used to wait for remote receivers to be ready. It is unclear how this functionality is now being handled. If waiting for remote receivers is still necessary, it should be addressed in the code or explained in the pull request description.

3. The pull request removes the prepareRemote() and prepareLocal() functions, which were used to prepare the dispatch operation for remote and local receivers, respectively. It is unclear how the dispatch operation is now being prepared for different types of receivers. If this functionality is still required, it should be addressed in the code or explained in the pull request description.

4. The makeEndBatch() function now handles errors when appending bytes to the batch vector. However, the error is not being returned or handled in the calling code. It is recommended to update the calling code to handle the error appropriately.

5. It would be helpful to provide more context or explanation in the pull request description about why these changes were made and what benefits they bring to the codebase.

Optimization suggestions:
1. Consider providing more detailed commit messages for each individual change made in the pull request. This will make it easier for reviewers to understand the purpose and impact of each change.

2. Consider adding comments or documentation to the code to explain the purpose and functionality of the dispatch operation, as well as any changes made in this pull request. This will make the code easier to understand and maintain in the future.

3. Consider running tests and ensuring that all existing functionality is still working as expected after the code refactoring. This will help prevent any regressions or issues introduced by the changes.

4. Consider reviewing the entire codebase for any other unused code or potential optimizations that can be made. This will help improve the overall quality and performance of the codebase.

**Here are review comments for file pkg/sql/colexec/dispatch/dispatch2.go:**
Review:

Title: rewrite the operator dispatch.

Body: The body of the pull request provides some context about the changes made. It mentions that the code for the dispatch has been rewritten, the action "wait remote receivers ready" has been moved to the prepare stage, and unused code has been removed. It also mentions that this is a code refactoring pull request.

Changes in pkg/sql/colexec/dispatch/dispatch2.go:
- The file has been completely rewritten.
- The `Prepare` function has been modified to initialize the `arg.ctr` struct and set the appropriate send function based on the `FuncId` value.
- The `Call` function has been modified to handle cancellation, call the child operator, and perform some analysis.
- The `waitRemoteReceiversReady` function has been added to prepare remote receivers and wait for them to be ready.

Potential problems and suggestions:
1. Security: The code does not appear to have any obvious security issues.

2. Code organization: The changes made in the pull request seem to improve the organization and readability of the code. The functions have been split into smaller, more focused functions, which can make the code easier to understand and maintain.

3. Error handling: The error handling in the `Prepare` and `waitRemoteReceiversReady` functions could be improved. Currently, if an error occurs, it is returned without any additional information or context. It would be helpful to provide more specific error messages or wrap the errors with additional context to aid in debugging.

4. Documentation: The code could benefit from more comments and documentation to explain the purpose and behavior of the functions and variables. This would make it easier for future developers to understand and modify the code.

5. Magic numbers: There are a few magic numbers in the code, such as the timeout value in the `waitRemoteReceiversReady` function. It would be better to define these values as constants or variables with meaningful names to improve code readability and maintainability.

6. Error handling in `Call` function: The `Call` function currently returns the result and error from the child operator without checking if the result is nil. It would be good to add a check to ensure that the result is not nil before accessing its properties.

Overall, the changes made in the pull request seem to improve the code organization and readability. However, there are some areas that could be further improved, such as error handling and documentation.

**Here are review comments for file pkg/sql/colexec/dispatch/types.go:**
Review:

Title: rewrite the operator dispatch.

Body: The pull request is a code refactoring that aims to rewrite the operator dispatch. The changes include moving the action "wait remote receivers ready" to the prepare stage and removing unused code.

Changes in pkg/sql/colexec/dispatch/types.go:
- Added a new type `senderStatus` to represent the status of the container.
- Added a `sendStatus` field to the `container` struct to store the status of the container.
- Added `sendFunc2` to the `container` struct, which is responsible for sending batches to the receivers.
- Added methods `startSending`, `stopSending`, and `isStopSending` to the `container` struct to control the sending status.
- Renamed the `Free` method in the `Argument` struct to `Free` and changed the parameter name `pipelineFailed` to `executeFailed`.
- Removed the unnecessary check for `pipelineFailed` in the `Free` method.

Suggestions:
1. The title of the pull request is clear and concise, indicating that the operator dispatch is being rewritten. No changes are needed for the title.

2. The body of the pull request is brief and provides a summary of the changes made. However, it would be helpful to provide more context on why the code refactoring was necessary and how it improves the codebase. Additionally, the reference to issue #14009 is unclear and should be clarified or removed if not relevant.

3. In the `container` struct, the `sendFunc` field is removed. It would be helpful to provide an explanation for this change and clarify how the new `sendFunc2` function is used.

4. The `Free` method in the `Argument` struct has been modified to remove the unnecessary check for `pipelineFailed`. It would be helpful to explain why this check was removed and how it affects the behavior of the method.

5. The changes made in the pull request seem to be focused on improving the code structure and organization. However, it would be helpful to provide more information on the performance impact of these changes and any potential optimizations that were considered.

Overall, the code changes in the pull request seem reasonable and focused on improving the codebase. However, the pull request description could be improved by providing more context and explanations for the changes made. Additionally, it would be helpful to address any potential security issues that may arise from the code changes.

**Comment by m-schen** [comment]
先别合，后续需要同步main上关于算子的一些修改到重写里头。
（如统计信息 https://github.com/matrixorigin/matrixone/pull/14370#pullrequestreview-1845092633，和去除info属性的pr https://github.com/matrixorigin/matrixone/pull/14295)。

**Comment by m-schen** [comment]
先关掉，太久了，同步不了main，冲突不会解决

**Pull request closed without merging**
