### PR TITLE
Check PK duplication on cn side when small txn commits

### LINKED ISSUE #13702: [Bug]:  Account ID in Compile.ctx is not same with the Account ID in txn.proc.ctx  when  run sql : create account test_account admin_name = 'test_user' identified by '111'
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 1.0-dev 1.1-dev

### Commit ID

51013537017

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

   txn.getTable returns fail when run sql-create account xxx  , since the account id in `txn.proc.ctx` and `compile.ctx` is not the same 

### Expected Behavior

`txn.getTable`  always return success if table exists.``

### Steps to Reproduce

```Markdown
Modify the code to triger the txn.getTable is called  when run sql : create account xxx
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by triump2020**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #13535 

## What this PR does / why we need it:

1. check pk duplication if txn's workspace size is  less than pk-dedup-count
2.  pk-dedup-count is configurable ,default is 0, which means don't do deduplication.
3.  fix #13702

### CODE REVIEW

**Comment by triump2020** [comment]
This PR depends on fixing #13702

**Comment by fengttt** [comment]
This should be confined and turned on/off as necessary.

**Review by fengttt — CHANGES_REQUESTED** [review]
config it please.

**Comment by triump2020** [comment]
> config it please.

ok

**Comment by triump2020** [comment]
The follow is the performance for main VS  this PR:

main : 

image


this PR when turn on the switch:
image

**Comment by triump2020** [comment]
need to unify these funciton

**Comment by triump2020** [comment]
tpcc 50-100

**Review by reusee — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by qingxinhome — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]

**Review by fengttt — APPROVED** [review]

**Pull request merged**
