### PR TITLE
[fix] : make runtime filter act on the correct node

### PR DESCRIPTION
**Pull request by jensenojs**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #15765

## What this PR does / why we need it:
make runtime filter act on the correct node

### CODE REVIEW

**Comment by jensenojs** [comment]
简单测验`runtime filter`的位置是否正确, 可以使用`explain insert into select`的方式看看

Pasted Graphic 8

**Comment by matrix-meow** [comment]
@jensenojs Thanks for your contributions!

### Pull Request Review:

#### Title:
The title of the pull request is clear and concise, indicating that the purpose of the PR is to fix an issue related to making the runtime filter act on the correct node.

#### Body:
The body of the pull request provides relevant information about the type of PR (BUG), the specific issue it fixes (issue #15765), and the reason for the changes made (making the runtime filter act on the correct node). It would be beneficial to include more details about the impact of the issue and how the fix addresses it.

#### Changes:
1. In the `build_constraint_util.go` file, the following changes were made:
   - Line 1311: A line related to `RuntimeFilterProbeList` was removed.
   - Line 1351-1352: A line related to `RuntimeFilterProbeList` was added.

#### Feedback and Suggestions:
1. **Redundant Code Removal:**
   - The removal of the `RuntimeFilterProbeList` assignment at line 1311 seems to have been unintentional or unnecessary. It might be a mistake that needs to be reverted or re-evaluated.
   - It appears that the same `RuntimeFilterProbeList` assignment is added back at lines 1351-1352. Ensure that the addition of this line is necessary and does not introduce duplication or unintended behavior.

2. **Code Consistency:**
   - Verify if the removal and addition of the `RuntimeFilterProbeList` assignment are consistent with the overall logic and requirements of the codebase. Ensure that the changes align with the intended behavior and do not introduce inconsistencies.

3. **Testing:**
   - It is essential to test the changes thoroughly to ensure that the runtime filter now correctly acts on the intended node. Consider adding or updating relevant tests to cover this scenario and prevent regressions.

4. **Code Optimization:**
   - Review the necessity of adding the `RuntimeFilterProbeList` assignment at the new location. If possible, consolidate or optimize the code to avoid redundancy and improve maintainability.

5. **Security Concerns:**
   - While the changes in the diff provided do not indicate any direct security issues, it is crucial to conduct a comprehensive security review to ensure that the modifications do not introduce vulnerabilities or weaken the system's security posture.

6. **Documentation:**
   - Consider updating any relevant documentation, comments, or guidelines affected by these changes to reflect the corrected behavior related to the runtime filter.

By addressing the points mentioned above and ensuring thorough testing, code consistency, and documentation updates, the quality and reliability of the codebase can be improved.

**Review by badboynt1 — APPROVED** [review]

**Comment by jensenojs** [comment]
使用
```sql
create table t0(a int primary key, b int);
insert into t0 select result, result from generate_series(1,10000000) g;
insert into t0 select result, result from generate_series(10000001, 20000000) g;
explain analyze INSERT INTO sensor_data1 (device_id, timestamp, value) VALUES (75, '2024-03-22 19:06:58', 0.565487);
```
的过滤结果如下所示 : 

image

**Comment by jensenojs** [comment]
用下面这个pr做跟踪
- https://github.com/matrixorigin/matrixone/pull/15771

**Pull request closed without merging**
