### PR TITLE
[Feature Request]: Support a non-primary-key table with sorting key #6959

### PR DESCRIPTION
**Pull request by badboynt1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6959 

## What this PR does / why we need it:
implement a new feature: cluster by
add ddl support in sql, waiting for storage engine to apply the sort key

### CODE REVIEW

**Review by daviszhen — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Review by ouyuanning — APPROVED** [review]

**Review by nnsgmsone — COMMENTED** [review]
Is this a fake thing. It doesn't actually sort of happen right?

**Comment by badboynt1** [comment]
> Is this a fake thing. It doesn't actually sort of happen right?

yes, waiting for @aptend to apply this in storage engine

**Comment by nnsgmsone** [comment]
> > Is this a fake thing. It doesn't actually sort of happen right?
> 
> yes, waiting for @aptend to apply this in storage engine

Oh, but I don't understand what the difference is between sort-key and sub-index.

**Review by iamlinjunhong — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
what if i want to cluster by several columns?   cluster by (a, b)?

**Review by fengttt — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Pull request merged**
