### PR TITLE
[fix] : remove pre check logic for create unique index for existed data

### PR DESCRIPTION
**Pull request by jensenojs**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/1631 https://github.com/matrixorigin/MO-Cloud/issues/1881

## What this PR does / why we need it:

only one test is enough

### CODE REVIEW

**Comment by matrix-meow** [comment]
@jensenojs Thanks for your contributions!

**Here are review comments for file pkg/container/types/tuple.go:**
### Pull Request Review:

#### Title: [fix] : remove pre-check logic for creating a unique index for existing data

#### Body:
- The PR is categorized as a bug fix.
- It references two specific issues on GitHub that this PR fixes.
- The description states that only one test is needed.

#### Changes in `pkg/container/types/tuple.go`:
- The changes in the file `tuple.go` involve modifying the `ErrString` and `SQLStrings` functions to handle `Decimal64` and `Decimal128` types when `scales` is `nil`.
- The changes introduce conditional checks to handle the case when `scales` is `nil` by using a default scale of 0.
- The modifications aim to address potential issues related to formatting `Decimal64` and `Decimal128` types when `scales` is not provided.

#### Feedback and Suggestions:
1. **Redundant Code**:
   - The changes made in the `ErrString` and `SQLStrings` functions are repetitive. The same conditional logic is duplicated for `Decimal64` and `Decimal128` types in both functions.
   - **Suggestion**: Consider refactoring the code to avoid duplication. You can create a helper function to handle the common logic for these two cases.

2. **Error Handling**:
   - The current implementation assumes that if `scales` is `nil`, using a default scale of 0 is sufficient. However, this may not always be the correct approach.
   - **Suggestion**: Instead of assuming a default scale, consider adding proper error handling or validation to ensure that the `scales` parameter is always provided with valid values.

3. **Consistency**:
   - The conditional checks for `Decimal64` and `Decimal128` types are inconsistent with the default case handling. In the default case, `t` is directly appended without any formatting.
   - **Suggestion**: Ensure consistency in how different types are handled within the switch statement to maintain code clarity and readability.

4. **Testing**:
   - The PR mentions that only one test is needed, but it's essential to verify the changes thoroughly, especially when modifying critical functions like `ErrString` and `SQLStrings`.
   - **Suggestion**: Write or update relevant test cases to cover the scenarios where `scales` is `nil` to validate the behavior of the modified functions.

5. **Security Concern**:
   - While the changes seem focused on fixing a specific issue, it's crucial to consider any potential security implications.
   - **Suggestion**: Conduct a security review to ensure that the modifications do not introduce any vulnerabilities, especially when handling sensitive data like decimals.

By addressing the mentioned points and considering the suggestions provided, the code quality can be improved, potential issues can be mitigated, and the changes can be optimized for better maintainability and reliability.

**Here are review comments for file pkg/sql/compile/ddl.go:**
### Pull Request Review:

#### Title:
The title of the pull request is clear and concise, indicating that the PR is a bug fix related to removing pre-check logic for creating a unique index for existing data.

#### Body:
The body of the pull request provides information about the type of PR (BUG), the issues it fixes, and a brief explanation of why the PR is needed. It references specific issues on GitHub that are being addressed by this PR.

#### Changes in `pkg/sql/compile/ddl.go`:
1. **Problem 1: Pre-Check Logic Removal:**
   - The changes in the code remove the pre-check logic for creating a unique index for existing data.
   - The comments added explain that when creating a unique index for an existing table, there is no need to check it in advance because it will be checked when inserting data into the hidden table.
   - **Suggestion:** While removing unnecessary pre-checks can improve performance, it is crucial to ensure that the data integrity is maintained. Consider adding a comment to clarify that the data integrity will still be enforced during data insertion.

2. **Optimization Opportunity:**
   - The code changes in both `AlterTableInplace` and `CreateIndex` functions are similar.
   - **Suggestion:** Consider refactoring the common logic into a separate function to avoid code duplication and improve maintainability.

3. **Security Concern:**
   - It's important to ensure that removing the pre-check logic does not introduce any security vulnerabilities.
   - **Suggestion:** Perform thorough testing to verify that the removal of pre-checks does not compromise the integrity of the data or introduce any potential security risks.

### Overall Suggestions:
- Ensure that the removal of pre-check logic does not compromise data integrity.
- Consider refactoring common logic to improve code maintainability.
- Conduct thorough testing to validate the changes and address any potential security concerns.

By addressing these points, the pull request can be enhanced to ensure the code remains efficient, secure, and maintainable.

**Here are review comments for file pkg/sql/compile/types.go:**
### Pull Request Review:

#### Title:
The title of the pull request indicates that it is a fix to remove pre-check logic for creating a unique index for existing data.

#### Body:
The body of the pull request specifies that this is a bug fix related to issues #1631 and #1881. It also mentions that only one test is necessary.

#### Changes in `pkg/sql/compile/types.go`:
- Added a new field `onlyInsertHidden` to the `fuzzyCheck` struct.
- The comment explains that this change is related to handling cases like creating a unique index for an existing table or altering to add a unique key, specifically when the type of unique key is compound.

### Feedback and Suggestions:
1. **Code Clarity:**
   - The addition of the `onlyInsertHidden` field seems appropriate for the described use case. However, the name could be more descriptive to clearly convey its purpose. Consider renaming it to something like `isUniqueIndexForExistingTable`.
  
2. **Comment Clarity:**
   - The comment explaining the purpose of the `onlyInsertHidden` field is helpful. It is recommended to ensure that comments are clear, concise, and accurately describe the intent behind the code changes.

3. **Code Optimization:**
   - Since this change involves adding a new field to a struct, ensure that this addition does not introduce any unnecessary complexity or overhead. Review the usage of this field in the codebase to confirm its necessity.

4. **Testing:**
   - As mentioned in the PR body, only one test is deemed sufficient. However, it is crucial to ensure that the test thoroughly covers the scenarios affected by this change to prevent regressions.

5. **Security Concerns:**
   - Ensure that the addition of the `onlyInsertHidden` field does not introduce any security vulnerabilities, especially when handling unique indexes for existing data. Perform a security review to identify and address any potential risks.

6. **Consistency:**
   - Maintain consistency in naming conventions and coding style throughout the codebase to enhance readability and maintainability.

By addressing the points mentioned above, you can improve the clarity, efficiency, and security of the codebase while ensuring that the changes align with the intended functionality.

**Here are review comments for file pkg/sql/compile/util.go:**
### Pull Request Review:

#### Title and Body:
The title of the pull request indicates that it is a bug fix related to removing pre-check logic for creating a unique index for existing data. The body of the pull request mentions that only one test is needed. The issue numbers related to the fix are also provided.

#### Changes in `pkg/sql/compile/util.go`:
1. **Removed Code:**
   - The pull request removes the `genNewUniqueIndexDuplicateCheck` function which was responsible for generating SQL to check for duplicate entries when creating a new unique index.
   - It also removes the import statements for `moerr` and `vector`.

2. **Modified SQL Queries:**
   - The SQL queries `fuzzyNonCompoundCheck` and `fuzzyCompoundCheck` have been updated to include backticks around the table names to ensure proper handling of special characters in table names.

#### Suggestions for Improvement:
1. **Security Concerns:**
   - The removal of the `genNewUniqueIndexDuplicateCheck` function might introduce a security risk by not checking for duplicate entries when creating a new unique index. It's crucial to ensure data integrity by verifying uniqueness before creating indexes. Consider revisiting this logic to prevent unintended duplicates.
  
2. **Code Optimization:**
   - Instead of completely removing the `genNewUniqueIndexDuplicateCheck` function, consider refactoring it to improve its efficiency or readability. It might be beneficial to enhance the function rather than removing it entirely.

3. **Consistency in SQL Queries:**
   - Ensure consistency in SQL query formatting. Since the table names are now enclosed in backticks in the modified queries, ensure that this formatting is consistent throughout the codebase for better readability and maintenance.

4. **Testing:**
   - Although the body mentions that only one test is needed, it's essential to verify that the removal of the `genNewUniqueIndexDuplicateCheck` function does not introduce any regressions. Consider adding appropriate tests to validate the behavior of the code after this change.

5. **Documentation:**
   - Update relevant documentation or comments to reflect the changes made in the codebase. This will help developers understand the purpose of the removed function and the modifications in the SQL queries.

By addressing the security concerns, optimizing the code changes, ensuring consistency, performing thorough testing, and updating documentation, the pull request can be enhanced to maintain code quality and functionality.

Overall, while the removal of unnecessary code is beneficial, it's crucial to ensure that essential functionality like data integrity checks are not compromised in the process.

**Here are review comments for file test/distributed/cases/ddl/alter_add_unique_index.result:**
### Pull Request Review:

#### Title: 
The title of the pull request is clear and concise, indicating that the fix is related to removing pre-check logic for creating a unique index for existing data.

#### Body:
The body of the pull request provides information on the type of PR (BUG), the issues it fixes, and a brief explanation of why the PR is needed. It references specific GitHub issues that are being addressed.

#### Changes:
1. The changes in the `alter_add_unique_index.result` file involve adding and modifying SQL statements related to creating tables, inserting data, adding unique keys, and dropping tables. The changes seem to be related to testing unique index creation and handling duplicate entries.

#### Feedback and Suggestions:
1. **Testing Coverage**: It's important to ensure that the tests cover various scenarios comprehensively. Consider adding more test cases to cover different data types, edge cases, and potential error scenarios related to unique index creation.
   
2. **Error Handling**: The test cases reveal duplicate entry errors, which are expected when adding unique keys. Ensure that the application handles such errors gracefully, providing appropriate feedback to users or logging the errors for further investigation.

3. **Data Consistency**: When testing unique constraints, it's crucial to verify that data integrity is maintained. Ensure that the unique keys are enforced correctly and that the data remains consistent after adding unique constraints.

4. **Optimization**: Review the test cases to see if there are any redundant or unnecessary steps that can be removed to streamline the testing process. This can help improve the efficiency of the tests and make them easier to maintain.

5. **Security Concerns**: While the changes seem to focus on testing, it's essential to ensure that sensitive data is handled securely. Avoid hardcoding sensitive information in tests and consider using mock data or anonymized data where possible to prevent exposure of real data.

6. **Documentation**: Consider adding comments or documentation within the test cases to explain the purpose of each test scenario and the expected outcomes. This can help developers understand the tests better and maintain them in the future.

7. **Code Consistency**: Ensure that the naming conventions, formatting, and structure of the test cases are consistent with the existing codebase to maintain readability and clarity.

By addressing these points, you can enhance the quality and reliability of the codebase, improve testing practices, and ensure that the unique index creation logic functions correctly under various conditions.

**Here are review comments for file test/distributed/cases/ddl/alter_add_unique_index.sql:**
### Pull Request Review:

#### Title: 
- The title indicates that the pull request is fixing an issue related to removing pre-check logic for creating a unique index for existing data.

#### Body:
- The body of the pull request specifies that it is a bug fix related to issues #1631 and #1881.
- The reason provided for the PR is "only one test is enough," which is a bit vague and could be more descriptive.

#### Changes:
- The changes in the `alter_add_unique_index.sql` file involve adding test cases for creating composite unique keys with different data types and checking for duplicates.
- The test cases cover scenarios where unique keys are added and expected to fail due to duplicate values.
- The test cases also include adding a unique key for an empty char column.

### Feedback and Suggestions:
1. **Missing Description in PR Body:**
   - The PR body could benefit from a more detailed explanation of the changes made and why the pre-check logic for creating unique indexes for existing data was removed.

2. **Security Concern - Data Privacy:**
   - The test data being inserted into the tables contains sensitive information like dates, decimals, and potentially identifiable values. It's crucial to ensure that test data does not expose any sensitive information. Consider using generic or anonymized data for testing purposes.

3. **Optimization of Test Cases:**
   - The test cases could be optimized by ensuring they cover a wider range of scenarios, including edge cases and boundary conditions, to enhance the robustness of the tests.

4. **Consistency in Naming Conventions:**
   - Ensure consistent naming conventions for keys, tables, and columns to maintain clarity and readability in the codebase.

5. **End of File Indicator:**
   - Add a newline at the end of the file to comply with standard file formatting practices.

6. **Documentation Update:**
   - Consider updating any relevant documentation to reflect the changes made in the test cases for creating unique indexes.

7. **Code Review:**
   - Perform a thorough code review to ensure adherence to coding standards, error handling, and best practices.

By addressing the security concerns, optimizing test cases, improving documentation, and ensuring code quality, the pull request can be enhanced to contribute positively to the codebase.

**Here are review comments for file test/distributed/cases/optimistic/unique_secondary_index.result:**
### Pull Request Review:

#### Title:
The title of the pull request is clear and concise, indicating that the fix is related to removing pre-check logic for creating a unique index for existing data.

#### Body:
The body of the pull request provides information about the type of PR (BUG), the issues it fixes, and a brief explanation of why the PR is needed. It references two specific issues and mentions that only one test is necessary.

#### Changes:
The changes made in the pull request involve modifying the file `test/distributed/cases/optimistic/unique_secondary_index.result`. The changes include updating error messages related to duplicate entries for keys in the index creation process.

#### Feedback and Suggestions for Improvement:
1. **Error Message Clarity:**
   - The error messages in the changes seem to have been modified to include a specific key name (`__mo_index_idx_col`) instead of the original column name. While this change may be intended to provide more context, it is important to ensure that the key name used in the error message accurately reflects the nature of the error. Verify that `__mo_index_idx_col` is the appropriate key name to be displayed in these error messages.

2. **Consistency in Error Messages:**
   - It is crucial to maintain consistency in error messages across the codebase. Ensure that the error messages for duplicate entries follow a standardized format and provide clear information to developers and users.

3. **Testing:**
   - Since the PR mentions that only one test is needed, it is essential to verify that the test adequately covers the scenarios related to unique index creation for existing data. Consider adding additional test cases if necessary to cover edge cases and ensure comprehensive testing.

4. **Code Optimization:**
   - Review the changes to see if there are any opportunities for code optimization or refactoring. Ensure that the modifications are efficient and do not introduce unnecessary complexity.

5. **Security Considerations:**
   - When handling unique indexes and error messages related to key constraints, it is important to consider potential security implications. Verify that the changes do not inadvertently expose sensitive information or create vulnerabilities.

6. **Documentation:**
   - Update any relevant documentation to reflect the changes made in the code. Ensure that developers have access to up-to-date information regarding unique index creation and error handling.

In conclusion, while the pull request addresses a specific bug related to unique index creation, it is essential to review the changes thoroughly to ensure accuracy, consistency, and security. Additionally, consider optimizing the code and enhancing testing to maintain the overall quality of the codebase.

**Here are review comments for file test/distributed/cases/pessimistic_transaction/unique_secondary_index.result:**
### Pull Request Review:

#### Title: 
The title of the pull request is clear and concise, indicating that the fix is related to removing pre-check logic for creating a unique index for existing data.

#### Body:
The body of the pull request provides information about the type of PR (Bug fix), the issues it fixes, and a brief explanation of the changes made.

#### Changes:
1. In the file `test/distributed/cases/pessimistic_transaction/unique_secondary_index.result`, the changes involve modifying error messages related to duplicate entries for unique indexes. The key names for the unique indexes have been changed from 'col2' and 'col3' to '__mo_index_idx_col' for better identification.

### Feedback and Suggestions:

1. **Key Naming for Unique Indexes:**
   - Issue: Changing the key names for unique indexes from 'col2' and 'col3' to '__mo_index_idx_col' may not be descriptive enough and could potentially cause confusion.
   - Suggestion: Consider using more meaningful and descriptive key names that clearly indicate the column associated with the unique index to improve clarity and maintainability.

2. **Error Message Clarity:**
   - Issue: The error messages for duplicate entries in the unique indexes have been modified, but they may still lack clarity and context.
   - Suggestion: Enhance the error messages to provide more specific information about the duplicate entry and the corresponding key, which can help in troubleshooting and debugging.

3. **Testing:**
   - Issue: The pull request mentions that "only one test is enough," which may indicate a lack of comprehensive testing.
   - Suggestion: Ensure that the changes are thoroughly tested with various scenarios to validate the behavior of unique indexes and error handling.

4. **Code Optimization:**
   - Consider refactoring the code to improve readability and maintainability. Ensure that the changes follow consistent coding standards and best practices.

5. **Security Concerns:**
   - Ensure that the changes do not introduce any security vulnerabilities, especially when handling unique indexes and error messages related to data integrity.

By addressing the above points, the pull request can be enhanced to improve the quality and reliability of the codebase. Additionally, thorough testing and code review can help in identifying and resolving any potential issues before merging the changes.

**Comment by jensenojs** [comment]
两个issue, 一个是4.2亿的表alter add unique index, 一个是16亿的表create unique index on xxx, 这里选用16亿的表在本地测, 测试结果如下所示

image

**Comment by jensenojs** [comment]
upgrade ci 失败, 还不知道为什么


image

https://github.com/matrixorigin/matrixone/actions/runs/8627477221/job/23647521802?pr=15433

**Comment by jensenojs** [comment]
> upgrade ci 失败, 还不知道为什么
> 
> image
> https://github.com/matrixorigin/matrixone/actions/runs/8627477221/job/23647521802?pr=15433
> 
> update : 另外一个提给1.1-dev的pr的upgrade ci也有一样的报错
> 
> https://github.com/matrixorigin/matrixone/actions/runs/8627430201/job/23647385422?pr=15432

测试的时候, 下面这个pr还没有合并. 现在好了

https://github.com/matrixorigin/matrixone/pull/15333/files#diff-df23824b49f2821d75a690ad1320c27d7fa873f410d7a95e8ebe7737c4face32

**Review by nnsgmsone — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by heni02 — APPROVED** [review]

**Review by sukki37 — APPROVED** [review]

**Pull request merged**
