### PR TITLE
Fix the bug of double free detection in mpool

### PR DESCRIPTION
**Pull request by nnsgmsone**
## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9732

## What this PR does / why we need it:
* since the current mpool detection does not take competition into account, there may be some double free missed, and eventually mo will encounter the free > alloc error
* add some missing free

### CODE REVIEW

**Comment by matrix-meow** [comment]
@nnsgmsone Thanks for your contributions!

The pull request fixes a bug in the mpool package that causes double free detection to miss some cases. The changes made in the pull request include modifications to the `mpool.go`, `partition_reader.go`, and `txn_table.go` files. 

The title of the pull request is clear and concise, indicating that the pull request fixes a bug in the mpool package. The body of the pull request includes a checklist of the type of PR, the issue number that the PR fixes, and a brief description of what the PR does and why it is needed.

However, the body of the pull request could be improved by providing more details about the bug and how the changes fix it. Additionally, the body does not provide any information about how the changes were tested or any potential side effects of the changes.

In terms of the changes made in the pull request, the modifications to the `mpool.go` file appear to fix the bug by taking competition into account when detecting double free. The changes to the `partition_reader.go` and `txn_table.go` files appear to be unrelated to the bug fix and may have been accidentally included in the pull request.

To optimize the changes made in the pull request, the body of the pull request should provide more details about the bug and how the changes fix it. Additionally, the changes to the `partition_reader.go` and `txn_table.go` files should be removed from the pull request as they are unrelated to the bug fix. Finally, the pull request should include information about how the changes were tested and any potential side effects of the changes.

**Comment by nnsgmsone** [comment]
Note that the pr only fixes the detection mechanism for double free, so the pr may cause mo to encounter failures early in the runtime (previously it would only report errors when the free memory was larger than the alloc memory), but I think this is necessary to allow us to better locate memory problems

**Comment by fengttt** [comment]
this does not seems correct.   it is impossible for two thread modify the guard byte at the same time.   the atomic is not necessary.

**Review by zhangxu19830126 — APPROVED** [review]

**Comment by nnsgmsone** [comment]
> this does not seems correct. it is impossible for two thread modify the guard byte at the same time. the atomic is not necessary.

https://github.com/nnsgmsone/matrixone/blob/mpool/pkg/common/mpool/mpool.go#L556，The current code does not modify Guard's at the time of free. I see that the code is not guaranteed to capture double free. @fengttt

**Review by fengttt — APPROVED** [review]

**Pull request merged**
