### PR TITLE
optimize hash join on primary key

### PR DESCRIPTION
**Pull request by zengyan1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11577 

## What this PR does / why we need it:

### CODE REVIEW

**Comment by badboynt1** [comment]
tpch does not cover all join type. need more bvt tests on semi/right semi ,mark,single join and etc...

**Review by fengttt — COMMENTED** [review]
This kind of work need to have a benchmark measure and the improvement be included in commit message or issue.

**Comment by zengyan1** [comment]
WX20231016-130545@2x
WX20231016-130309@2x

**Comment by zengyan1** [comment]
tpch-10g的内存使用情况，其中hash build从506MB下降到了253MB

**Review by badboynt1 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by heni02 — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Pull request merged**
