### PR TITLE
fix a bitor problem of bit_or

### PR DESCRIPTION
**Pull request by NTH19**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

Which issue(s) this PR fixes:

#2168 

What this PR does / why we need it:

Special notes for your reviewer:

Not Available

Additional documentation (e.g. design docs, usage docs, etc.):

Not Available

### CODE REVIEW

**Comment by domingozhang** [comment]
result is correct now

**Comment by yingfeng** [comment]
Sorry, please resubmit this PR due to the merge error, thank you~

**Comment by domingozhang** [comment]
@NTH19 sorry, because of my fault, this commit didn't go through squash and merge. could you please raise it again.
thanks

**Comment by NTH19** [comment]
> @NTH19 sorry, because of my fault, this commit didn't go through squash and merge. could you please raise it again.
> 
> thanks

#2173

**Pull request merged**
