### PR TITLE
Fix 4963：The function of STARTSWITH() has a Prefix processing problem

### PR DESCRIPTION
**Pull request by YANGGMM**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4963 

## What this PR does / why we need it:
The function of STARTSWITH() has a Prefix processing problem

### CODE REVIEW

**Comment by ouyuanning** [comment]
pls add some ut and bvt

**Review by ouyuanning — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
Why this is an error?   Isn't false the right answer?

**Comment by fengttt** [comment]
startwith('foo', '') should be true,
startwith('', 'foo') should be false,

No?

**Comment by fengttt** [comment]
Wrong fix.  Wont merge.

**Comment by domingozhang** [comment]
> startwith('foo', '') should be true, startwith('', 'foo') should be false,
> 
> No?

I made a mistake between NULL and blank ''.
May I give this as new rull:
- Blank can be used as parameters and get result
- NULL cannot be used as parameters and get errors

**Pull request closed without merging**
