### PR TITLE
[MatrixCamp] Add aggregate function stddev_pop

### PR DESCRIPTION
**Pull request by jinfuchiang**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1996 

**What this PR does / why we need it:**

Support stddev_pop aggregation function.

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by jinfuchiang** [comment]
**SSB Performance Result**
```sql
MySQL [ssb]> load data infile '../lineorder_flat.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
Query OK, 10272594 rows affected (56.777 sec)
Records: 10272594  Deleted: 0  Skipped: 0  Warnings: 0 WriteTimeout: 0

MySQL [ssb]> select avg(LO_SUPPKEY) from lineorder_flat;
+-----------------+
| avg(LO_SUPPKEY) |
+-----------------+
|        100.5879 |
+-----------------+
1 row in set (0.066 sec)

MySQL [ssb]> select sum(LO_SUPPKEY) from lineorder_flat;
+-----------------+
| sum(LO_SUPPKEY) |
+-----------------+
|      1122339899 |
+-----------------+
1 row in set (0.037 sec)

MySQL [ssb]> select stddev_pop(LO_SUPPKEY) from lineorder_flat;
+------------------------+
| stddev_pop(LO_SUPPKEY) |
+------------------------+
|                57.6749 |
+------------------------+
1 row in set (0.083 sec)
```

**Review by m-schen — CHANGES_REQUESTED** [review]
It seems very similar to variance.
and I'm sorry that I forget to add type support check for tutorial.

You should add it at transformer.go. you can refer to NewBitAnd or my new pull request #2162

**Comment by jinfuchiang** [comment]
Thanks for your review. Indeed, it almost the same with variance and I've added type support check of StdDevPopRing in transformer.go .

**Comment by m-schen** [comment]
i’m not sure if that is any need to refactor the file `bitor_test.go`, I mean, there are not different.
And it's the file which is not related to this function.
Are you doing this because of a conflict? @jinfuchiang

**Comment by jinfuchiang** [comment]
Sorry about that. I don't intend to change other files. It's probably done by the IDE's formatter when I did the last commit. I'll revert these changes in xor* files soon.

**Review by m-schen — APPROVED** [review]
looks good to me.
thank you for your contribution.

**Pull request merged**
