### PR TITLE
[Opt] Reduce PROJECT nodes whose outputs are referenced only once

### PR DESCRIPTION
**Pull request by aunjgr**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

### CODE REVIEW

**Review by ouyuanning — APPROVED** [review]

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify queue

**Review by reusee — APPROVED** [review]

**Comment by aunjgr** [comment]
@mergify refresh

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify queue

**Pull request merged**
