### PR TITLE
fix bug: make sure vector will be free in some case

### PR DESCRIPTION
**Pull request by ouyuanning**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #18364

## What this PR does / why we need it:
fix bug: make sure vector will be free in some case

___

### **PR Type**
Bug fix

___

### **Description**
- Added cleanup logic for buffer (`buf`) in multiple files to prevent memory leaks.
- Updated test cases to include buffer cleanup in teardown.
- Introduced a new field `buf` in the `state` struct to manage batch processing.
- Optimized vector handling in the insert plan by reusing length and ensuring cleanup.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>lock_op.go</strong><dd><code>Ensure proper cleanup of buffer and cached batches</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/lockop/lock_op.go

<li>Added cleanup for <code>lockOp.ctr.buf</code> before reassigning it.<br> <li> Ensured <code>lockOp.ctr.buf</code> is set to nil after cleaning.<br> <li> Updated logic to handle <code>cachedBatches</code> and <code>buf</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18490/files#diff-72fd177a79db26bc21d48eba216ec1690f1377a9a3430a3da15e293d7690b37a">+10/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>order.go</strong><dd><code>Ensure buffer cleanup in merge order processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/mergeorder/order.go

<li>Added cleanup for <code>ctr.buf</code> before reassigning it.<br> <li> Ensured <code>ctr.buf</code> is set to nil after cleaning.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18490/files#diff-03dce6b47ef9452f552f884948d69d94c785eaafbc24f53b849c79bacf2df09e">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>build_insert.go</strong><dd><code>Optimize vector handling and cleanup in insert plan</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/plan/build_insert.go

<li>Added cleanup for <code>vec</code> after marshaling.<br> <li> Stored <code>vec.Length()</code> in a variable for reuse.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18490/files#diff-9d0fd08ed4afb7ebd89ebb05190cd8900fd133473e4ef2e795dd5cea28ddce40">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>lock_op_test.go</strong><dd><code>Add buffer cleanup in test teardown</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/lockop/lock_op_test.go

<li>Added cleanup for <code>arg.ctr.buf</code> in test teardown.<br> <li> Ensured <code>arg.ctr.buf</code> is set to nil after cleaning.<br>

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18490/files#diff-7e6891e992b4a6b127d6467dcf706b643c3ed890683da7c44e9e1d69d8ab9437">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>types.go</strong><dd><code>Add buffer field to state struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/sql/colexec/lockop/types.go

- Introduced `buf` field in `state` struct.

</details>

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/18490/files#diff-ecc813ef8ffb0beae98577e03d670b0c2197427673166dd94aa910b9d0d89e86">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by m-schen — APPROVED** [review]

**Comment by badboynt1** [comment]
should add some unit tests

**Review by badboynt1 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
Why does lock op need to cache batches?

**Comment by ouyuanning** [comment]
> Why does lock op need to cache batches?

目前select for update这类锁，是会等所有batch都过来后再一起上锁。估计是希望上锁的原子性吧。

**Comment by zhangxu19830126** [comment]
> Why does lock op need to cache batches?

see #10102

**Review by fengttt — APPROVED** [review]

**Pull request merged**
