### PR TITLE
Fix now/current_timestamp returns inconsistent value in one sql

### PR DESCRIPTION
**Pull request by mooleetzi**
## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6977 

## What this PR does / why we need it:
1. add proc args during planBuilding
2. make current_timestamp non-volatile to let constFolder track it.

### CODE REVIEW

**Review by fengttt — CHANGES_REQUESTED** [review]
This does not work with parallel remote run.   This must be resolved by query optimizer.

**Comment by mooleetzi** [comment]
> This does not work with parallel remote run. This must be resolved by query optimizer.

emm,

> This does not work with parallel remote run. This must be resolved by query optimizer.

this should work fine with parallel remote run since process containing context, and remote run decode process from []byte.

**Comment by mooleetzi** [comment]
> This does not work with parallel remote run. This must be resolved by query optimizer.

this change should work fine with remote parallel run since `process` contains running context, and remote run decode `process` from encoded `process` from other nodes.

**Comment by mooleetzi** [comment]
Or even this works, also must be resolved by query optimizer?

**Comment by fengttt** [comment]
> 



> > This does not work with parallel remote run. This must be resolved by query optimizer.
> 
> this change should work fine with remote parallel run since `process` contains running context, and remote run decode `process` from encoded `process` from other nodes.

Interesting.  So the current timestamp value is encoded?

**Comment by fengttt** [comment]
> Or even this works, also must be resolved by query optimizer?

It should be.

This value should be substitued, const folded, and optimized for select/join on selectivity and zonemap filtering.   So yes, it has to be part of plan.

**Comment by mooleetzi** [comment]
> > > This does not work with parallel remote run. This must be resolved by query optimizer.
> > 
> > 
> > this change should work fine with remote parallel run since `process` contains running context, and remote run decode `process` from encoded `process` from other nodes.
> 
> Interesting. So the current timestamp value is encoded?

yes

**Comment by mooleetzi** [comment]
> > Or even this works, also must be resolved by query optimizer?
> 
> It should be.
> 
> This value should be substitued, const folded, and optimized for select/join on selectivity and zonemap filtering. So yes, it has to be part of plan.

ok，i see.

**Review by daviszhen — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
can you check that a prepared statement, when executed twice, should have different current timestamp value?   Add this to test please.

**Comment by mooleetzi** [comment]
> can you check that a prepared statement, when executed twice, should have different current timestamp value? Add this to test please.

Ok

**Review by fengttt — APPROVED** [review]

**Pull request merged**
