### PR TITLE
Enable to filter zonemaps by IN predicates

### PR DESCRIPTION
**Pull request by aunjgr**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6822

## What this PR does / why we need it:

### CODE REVIEW

**Review by reusee — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify refresh

**Comment by aunjgr** [comment]
@mergify refresh

**Pull request merged**
