### PR TITLE
common: added the RaceEnabled invariant

### PR DESCRIPTION
**Pull request by lni**
when writing code, you can use this RaceEnabled flag to test whether
your code is running in race testing mode and run more checks without
worrying on possible overheads introduced by such extra checks - as
the race detector makes your program 2-10x slower already.

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [x] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

Added the RaceEnabled invariant. 

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
Why we don't use a config variable?   Wonder what it the reason behind this.

**Comment by lni** [comment]
-race is a build time option. we can certainly provide another runtime config variable indicating that we are in testing mode, but knowing precisely that the program is built with -race is also useful, e.g. in the current version go, we have certain tests that must be skipped when -race is enabled as they creates way too many goroutines (>8100) and the race detector is not happy with that.

**Comment by fengttt** [comment]
> -race is a build time option. we can certainly provide another runtime config variable indicating that we are in testing mode, but knowing precisely that the program is built with -race is also useful, e.g. in the current version go, we have certain tests that must be skipped when -race is enabled as they creates way too many goroutines (>8100) and the race detector is not happy with that.

It seems to me, creating too many goroutines is indeed a problem -- why we need to create that many?

**Comment by lni** [comment]
Those goroutines were created by the 3rd party gossip library when simulating a cluster with 48 Log Service nodes. 

I agree that the RaceEnabled flag proposed in this PR is not super useful.

**Pull request closed without merging**
