### PR TITLE
plsql grammar

### PR DESCRIPTION
**Pull request by chrisxu333**
support declare / case / if-then-elseif-else / loop / while / repeat / iterate / leave

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/matrixone/issues/6623
issue https://github.com/matrixorigin/matrixone/issues/6622
issue https://github.com/matrixorigin/matrixone/issues/6621
issue https://github.com/matrixorigin/matrixone/issues/6620
issue https://github.com/matrixorigin/matrixone/issues/6618
issue https://github.com/matrixorigin/matrixone/issues/6617

## What this PR does / why we need it:

### CODE REVIEW

**Review by sukki37 — CHANGES_REQUESTED** [review]
Add bvt case please

**Comment by chrisxu333** [comment]
> Add bvt case please

Okay will do.

**Comment by fengttt** [comment]
> > Add bvt case please
> 
> Okay but I thought about it. This pr only implements plsql grammar (compound statements with begin...end, and others mentioned in the issues section), and not the `create procedure...` syntax yet. Even with `create procedure...`, the parser won't know if the plsql grammar inside the procedure body is valid until a procedure call, which will be implemented in the next pr. So how do I add bvt cases? I thought ut case focusing on grammar is enough :)

At least you can call it and return an error NYI.   Once you implemented the real thing you can update expected result file.

And for negative test, those should fail due to invalid syntax, you should catch them with parser error.

**Comment by chrisxu333** [comment]
> > > Add bvt case please
> > 
> > 
> > Okay but I thought about it. This pr only implements plsql grammar (compound statements with begin...end, and others mentioned in the issues section), and not the `create procedure...` syntax yet. Even with `create procedure...`, the parser won't know if the plsql grammar inside the procedure body is valid until a procedure call, which will be implemented in the next pr. So how do I add bvt cases? I thought ut case focusing on grammar is enough :)
> 
> At least you can call it and return an error NYI. Once you implemented the real thing you can update expected result file.
> 
> And for negative test, those should fail due to invalid syntax, you should catch them with parser error.

Okay I see now.

**Review by fengttt — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
Why do you need to replicate all sql grammar in .y?

Can you just do something like BEGIN xxx END; then pass xxx to sql.y?

**Comment by chrisxu333** [comment]
> Why do you need to replicate all sql grammar in .y?
> 
> Can you just do something like BEGIN xxx END; then pass xxx to sql.y?

I tried to do this way but then I figured if we have nested BEGIN xxx END, something like
BEGIN
    xxx
    BEGIN
        xxx
    END
END
Then it's hard to determine which parser to use, as the original sql.y only handles single statement.

**Comment by chrisxu333** [comment]
I’ve merged two yacc file into one, just like what MySQL does.

**Review by heni02 — APPROVED** [review]

**Review by iamlinjunhong — APPROVED** [review]

**Review by sukki37 — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by fengttt — APPROVED** [review]

**Pull request merged**
