### PR TITLE
remove unused logic

### PR DESCRIPTION
**Pull request by ouyuanning**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
QueryType was used to mark run statement as  select/update/delete..
then determine whether push row_id to tableDef or not.
for now we push all columns to tableDef.  seems we can drop these codes.

### CODE REVIEW

**Review by daviszhen — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
I am not sure if cloud team want to display ins/del etc query types, and how/where they should get it if we remove these.    Please ask them to reivew this code.

**Comment by ouyuanning** [comment]
> I am not sure if cloud team want to display ins/del etc query types, and how/where they should get it if we remove these. Please ask them to reivew this code.

i guess cloud team want to known  the type of statement like "DDL/DML。。。“  that msg was not removed.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
As discussed with @ouyuanning , the fields in the `system.statement_info` are not affected, so no impact on the cloud services.

**Review by fengttt — APPROVED** [review]

**Pull request merged**
