### PR TITLE
[MatrixCamp] Add Aggregate function bit_and

### PR DESCRIPTION
**Pull request by noneback**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1993

**What this PR does / why we need it:**

Add aggregate function bit_and

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by m-schen — CHANGES_REQUESTED** [review]
Generally, the use of underscores in package names is not recommended in golang,
We suggest you keep your package name and directory the same.
you can change the package name and directory from `bit_and` to `bitand` @noneback 

and other code is good.
And so sorry that we change the tutorial for aggregate function yesterday. you can read it, and we need you to provide a results of simple performance tests while pull request. you can just comment it at pr.

**Comment by noneback** [comment]
Ok. But I will fix it all after your review it all.

**Comment by dengn** [comment]
> > Generally, the use of underscores in package names is not recommended in golang, We suggest you keep your package name and directory the same. you can change the package name and directory from `bit_and` to `bitand` @noneback
> > and other code is good. And so sorry that we change the tutorial for aggregate function yesterday. you can read it, and we need you to provide a results of simple performance tests while pull request. you can just comment it at pr.
> 
> Is there any better way to download the test data rather than baidu-netdisk? Downloading via a browser will be way better than it. @m-schen

If you find baidu-Netdisk too slow, maybe this weiyun disk link for downloading this dataset helps: https://share.weiyun.com/rF3HjsSR code：9u8xz8

**Comment by noneback** [comment]
> > > Generally, the use of underscores in package names is not recommended in golang, We suggest you keep your package name and directory the same. you can change the package name and directory from `bit_and` to `bitand` @noneback
> > > and other code is good. And so sorry that we change the tutorial for aggregate function yesterday. you can read it, and we need you to provide a results of simple performance tests while pull request. you can just comment it at pr.
> > 
> > 
> > Is there any better way to download the test data rather than baidu-netdisk? Downloading via a browser will be way better than it. @m-schen
> 
> If you find baidu-Netdisk too slow, maybe this weiyun disk link for downloading this dataset helps: https://share.weiyun.com/rF3HjsSR code：9u8xz8

I think it is still quite slow. Maybe [aliyundrive](https://www.aliyundrive.com/drive) will be better. Can you upload it again?

**Comment by m-schen** [comment]
> > > > Generally, the use of underscores in package names is not recommended in golang, We suggest you keep your package name and directory the same. you can change the package name and directory from `bit_and` to `bitand` @noneback
> > > > and other code is good. And so sorry that we change the tutorial for aggregate function yesterday. you can read it, and we need you to provide a results of simple performance tests while pull request. you can just comment it at pr.
> > > 
> > > 
> > > Is there any better way to download the test data rather than baidu-netdisk? Downloading via a browser will be way better than it. @m-schen
> > 
> > 
> > If you find baidu-Netdisk too slow, maybe this weiyun disk link for downloading this dataset helps: https://share.weiyun.com/rF3HjsSR code：9u8xz8
> 
> I think it is still quite slow. Maybe [aliyundrive](https://www.aliyundrive.com/drive) will be better. Can you upload it again?

if you are not Mac, you can download the code and generate data yourself.
https://docs.matrixorigin.io/0.3.0/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone/#3-create-tables-in-matrixone
you just need to load one table but not all.
 or you should wait a moment, we need to discuss how to solve this problem.

 Or 我有会员，你需要吗

**Comment by dengn** [comment]
> > > > Generally, the use of underscores in package names is not recommended in golang, We suggest you keep your package name and directory the same. you can change the package name and directory from `bit_and` to `bitand` @noneback
> > > > and other code is good. And so sorry that we change the tutorial for aggregate function yesterday. you can read it, and we need you to provide a results of simple performance tests while pull request. you can just comment it at pr.
> > > 
> > > 
> > > Is there any better way to download the test data rather than baidu-netdisk? Downloading via a browser will be way better than it. @m-schen
> > 
> > 
> > If you find baidu-Netdisk too slow, maybe this weiyun disk link for downloading this dataset helps: https://share.weiyun.com/rF3HjsSR code：9u8xz8
> 
> I think it is still quite slow. Maybe [aliyundrive](https://www.aliyundrive.com/drive) will be better. Can you upload it again?

Aliyundrive doesn't support sharing this kind of file. We will upload it to a Tencent Cloud object storage for faster downloading, the link will be shared later.

**Comment by noneback** [comment]
> 

I will try to generate it. Thx.

**Comment by dengn** [comment]
> > 
> 
> I will try to generate it. Thx.

The fast download link：
https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/lineorder_flat.tar.bz2

**Comment by noneback** [comment]
> > > 
> > 
> > 
> > I will try to generate it. Thx.
> 
> The fast download link： https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/lineorder_flat.tar.bz2

That will be helpful. Thx.

**Comment by noneback** [comment]
I have tested as the tutorial says. Here is the result.
- SQL
 `select bit_and(LO_SUPPKEY) from lineorder_flat;`
- Result
```sql
+---------------------+
| bit_and(LO_SUPPKEY) |
+---------------------+
|                   0 |
+---------------------+
1 row in set (0.379 sec)
```
-  Additional 
The agg SUM result
```sql
MySQL [ssb]> select SUM(LO_SUPPKEY) from lineorder_flat;+-----------------+
| sum(LO_SUPPKEY) |
+-----------------+
|      1033298590 |
+-----------------+
1 row in set (0.313 sec)

```


```

**Review by m-schen — APPROVED** [review]
get it. code is good. thanks.

**Review by yingfeng — CHANGES_REQUESTED** [review]
Do not modify go.mod since matrixcube has been upgraded

**Comment by noneback** [comment]
> Do not modify go.mod since matrixcube has been upgraded

I don't get it. It seems I never modify `go.mod` on the basis of `git diff` and `file change tab` @yingfeng

**Review by yingfeng — APPROVED** [review]
I made a mistake. It's OK

**Pull request merged**
