### PR TITLE
refactor pipeline's clean up method.

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4929 

## What this PR does / why we need it:
1. rewrite pipeline's clean up function, remove the logic will call itself which cause possible dead lock.
2. fix a bug will generate illegal pipeline.

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
what is a container?     Why its clean up code has to be repeated so many times in so many places?

**Review by ouyuanning — APPROVED** [review]

**Comment by m-schen** [comment]
> what is a container? Why its clean up code has to be repeated so many times in so many places?

An argument will not be cleaned up multiple times. The container stores private attributes such as memory allocated in an operator, and the memory should be free after pipeline is over.

**Comment by m-schen** [comment]
@matrix-meow rerun all

**Review by aunjgr — APPROVED** [review]

**Comment by m-schen** [comment]
@matrix-meow rerun failed

**Review by nnsgmsone — APPROVED** [review]

**Pull request merged**
