### PR TITLE
Add timezone support

### PR DESCRIPTION
**Pull request by aunjgr**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [x] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #3703 #3655 #4510 #2488 #3870 #3874

## What this PR does / why we need it:

This commit adds a `*time.Location` instance in both `frontend.Session` and `process.SessionInfo`, to store session level timezone info. We can use `set time_zone=XXX` to modify it. Three different formats are supported, the same as MySQL:

* set time_zone="SYSTEM". It sets timezone to your operating system's value, which is the default.
* set time_zone="+01:00". The timezone string specifies offset to UTC. It comprises a not omittable "+/-" sign, 2-digit hour, a ":" sign, and 2-digit minute. Legal values are between -13:59 and +14:00.
* set time_zone="America/New_York". The timezone string is a legal IANA TZ database name.

TIMESTAMP values are converted from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.)

### CODE REVIEW

**Review by daviszhen — APPROVED** [review]

**Comment by fengttt** [comment]
Hi, can you please write a good commit message?    What did you do, what has changed, where is timezone stored, or session timezone works, etc..    Or link to a doc.

Thank you.

**Review by fengttt — CHANGES_REQUESTED** [review]
Need commit message and better documentation.

**Review by fengttt — COMMENTED** [review]
I am very concerned about the performance of this change.

Can you please add a golang benchmark test, do datetime_add and compare that of using old code without timezone, and new code with timezone.   Let me know how big is the difference.

**Review by ouyuanning — APPROVED** [review]

**Review by aptend — APPROVED** [review]

**Comment by aunjgr** [comment]
> I am very concerned about the performance of this change.
> 
> Can you please add a golang benchmark test, do datetime_add and compare that of using old code without timezone, and new code with timezone. Let me know how big is the difference.

{data,datetime}_{add,sub} has been rewritten. It doesn't involve timezone now.

**Review by aressu1985 — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by fengttt — APPROVED** [review]

**Pull request merged**
