### PR TITLE
scan log tail only when there are subscriptions

### PR DESCRIPTION
**Pull request by cnutshell**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

### CODE REVIEW

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by cnutshell** [comment]
@mergifyio refresh

**Comment by guguducken** [comment]
@mergifyio refresh

**Comment by cnutshell** [comment]
https://github.com/Mergifyio refresh

**Pull request merged**
