### PR TITLE
Add time type

### PR DESCRIPTION
**Pull request by dongdongyang33**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5704

## What this PR does / why we need it:

Add time type 
* support basic time type 
* support cast between time and date/datetime/string
* support time type compare
* support time() func
* support time type for date_add()

### CODE REVIEW

**Review by reusee — APPROVED** [review]

**Comment by dongdongyang33** [comment]
> I will approve.
> 
> However, there is something horribly wrong with our code. Adding a new type, should touch about 8 files, not 86.

yes it scared me ...
but I implement some time-related functions like cast/time() in addition
so this PR touches a little more files than what only support time type need

**Review by daviszhen — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Review by aunjgr — CHANGES_REQUESTED** [review]
Seems that you forgot to include the modified proto files

**Comment by yingfeng** [comment]
One failure in the `e2e` ci pipeline:

```
2022-10-25 12:53:25 ERROR Executor:125 - [EXPECT RESULT]:
not supported: function or operator 'time'
2022-10-25 12:53:25 ERROR Executor:126 - [ACTUAL RESULT]:
adddate(time(00:00:00), interval(1, hour))
```

You need to guarantee bvt passed in both `tae-logservice` and `cn-tae-dn-tae`

**Comment by dongdongyang33** [comment]
> Seems that you forgot to include the modified proto files

my fault. create a new PR #5964 for it

**Pull request merged**
