### PR TITLE
fix issue 15543: query return but part of pipelines still running.

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #15543

## What this PR does / why we need it:
1. fix a bug cause query return with part of pipelines still running for a moment.
2. fix the order of  mpool destory process.
3. fix a hash-build bug of missing sending auxdata batch when data was empty.
4. fix a context mismatched bug of receiver and its local sender.

### CODE REVIEW

**Comment by matrix-meow** [comment]
@m-schen Thanks for your contributions!

### Pull Request Review:

#### Title:
The title of the pull request is clear and concise, indicating that it fixes issue 15543 related to query return with part of pipelines still running.

#### Body:
The body of the pull request provides essential information about the type of PR (BUG), the specific issue it fixes (issue #15543), and the reason for the PR, which is to address a bug causing pipelines to continue running after a query returns.

#### Changes:
1. In `mpool.go`:
   - The `destroy` function now returns a boolean indicating success.
   - Improved handling of double destroy scenarios and when the pool is still in use.
   - The `DeleteMPool` function now checks the return value of `mp.destroy()` before deleting the pool.
   
2. In `scope.go`:
   - The `notifyAndReceiveFromRemote` function now takes a `sync.WaitGroup` parameter to ensure proper synchronization.
   - Added error handling and synchronization mechanisms to handle notifications to remote nodes.
   - Improved error handling and closing of channels in the `notifyAndReceiveFromRemote` function.

3. In `scopeRemoteRun.go` and `scopeRemoteRunTypes.go`:
   - Added `bat.Clean(mp)` to properly clean up resources after decoding a batch.

#### Suggestions for Improvement:
1. **Error Handling in `mpool.go`**:
   - Consider logging errors or returning them instead of silently failing in the `destroy` function. This can help in diagnosing issues during pool destruction.

2. **Synchronization in `scope.go`**:
   - Ensure proper synchronization by reviewing the usage of `sync.WaitGroup` and deferred `wg.Wait()` calls. Make sure all goroutines are properly waited for before proceeding.

3. **Error Handling and Resource Cleanup**:
   - Ensure consistent error handling and resource cleanup across functions. Verify that resources are properly released in case of

**Comment by m-schen** [comment]
先别合，貌似合到1.1的相同pr会导致tpch和ssb卡卡死

**Comment by m-schen** [comment]
已修复，在多节点上测试tpch通过，正在测试ssb用例。

**Comment by m-schen** [comment]
咋回事啊 sad

**Pull request merged**
