### PR TITLE
Add statistics logic for logtail server

### PR DESCRIPTION
**Pull request by cnutshell**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6894

## What this PR does / why we need it:
Collect and log logtail server running status.

### CODE REVIEW

**Review by fengttt — CHANGES_REQUESTED** [review]
why this is not reusing the metrics of Hang Feng?

**Comment by cnutshell** [comment]
> why this is not reusing the metrics of Hang Feng?

@fengttt Now our implementation would dump metric data to a table every 15 seconds,  one table per metric.
This PR mainly collects logtail server statistics, and log them by interval. It has different purpose compared with metrics.

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by fengttt** [comment]
> > why this is not reusing the metrics of Hang Feng?
> 
> @fengttt Now our implementation would dump metric data to a table every 15 seconds, one table per metric. This PR mainly collects logtail server statistics, and log them by interval. It has different purpose compared with metrics.

What is the difference?   Other than you have an interval instead of 15 seconds.

**Comment by cnutshell** [comment]
> > > why this is not reusing the metrics of Hang Feng?
> > 
> > 
> > @fengttt Now our implementation would dump metric data to a table every 15 seconds, one table per metric. This PR mainly collects logtail server statistics, and log them by interval. It has different purpose compared with metrics.
> 
> What is the difference? Other than you have an interval instead of 15 seconds.

What I need is to record logtail server running statistics in log, but now we couldn't convert metrics into log, as far as I know.
Besides, log/metrics/trace are different approach for service observation. They are complementary. Maybe there should be another PR with metrics mainly.

**Pull request closed without merging**
