### PR TITLE
[Refactor]: FS Pool refactor

### PR DESCRIPTION
**Pull request by arjunsk**
## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [X] Code Refactoring

## Which issue(s) this PR fixes:

issue # https://github.com/matrixorigin/MO-Cloud/issues/669

## What this PR does / why we need it:

- Replace the current `closure with no arguments`, with `closure with the resource as an argument`.
- pre-allocating `pool.pool` slice instead of appending items one by one.
- Removing defer inside the `for loop` to avoid possible [memory leaks](https://stackoverflow.com/questions/45617758/proper-way-to-release-resources-with-defer-in-a-loop/45617791#45617791).

### CODE REVIEW

**Comment by arjunsk** [comment]
Hi @fengttt , I made the requested changes for the file service Pool in this PR. But since the root cause for this [issue](https://github.com/matrixorigin/MO-Cloud/issues/669) is not related to file_service Pool, I am holding this PR.

I will be working on debugging the location of `unsafe.Pointer` causing this issue https://github.com/matrixorigin/MO-Cloud/issues/669

**Review by fengttt — COMMENTED** [review]
I still cannot understand ...

Well, I guess you can skip this one and I will later try a simple stupid version.

**Comment by reusee** [comment]
I bet there is no easy way to beat the pool :)
```
| go test -run zzz -bench Pool -benchmem -count 5
goos: darwin
goarch: arm64
pkg: github.com/matrixorigin/matrixone/pkg/fileservice
BenchmarkBytesPool-10            	100000000	        11.68 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-10            	100000000	        11.71 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-10            	100000000	        11.69 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-10            	100000000	        11.96 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-10            	100000000	        11.77 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-10    	130386654	         9.164 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-10    	130903932	         9.259 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-10    	124547924	         9.238 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-10    	130432472	         9.230 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-10    	133843027	         9.029 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/matrixorigin/matrixone/pkg/fileservice	16.895s
```

**Comment by reusee** [comment]
And it scales much better on x86 machines in parallel workload
```
| go test -run zzz -bench Pool -count 5 -benchmem
goos: linux
goarch: amd64
pkg: github.com/matrixorigin/matrixone/pkg/fileservice
cpu: AMD Ryzen 7 5800U with Radeon Graphics
BenchmarkBytesPool-16            	100000000	        10.97 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-16            	98735437	        11.01 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-16            	132180738	        11.45 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-16            	100000000	        11.87 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesPool-16            	100000000	        11.32 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-16    	534080730	         2.504 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-16    	478755644	         2.355 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-16    	444883354	         2.694 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-16    	436514906	         2.757 ns/op	       0 B/op	       0 allocs/op
BenchmarkParallelBytesPool-16    	454462072	         2.673 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/matrixorigin/matrixone/pkg/fileservice	14.396s
```

**Pull request closed without merging**
