### PR TITLE
modify read simdcsv flow

### PR DESCRIPTION
**Pull request by jianwan0214**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

### CODE REVIEW

**Comment by fengttt** [comment]
You should make rpc message 100M and load tpch 10G.

**Comment by yingfeng** [comment]
why 0.6 is ok but 0.8 will fail? there must have some problems elsewhere

**Review by fengttt — COMMENTED** [review]
Can we keep the ONE_BATCH_READ_ROW?   Give it a better name maybe.

Let's get this in to make load run.    Actually, I would set the fudge factor from 0.6 to a smaller number.  0.2 or 0.25?

However, this is not the right fix.  The right fix should be open a batch.  read a small number of lines, append to the batch and count bytes in the batch.   Once this count reached 0.8 (or any fudge factor) of batch size, output.    

RPC message size is all about the size of batch, not the one in csv file.    Once char 'a', will be using 24 bytes in vector/batch, so your current accounting is way off.

Or should we consider compress vector?

**Review by fengttt — APPROVED** [review]
Please clean up.   Approve to speed up the process.

**Review by yingfeng — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Pull request merged**
