### PR TITLE
Update Decimal Encoding/Decoding, Add Decimal Constant, Update Parsing Function From String to Decimal

### PR DESCRIPTION
**Pull request by zengyan1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10002 

## What this PR does / why we need it:
Update Decimal Encoding and Add Decimal Constant
Change names of function parsing string to decimal

### CODE REVIEW

**Comment by matrix-meow** [comment]
@zengyan1 Thanks for your contributions!

**Here are review comments for file pkg/container/types/decimal.go:**
The pull request updates Decimal Encoding and adds Decimal Constant. However, there are a few issues that need addressing:

1. The pull request title is not descriptive enough. It should provide more information about what the pull request does and why it is necessary.
2. The pull request body is incomplete. It should provide more details about the changes made and why they are necessary.
3. The changes made in the pull request are not optimized. The addition of new constants and their corresponding byte arrays could have been done in a more efficient way.
4. The naming of the new functions added in the pull request is not consistent with the naming convention used in the rest of the codebase. They should be renamed to follow the convention used in the codebase.

**Here are review comments for file pkg/container/types/decimal_test.go:**
The pull request title is clear and concise, indicating that it updates decimal encoding and adds a decimal constant. However, the body of the pull request is not helpful as it only contains a checklist of PR types and an issue number. It would be better if the body provided more context on what the changes are and why they are necessary.

The changes made in the pull request modify the `TestDecimal128OverDiv` function in the `decimal_test.go` file. Specifically, it updates the `Parse128` function to `ParseDecimal128FromString`. This change is necessary because the `Parse128` function is deprecated and has been replaced by `ParseDecimal128FromString`.

One issue with the changes is that the `panic` statement in the `TestDecimal128OverDiv` function is not helpful for debugging. It would be better to use the `t.Errorf` function to provide a more informative error message.

Another issue is that the pull request only addresses one instance of the deprecated `Parse128` function. It would be better to search the entire codebase for all instances of the deprecated function and update them to the new function.

Overall, the changes made in the pull request are necessary and should be merged. However, the pull request could be improved by providing more context in the body and addressing all instances of the deprecated function.

**Here are review comments for file pkg/container/types/encoding.go:**
The title of the pull request is clear and concise. However, the body of the pull request is not helpful as it only contains a checklist and a brief description of the changes. It would be better if the body provided more context on why these changes are necessary and how they will improve the codebase.

In terms of the changes made, the `EncodeDecimal64` and `EncodeDecimal128` functions have been updated to use a safer method of encoding. However, the changes made to these functions are not optimal as they create unnecessary memory allocations. Instead of using `append` to build the byte slice, the functions should use a fixed-size byte array and copy the bytes into it.

Additionally, the `DecodeDecimal64` and `DecodeDecimal128` functions have been updated to use a safer method of decoding. However, the changes made to these functions are not optimal as they use a loop to swap bytes. A more efficient method would be to use the `binary` package to swap the bytes.

Finally, the pull request does not include any tests to ensure that the updated functions work correctly. It would be helpful to include tests to verify that the encoding and decoding functions work as expected.

**Here are review comments for file pkg/container/types/time_test.go:**
The title of the pull request is clear and concise. However, the body of the pull request is not helpful as it does not provide any additional information about the changes made. It would be better if the body of the pull request provided more context about the changes and why they were made.

The changes made in the pull request are focused on updating the Decimal Encoding and adding a Decimal Constant. Specifically, the changes are made to the `time_test.go` file in the `pkg/container/types/` directory. The changes involve updating the `Parse128` function to `ParseDecimal128FromString` function. 

One problem with the changes is that the `println` statement in the `TestTime_ParseTimeFromDecimal128` function should be removed as it is not necessary. Additionally, it would be better to use `t.Log` instead of `println` to log the decimal value. 

Another suggestion would be to add comments to the code to explain the changes made and why they were necessary. This would make it easier for other developers to understand the code and make future changes if necessary. 

Finally, it would be helpful to include test cases to ensure that the new `ParseDecimal128FromString` function works as expected. This would help catch any potential bugs or issues with the new code.

**Here are review comments for file pkg/frontend/util_test.go:**
The pull request updates the decimal encoding and adds a decimal constant. However, the body of the pull request is incomplete and does not provide enough information about the changes made. Additionally, the changes made in the file `pkg/frontend/util_test.go` seem to be unrelated to the title and body of the pull request. 

Suggestions:
- The body of the pull request should be updated to provide more information about the changes made and why they are necessary.
- The changes made in the file `pkg/frontend/util_test.go` should be moved to a separate pull request or explained in the body of the current pull request if they are related to the decimal encoding and constant changes.
- The pull request should be reviewed to ensure that all changes are necessary and optimized.

**Here are review comments for file pkg/sql/plan/base_binder.go:**
The pull request updates the Decimal Encoding and adds a Decimal Constant. The changes made in the pull request are in the file `pkg/sql/plan/base_binder.go`. The `Parse128` function is replaced with `ParseDecimal128FromString` function. 

However, the pull request lacks a detailed explanation of the changes made and why they are necessary. The pull request does not explain why the `Parse128` function is being replaced with `ParseDecimal128FromString`. It would be helpful to provide more information on the changes made and the benefits of using `ParseDecimal128FromString`.

Additionally, the pull request does not provide any information on how the changes were tested. It is important to include information on how the changes were tested to ensure that they do not cause any issues or regressions. 

To optimize the changes made in the pull request, the author could provide more information on the benefits of using `ParseDecimal128FromString` and how it improves the codebase. The author could also include information on how the changes were tested to ensure that they do not cause any issues or regressions.

**Here are review comments for file pkg/sql/plan/function/func_unary_test.go:**
The pull request updates the decimal encoding and adds a decimal constant. The changes made in the pull request are in the file `pkg/sql/plan/function/func_unary_test.go`. The changes include replacing the `types.Parse128` function with `types.ParseDecimal128FromString` function in some test cases. 

There are no issues with the title and body of the pull request. However, there are some issues with the changes made in the pull request:

1. The changes made in the pull request are not optimized. The changes only replace the `types.Parse128` function with `types.ParseDecimal128FromString` function in some test cases. The changes could be optimized by replacing all occurrences of `types.Parse128` function with `types.ParseDecimal128FromString` function in the entire file.

2. There are some commented lines of code in the file that are not needed. These lines of code should be removed.

To optimize the changes made in the pull request, all occurrences of `types.Parse128` function in the entire file should be replaced with `types.ParseDecimal128FromString` function. Additionally, the commented lines of code in the file should be removed.

**Here are review comments for file pkg/sql/plan/make.go:**
The pull request updates the decimal encoding and adds a decimal constant. The changes are made to the `make.go` file in the `pkg/sql/plan` directory. The changes involve updating the `types.Parse128` function to `types.ParseDecimal128FromString` to handle decimal encoding and adding a decimal constant. 

However, the pull request lacks a detailed explanation of why these changes are necessary. It would be helpful to have more information on the issues that the changes aim to solve. Additionally, the pull request does not provide any tests to ensure that the changes do not break existing functionality. 

To optimize the changes, the pull request could include a more detailed explanation of the changes and their impact on the codebase. Additionally, the pull request could include tests to ensure that the changes do not break existing functionality.

**Here are review comments for file pkg/testutil/util_make.go:**
The pull request title and body are clear and concise, indicating that the changes aim to update the decimal encoding and add a decimal constant. However, the body of the pull request does not provide enough context about the changes made. It would be helpful to include more details about the changes, such as why the decimal encoding needed to be updated and what the decimal constant is used for.

In terms of the code changes, the pull request modifies a single file, `pkg/testutil/util_make.go`. The changes made in this file update the `MakeScalarDecimal128ByFloat64` function to use the `ParseDecimal128FromString` function instead of `Parse128` to parse decimal values. This change is necessary because the `Parse128` function has been deprecated and replaced with `ParseDecimal128FromString`.

One suggestion for improvement would be to include a brief explanation of the deprecation of `Parse128` and the benefits of using `ParseDecimal128FromString` instead. Additionally, it would be helpful to include some test cases to ensure that the updated function works as expected.

Overall, the changes made in this pull request are straightforward and appear to be necessary. However, providing more context and test cases would help ensure that the changes are thoroughly reviewed and tested.

**Review by fengttt — CHANGES_REQUESTED** [review]
Is this the right place?    All we want is the encoding/decoding in tuple to preserve orders.   It has nothing to do with types/encoding.

**Comment by zengyan1** [comment]
> Is this the right place? All we want is the encoding/decoding in tuple to preserve orders. It has nothing to do with types/encoding.

I put it into decimal.go, someone need a function to encode/decode decimal , tuple uses a packer

**Review by daviszhen — APPROVED** [review]

**Review by m-schen — APPROVED** [review]

**Review by qingxinhome — APPROVED** [review]

**Comment by fengttt** [comment]
> > Is this the right place? All we want is the encoding/decoding in tuple to preserve orders. It has nothing to do with types/encoding.
> 
> I put it into decimal.go, someone need a function to encode/decode decimal , tuple uses a packer

This is not right -- encoding of decimal64/128 should not be any more than copy8/16 bytes.   The code is pure overhead.    Only tuple need to encode it to order-preserving-by-memcmp format.

Get rid of the types.encoding, the code should just runs OK.    Or it is a bug.

**Review by aunjgr — APPROVED** [review]

**Review by m-schen — APPROVED** [review]

**Comment by fengttt** [comment]
> > > > Is this the right place? All we want is the encoding/decoding in tuple to preserve orders. It has nothing to do with types/encoding.
> > > 
> > > 
> > > I put it into decimal.go, someone need a function to encode/decode decimal , tuple uses a packer
> > 
> > 
> > This is not right -- encoding of decimal64/128 should not be any more than copy8/16 bytes. The code is pure overhead. Only tuple need to encode it to order-preserving-by-memcmp format.
> > Get rid of the types.encoding, the code should just runs OK. Or it is a bug.
> 
> 锁要用bytes.Compare来比较主键大小，也是需要order-preserving

According to @zhangxu19830126 , already handled.     Please remove this section of code.   If this really needed, we should add an encodeWithOrder method.    

Also please see #10081

**Review by fengttt — CHANGES_REQUESTED** [review]
please address our discussion in the decimal encoding code.

**Pull request closed without merging**
