### PR TITLE
optimize write s3 by using UnionBatch

### PR DESCRIPTION
**Pull request by JackTan25**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [x] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7240 #7870

## What this PR does / why we need it:
In 7870 and 7240, load the partsupp table is slow, that's very strange, but  for other tables, that's 
faster than 0.6, so I need to issue the problem and then optimize the write s3 performance.

### CODE REVIEW

**Comment by nnsgmsone** [comment]
Please comment on what this pr does @JackTan25

**Review by nnsgmsone — APPROVED** [review]

**Comment by nnsgmsone** [comment]
The logic should be to reduce the number of alloc

**Comment by JackTan25** [comment]
@matrix-meow rerun failed

**Comment by JackTan25** [comment]
@matrix-meow rerun failed

**Pull request closed without merging**
