### PR TITLE
logservice: use reverse proxy for service discovery

### PR DESCRIPTION
**Pull request by lni**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

Log Service's ClientConfig and HAKeeper's HAKeeperClientConfig both have an optional DiscoveryAddress field which is the service address of a reverse proxy provided by k8s. The reverse proxy redirects requests to a random Log Service node and we use this mechanism to query Log Shard info from such random node. As such shard info is broadcasted to all Log Service nodes via gossip over time, this allows eventual discovery of the details of the interested Log Service shard.  

This feature is required as replicas of a Log Shard can migrate to a completely different set of nodes over time, a pre determined & fixed address list alone won't be enough to allow clients to connect to the interested Log Shard.

### CODE REVIEW

**Comment by lni** [comment]
This PR touched auto-generated pb.go files from multiple owners when none of their .proto files were changed. 

Probably because we are all using different version of pb on our dev machines?

**Review by aptend — APPROVED** [review]

**Comment by lni** [comment]
OK, thanks to the help from @zhangxu19830126 and @nnsgmsone, it was my installation of gogoprotobuf causing the problem. upgraded to v1.3.2 and it is much better now.

**Review by fengttt — COMMENTED** [review]
I am OK with the change, but can you explain why we need this in commit message?   I think I need a better overview and motivation of this change.

**Comment by fengttt** [comment]
> I am OK with the change, but can you explain why we need this in commit message? I think I need a better overview and motivation of this change.

Never mind.   Now we don't use commit message, but use PR message.

**Review by fengttt — APPROVED** [review]

**Comment by lni** [comment]
> > I am OK with the change, but can you explain why we need this in commit message? I think I need a better overview and motivation of this change.
> 
> Never mind. Now we don't use commit message, but use PR message.

Yes, the "What this PR does / why we need it" section of the PR message will become the body of the commit message once merged.

**Review by nnsgmsone — APPROVED** [review]

**Comment by guguducken** [comment]
@mergifyio refresh

**Comment by lni** [comment]
@mergifyio refresh

**Pull request merged**
