### PR TITLE
refactor the pipeline's remote run

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:
https://github.com/matrixorigin/MO-Cloud/issues/2788
https://github.com/matrixorigin/MO-Cloud/issues/3281

## What this PR does / why we need it:

1.Refactor the remote execution function and add more logging for it. If the data-receiver prematurely terminates the query, it will always notify the sender to cease operations before closing the connection.

2.Remove numerous fields from the pipeline's Message.

3.Add comments to some obscure code sections.
___

### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Refactored the remote run server-side handling by adding `CnServerMessageHandler` and `handlePipelineMessage`.
- Implemented client-side functionality for remote run, including message sending and receiving.
- Updated scope handling to use the new message sender and improved error handling.
- Added tracking for running pipelines in `colexec` and initialized it in the server.
- Updated pipeline proto definitions by adding a new method and removing unused fields.
- Added comments and improved error logging in the server.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>remoterunServer.go</strong><dd><code>Refactor and enhance remote run server-side handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/sql/compile/remoterunServer.go

<li>Added <code>CnServerMessageHandler</code> to handle messages from the cn-client.<br> <li> Implemented <code>handlePipelineMessage</code> to process different types of <br>pipeline messages.<br> <li> Removed <code>messageSenderOnClient</code> and related functions.<br> <li> Added error handling and logging improvements.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-d73b7f89321871c12e2595b1b3fd175f2f3a8a3cff9e153f69c02f23cd650d6f">+174/-202</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>remoterunClient.go</strong><dd><code>Implement remote run client-side functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/sql/compile/remoterunClient.go

<li>Added <code>remoteRun</code> function to send scope to remote nodes and receive <br>results.<br> <li> Implemented <code>messageSenderOnClient</code> to handle message sending and <br>receiving.<br> <li> Added functions for encoding and decoding messages.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-e027434536257765c13ae824cfa8138e56c758db4365d2706ae5889ed1db14e2">+406/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>scope.go</strong><dd><code>Update scope handling to use new message sender</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/sql/compile/scope.go

<li>Replaced <code>morpc.Stream</code> with <code>messageSenderOnClient</code> for sending messages.<br> <li> Updated <code>sendNotifyMessage</code> to use the new client message sender.<br> <li> Improved error handling and logging.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-1a84d311b058e390f8c70e84f5e0c59dbd42736a85d022e2a283d926d43f5bd6">+29/-80</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>types.go</strong><dd><code>Add tracking for running pipelines in colexec</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/sql/colexec/types.go

<li>Added <code>RunningPipelineMapForRemoteNode</code> to track running pipelines.<br> <li> Implemented functions to record, cancel, and remove running pipelines.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-a63bd733f31e4baece44c165cb387a424e53a74a2c9fed3d04d3b9c77cb08f37">+40/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>server.go</strong><dd><code>Initialize running pipeline tracking in server</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/sql/colexec/server.go

- Initialized `RunningPipelineMapForRemoteNode` in `NewServer`.

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-ce804a3d5013e5c854f05ab524576d3b22c2a2eb2be113c999bd5464b4660722">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pipeline.proto</strong><dd><code>Update pipeline proto definitions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
proto/pipeline.proto

<li>Added <code>StopSending</code> method to <code>Method</code> enum.<br> <li> Removed unused fields from <code>Message</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-e9c91df4d87ffef63693440b86da7db2a8349c550c6c789bcc8e71f3e81309a6">+2/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Miscellaneous
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>remoterun_test.go</strong><dd><code>Clean up imports in remoterun tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/sql/compile/remoterun_test.go

- Removed unused imports.

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-87cb5b928ccaeb113e1cda3c8fe7fe6b65a71d470bf5f32c8da9c8de302456cf">+1/-77</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>server.go</strong><dd><code>Add comments and improve error logging in server</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pkg/cnservice/server.go

<li>Added comments to explain message handling logic.<br> <li> Improved error logging in <code>handleRequest</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/matrixorigin/matrixone/pull/16923/files#diff-3a5012a0926d6830df057d5994c8cc87d91d484802c6b8a60a6d417110c09854">+15/-6</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by m-schen** [comment]
先跑跑看。
如果能过的话，下周一再让QA帮忙跑下回归。

后续将该pr 合并到main分支可能需要一定时间，改动有点大。

**Review by daviszhen — APPROVED** [review]

**Comment by m-schen** [comment]
先加个not-merge标签，等我自测完了再合并。

**Review by reusee — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by badboynt1 — APPROVED** [review]

**Comment by m-schen** [comment]
ssb job通过：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9544757100

tpch job通过：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9544081373/job/26301973539

**Comment by m-schen** [comment]
等一下下

**Review by ouyuanning — APPROVED** [review]

**Review by sukki37 — APPROVED** [review]

**Pull request merged**
