### PR TITLE
Refactor insert node

### PR DESCRIPTION
**Pull request by triump2020**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #7158  #6824 #6969 

## What this PR does / why we need it:
1. Refactor insertNode to support adding block on S3.
2.  Add codes for supporting CN 's direct s3 `insert `  . These codes will not be executed for now.
3. Added some code comments.

### CODE REVIEW

**Comment by triump2020** [comment]
Doc : https://github.com/matrixorigin/docs/blob/main/design/Precommit-Wite-S3.md

**Comment by triump2020** [comment]
@matrix-meow rerun failed.

**Comment by JackTan25** [comment]
@matrix-meow rerun failed

**Comment by triump2020** [comment]
@matrix-meow  rerun failed

**Review by jiangxinmeng1 — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Review by nnsgmsone — APPROVED** [review]

**Pull request merged**
