### PR TITLE
Add analyze info and memory limit for operator

### PR DESCRIPTION
**Pull request by nnsgmsone**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3921

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
Are you moving code from colexec2 to colexec?   That means you will retire colexec2 instead of colexec?    Talking about confusion ...

You need to update people on memory related stuff.

**Review by fengttt — COMMENTED** [review]
And we don't really have any "operator" limit, all we have is a proc limit, is this correct?

And what are BatchRows, BatchSize, and ReaderSize?   Are you expecting people to set it/change it at all?

Finally, which Lim, and Size/BatchRows etc has to be public?

**Comment by nnsgmsone** [comment]
> Are you moving code from colexec2 to colexec? That means you will retire colexec2 instead of colexec? Talking about confusion ...
> 
> You need to update people on memory related stuff.

Well, colexec2 is a temporary directory. That I use to correct some code.

**Comment by nnsgmsone** [comment]
> And we don't really have any "operator" limit, all we have is a proc limit, is this correct?
> 
> And what are BatchRows, BatchSize, and ReaderSize? Are you expecting people to set it/change it at all?
> 
> Finally, which Lim, and Size/BatchRows etc has to be public?



> And we don't really have any "operator" limit, all we have is a proc limit, is this correct?
> 
> And what are BatchRows, BatchSize, and ReaderSize? Are you expecting people to set it/change it at all?
> 
> Finally, which Lim, and Size/BatchRows etc has to be public?

There are restrictions on operators, and some variables do need to be hidden. I will write documentation on their specific meaning.

**Review by yingfeng — APPROVED** [review]

**Pull request merged**
