### PR TITLE
[opt] : when composite primary key has a column that is auto-incr, and this column does not specify a value, no dup check is needed(1.1-dev)

### PR DESCRIPTION
**Pull request by jensenojs**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue # https://github.com/matrixorigin/MO-Cloud/issues/3038 

## What this PR does / why we need it:

to opt sysbench insert performance

### CODE REVIEW

**Comment by jensenojs** [comment]
本地用ubuntu做了一个测试, 测试的是sysbench_insert, table_size 100000, threads 100, 有自增列, 有次级索引的对比情况.

1.1-dev :

Pasted Graphic 1

this pr : 
Pasted Graphic

**Comment by jensenojs** [comment]
补充一个优化case, 对于复合主键, 并且其中一列是auto increment的类型, 并且该列没有值的情况, 也可以不用做去重检测.

企业微信截图_d6e52dbb-cc75-477a-adb4-321c524e2ad3

**Review by badboynt1 — APPROVED** [review]

**Comment by badboynt1** [comment]
这个pr的逻辑错误。 自增列主键不能不做去重，而是应该通过runtime filter来做去重。

**Review by badboynt1 — CHANGES_REQUESTED** [review]
这个pr的逻辑错误。 自增列主键不能不做去重，而是应该通过runtime filter来做去重。

**Review by fengttt — CHANGES_REQUESTED** [review]
This is simply not true.   What if user supplied a key, and it is inserted, but later auto increment picked up this key again?

**Comment by fengttt** [comment]
> 这个pr的逻辑错误。 自增列主键不能不做去重，而是应该通过runtime filter来做去重。

Or, we enforce this by fail all inserts that users supply a value.

Must let user bulkhead the table.   Then turn on a config/option etc, saying from this time on, all ids are auto gen.   Fail any user inserts
with supplied ID.

**Pull request closed without merging**
