### PR TITLE
[opt] apply indices for IN filters

### PR DESCRIPTION
**Pull request by aunjgr**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #12517 #12934

## What this PR does / why we need it:
To accelerate particular queries in sysbench

### CODE REVIEW

**Comment by aunjgr** [comment]
@mergify refresh

**Review by daviszhen — APPROVED** [review]

**Review by XuPeng-SH — APPROVED** [review]

**Review by badboynt1 — APPROVED** [review]

**Review by qingxinhome — APPROVED** [review]

**Review by m-schen — APPROVED** [review]

**Review by iamlinjunhong — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Comment by aunjgr** [comment]
@mergify queue

**Comment by aunjgr** [comment]
@mergify refresh

**Comment by aunjgr** [comment]
@mergify queue

**Pull request merged**
