### PR TITLE
fix show columns for cluster table

### PR DESCRIPTION
**Pull request by YANGGMM**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8396 

## What this PR does / why we need it:
fix show columns for cluster table

### CODE REVIEW

**Review by heni02 — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Comment by guguducken** [comment]
@mergifyio refresh

**Comment by YANGGMM** [comment]
@mergifyio refresh

**Comment by YANGGMM** [comment]
@mergifyio refresh

**Review by aunjgr — APPROVED** [review]

**Comment by YANGGMM** [comment]
@mergify refresh

**Comment by YANGGMM** [comment]
@mergify refresh

**Pull request merged**
