### PR TITLE
feature: Decimal max min average functions

### PR DESCRIPTION
**Pull request by broccoliSpicy**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2302 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by m-schen — APPROVED** [review]
looks good to me.

**Review by fengttt — COMMENTED** [review]
What is exact a Ring?   Can these Ring code get merged?   I am baffled that, Min and Max, aren't they should be just 1 line diff (< vs >)?

**Comment by broccoliSpicy** [comment]
> What is exact a Ring? Can these Ring code get merged? I am baffled that, Min and Max, aren't they should be just 1 line diff (< vs >)?

I am just following the codebase convention of other min/max functions

**Comment by nnsgmsone** [comment]
> What is exact a Ring? Can these Ring code get merged? I am baffled that, Min and Max, aren't they should be just 1 line diff (< vs >)?
The logic of the aggregation function retains the semantics of ring, and we will refactor this part of the logic after 0.5. For the time being, I've reused the original ring logic in the interests of progress.

**Pull request merged**
