### PR TITLE
[feat] : add database config unique_check_on_autoincr

### PR DESCRIPTION
**Pull request by jensenojs**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #15809

## What this PR does / why we need it:

- 拆分pr, 这个pr只添加了配置, 没有开始使用, 后面一并补充相应的测试用例
- 重构了部份的`DataBase Config`, 但是有很多后续工作, 用#16070 跟踪
- 在Session中添加了一个字段用来缓存配置信息, 以便plan/compile的阶段能够不通过后台SQL调用的方式来获取配置

### CODE REVIEW

**Comment by matrix-meow** [comment]
@jensenojs Thanks for your contributions!

**Here are review comments for file pkg/frontend/authenticate.go:**
### Pull Request Review:

#### Title and Body:
The title and body of the pull request provide a brief overview of the changes being made, indicating that the PR is an improvement related to database configuration. The body mentions that this PR only adds configuration without immediate usage, and that corresponding test cases will be added later. It also references the related issue number.

#### Changes in pkg/frontend/authenticate.go:
1. **Security Issue - Potential SQL Injection:**
   - In the `insertRecordToMoMysqlCompatibilityMode` function, the SQL query is constructed using `fmt.Sprintf` without any sanitization or parameterization. This can lead to SQL injection vulnerabilities. It's crucial to use parameterized queries to prevent this security risk. Suggest using prepared statements or query parameters to safely insert variables into the SQL query.

2. **Error Handling Improvement:**
   - In the `GetUniqueCheckOnAutoIncr` function, the error handling can be enhanced. Instead of returning the default configuration immediately after an error occurs, consider returning a more informative error message to help with debugging and troubleshooting.

3. **Code Optimization:**
   - In the `doAlterDatabaseConfig` function, the switch statement can be optimized by moving the common error handling code outside the switch block to avoid repetition. This can make the code more concise and easier to maintain.

4. **Consistency Improvement:**
   - In the `insertRecordToMoMysqlCompatibilityMode` function, the variable names `variableName1` and `variableValue1` can be made more descriptive to improve code readability and maintainability. Consider using meaningful names that reflect the purpose of the variables.

5. **Error Handling Enhancement:**
   - In the `insertRecordToMoMysqlCompatibilityMode` function, after executing the first SQL query, there is a missing error check for the second SQL query execution. Ensure that error handling is consistent and thorough throughout the function.

6. **Logic Improvement:**
   - In the `GetUniqueCheckOnAutoIncr` function, the default configuration is always returned if an error occurs during SQL execution. Consider handling errors more gracefully by distinguishing between different types of errors and providing appropriate responses.

7. **Error Handling Consistency:**
   - In the `GetUniqueCheckOnAutoIncr` function, the defer statement for closing the background executor should be placed after the error check for better consistency and to ensure proper resource cleanup.

8. **Error Handling Best Practice:**
   - In the `GetUniqueCheckOnAutoIncr` function, consider using a more specific error type instead of a generic error to provide better context in case of failures.

9. **Code Readability Enhancement:**
   - In the `doAlterDatabaseConfig` function, the comment for `step2` can be updated to reflect the actual operation being performed, which is updating the database configuration, to improve code clarity.

10. **Security Enhancement:**
    - Ensure that the `panic` statement in the `doAlterDatabaseConfig` function is handled more gracefully to avoid abrupt termination of the program. Consider using proper error handling mechanisms instead of panicking.

### Overall, the pull request introduces some improvements related to database configuration, but there are critical security issues and areas for enhancement that need to be addressed before merging the changes. By addressing these issues and optimizing the code, the quality and security of the codebase can be significantly improved.

**Here are review comments for file pkg/sql/parsers/dialect/mysql/keywords.go:**
### Pull Request Review:

#### Title and Body:
The title of the pull request indicates that it is an improvement related to adding a database configuration for `unique_check_on_autoincr`. The body of the pull request mentions that this PR only adds the configuration without using it yet, and that test cases will be added later. It also references the related issue #15809.

#### Changes in `keywords.go`:
The changes in `keywords.go` show the addition of the `unique_check_on_autoincr` keyword to the list of keywords in the MySQL dialect.

#### Feedback and Suggestions:
1. **Consistency in Comments:**
   - It is essential to maintain consistency in comments and commit messages. The comment in the code should be in English for better readability and maintainability.

2. **Use of Non-English Characters:**
   - The body of the pull request contains non-English characters which may make it difficult for English-speaking team members to understand. It is recommended to use English for all communication within the codebase and documentation.

3. **Testing:**
   - While it is mentioned that test cases will be added later, it is crucial to ensure that comprehensive testing is included before merging the code to avoid any potential issues related to the new configuration.

4. **Security Consideration:**
   - When introducing new configurations, especially related to unique constraints or auto-increment fields, it is important to consider potential security implications. Ensure that the new configuration does not introduce any vulnerabilities or weaken the database security.

5. **Optimization:**
   - Since this PR only adds a new keyword to the list, it seems straightforward. However, it is always good practice to review the entire context where this keyword will be used to ensure consistency and compatibility with existing code.

6. **Documentation:**
   - Once the configuration is fully implemented and tested, it is recommended to update the relevant documentation to reflect the new feature and its usage.

7. **Collaboration:**
   - Encourage collaboration between developers to ensure that the implementation of the new configuration aligns with the overall architecture and design principles of the project.

In conclusion, while the pull request seems to be a straightforward addition of a new configuration keyword, it is important to address the points mentioned above to maintain code quality, security, and collaboration within the team.

**Here are review comments for file pkg/sql/parsers/dialect/mysql/mysql_sql.go:**
### Pull Request Review:

#### Title:
The title of the pull request is clear and informative, indicating that the PR is an improvement related to adding a database configuration for unique check on auto increment.

#### Body:
The body of the pull request provides some context about the type of PR and the issue it addresses. It mentions that this PR is for adding a configuration without immediate usage, with plans to add corresponding test cases later. It would be beneficial to provide more details about the purpose and impact of this configuration for better understanding.

#### Changes:
Since the diff data is not provided, it is challenging to review the specific code changes. However, based on the description, it seems that the changes are related to adding a new database configuration for unique check on auto increment in the MySQL SQL parser.

### Feedback and Suggestions:

1. **Lack of Code Changes:**
   - It appears that the diff data for the code changes is missing. To provide a comprehensive review, it is essential to include the actual code modifications in the pull request.

2. **Incomplete Description:**
   - The body of the pull request could be improved by providing more details about the purpose and significance of the new configuration. This would help reviewers and other team members understand the rationale behind the changes.

3. **Testing Plan:**
   - While it is mentioned that test cases will be added later, it is crucial to ensure that comprehensive testing is included to cover the new configuration. Consider adding test cases as part of this PR to validate the functionality.

4. **Security Considerations:**
   - When introducing new database configurations, especially related to unique checks, ensure that proper validation and handling of unique constraints are implemented to prevent security vulnerabilities like duplicate entries or data integrity issues.

5. **Optimization:**
   - As a suggestion for optimization, consider incorporating the test cases along with the configuration changes in this PR to streamline the process and ensure that the feature is thoroughly tested before merging.

6. **Documentation:**
   - Update relevant documentation to reflect the new configuration and its usage to assist developers and users in understanding and utilizing this feature effectively.

In conclusion, while the intent of the pull request is clear, it is essential to provide the actual code changes, enhance the description for better clarity, include thorough testing, address security considerations, optimize the process by incorporating test cases, and update documentation accordingly.

**Here are review comments for file pkg/sql/parsers/dialect/mysql/mysql_sql.y:**
### Pull Request Review:

#### Title and Body:
The title of the pull request indicates that it is an improvement related to adding a database configuration for `UNIQUE_CHECK_ON_AUTOINCR`. The body of the pull request mentions that this change is part of splitting the pull request and that it only adds the configuration without immediate use, with plans to add corresponding test cases later. 

#### Changes in `pkg/sql/parsers/dialect/mysql/mysql_sql.y`:
1. **Addition of `UNIQUE_CHECK_ON_AUTOINCR` token**:
   - The token `UNIQUE_CHECK_ON_AUTOINCR` has been added to the list of tokens in the parser file.
  
2. **Alter Database Config Statement**:
   - New rules have been added to handle the `UNIQUE_CHECK_ON_AUTOINCR` configuration in the `ALTER DATABASE` statement.
   - The parser now recognizes and processes the `ALTER DATABASE db_name SET UNIQUE_CHECK_ON_AUTOINCR` syntax.

3. **Non-reserved Keyword**:
   - The `UNIQUE_CHECK_ON_AUTOINCR` keyword has been added to the list of non-reserved keywords in the parser.

#### Suggestions for Improvement:
1. **Consistency in Naming**:
   - Ensure consistency in naming conventions throughout the codebase. If `UNIQUE_CHECK_ON_AUTOINCR` is a configuration or feature, make sure the naming aligns with existing conventions.

2. **Documentation**:
   - Add inline comments or documentation to explain the purpose and usage of the new `UNIQUE_CHECK_ON_AUTOINCR` configuration for better understanding by other developers.

3. **Testing**:
   - As mentioned in the PR body, it is essential to add corresponding test cases for the new configuration to ensure its functionality and prevent regressions.

4. **Security Considerations**:
   - When introducing new configurations, especially related to unique constraints, ensure that there are no security vulnerabilities introduced. Perform thorough testing to validate the behavior under different scenarios.

5. **Code Optimization**:
   - Review the code for any redundant or unnecessary lines to optimize the implementation and improve code readability.

6. **Error Handling**:
   - Implement proper error handling mechanisms for the new configuration to provide meaningful error messages in case of invalid inputs or failures.

7. **Review with Team**:
   - Collaborate with team members to review the changes and gather feedback on the design and implementation of the new configuration.

By addressing these suggestions, the pull request can be enhanced in terms of functionality, maintainability, and security.

Overall, the addition of the `UNIQUE_CHECK_ON_AUTOINCR` configuration seems like a valuable improvement, and with the suggested enhancements, the codebase can be further strengthened.

**Here are review comments for file pkg/sql/parsers/tree/alter.go:**
### Pull Request Review:

#### Title:
The title of the pull request is clear and follows the conventional format of indicating a new feature addition.

#### Body:
The body of the pull request provides some context about the type of PR and the issue it addresses. It mentions that this PR adds a configuration but does not start using it yet. It also refers to splitting the PR and planning to add corresponding test cases later.

#### Changes in `pkg/sql/parsers/tree/alter.go`:
1. **Addition of DatabaseConfig Enum:**
   - An `enum` type `DatabaseConfig` is introduced to represent different types of database configurations.
   - This enum includes `MYSQL_COMPATIBILITY_MODE` and `UNIQUE_CHECK_ON_AUTOINCR`.
   - This addition is a good practice to manage different types of configurations in a structured way.

2. **Update in AlterDataBaseConfig Struct:**
   - The `AlterDataBaseConfig` struct is modified to include a new field `ConfigType` of type `DatabaseConfig`.
   - The `NewAlterDataBaseConfig` function is updated to accept the `configType` parameter and assign it to the `ConfigType` field.
   - This change allows for specifying the type of configuration being updated, enhancing clarity and extensibility.

#### Suggestions for Improvement:
1. **Use Meaningful Enum Values:**
   - While `MYSQL_COMPATIBILITY_MODE` is clear, `UNIQUE_CHECK_ON_AUTOINCR` could be more descriptive. Consider a name that clearly indicates what this configuration does, such as `ENABLE_UNIQUE_CHECK_ON_AUTO_INCREMENT`.

2. **Consistent Naming:**
   - Ensure consistency in naming conventions throughout the codebase. For example, `ConfigType` could be renamed to `configType` to align with common Go naming conventions.

3. **Documentation:**
   - Add comments or documentation to explain the purpose of the new enum values and how they should be used. This will help other developers understand the intent behind these configurations.

4. **Testing:**
   - As mentioned in the PR body, ensure to add test cases that cover the usage of the new configuration. Testing is crucial to validate the functionality and prevent regressions.

5. **Security Consideration:**
   - When introducing new configurations, especially related to unique constraints, ensure that proper validation and handling are in place to prevent any security vulnerabilities like SQL injection or data integrity issues.

6. **Optimization:**
   - Consider if there are any other related configurations or functionalities that can be grouped together to optimize the codebase and improve maintainability.

By addressing these suggestions, the codebase can be enhanced in terms of clarity, maintainability, and security. Additionally, thorough testing and documentation will ensure the reliability of the new feature.

**Here are review comments for file test/distributed/cases/database/config.result:**
### Pull Request Review:

#### Title:
The title of the pull request is clear and follows the conventional format for indicating a feature addition.

#### Body:
The body of the pull request provides some context about the type of PR and the issue it addresses. It mentions that the PR adds a configuration but does not start using it yet. It also references the issue number associated with the changes.

#### Changes in `test/distributed/cases/database/config.result`:
1. **Security Issue - Lack of Input Sanitization:**
   - The SQL queries in the file `config.result` are vulnerable to SQL injection attacks as they directly concatenate user input (`dat_name`) without proper sanitization. This can lead to malicious SQL queries being executed.
   - **Suggestion:** To prevent SQL injection, parameterized queries should be used or input validation and sanitization functions should be applied to user inputs.

2. **Redundant Query Modification:**
   - The changes made to the SQL queries seem unnecessary as they only add an additional condition (`variable_name = 'version_compatibility'`) without any apparent reason or explanation.
   - **Suggestion:** If the purpose of adding the `variable_name` condition is not clear, it should be reviewed and confirmed whether it is necessary. Unnecessary modifications should be avoided to maintain code clarity and efficiency.

3. **Lack of Comments or Descriptive Commit Message:**
   - The changes lack comments or a descriptive commit message explaining the rationale behind the modifications. This makes it difficult for other developers to understand the purpose of the changes.
   - **Suggestion:** It is recommended to add comments within the code to explain the significance of the modifications. Additionally, a clear and descriptive commit message should be provided to enhance code readability and maintainability.

#### Overall Suggestions for Optimization:
- **Code Review and Testing:** Before merging the changes, thorough code review and testing should be conducted to ensure the modifications are necessary, secure, and do not introduce any regressions.
- **Documentation:** Update the relevant documentation to reflect the new configuration and its usage once it is implemented.
- **Collaboration:** Collaborate with team members to discuss the necessity of the changes and gather feedback for further improvements.

By addressing the security vulnerabilities, avoiding unnecessary modifications, and enhancing code documentation, the quality and security of the codebase can be significantly improved.

**Here are review comments for file test/distributed/cases/database/config.sql:**
### Pull Request Review:

#### Title and Body:
The title of the pull request indicates that it is an improvement related to adding a database configuration for unique check on auto increment. The body of the pull request mentions that it is splitting the PR and only adding the configuration without using it yet, with the intention to add corresponding test cases later. It also references the related issue #15809.

#### Changes in `test/distributed/cases/database/config.sql`:
1. **Security Issue - SQL Injection Vulnerability:**
   - The SQL query in the changes made to `config.sql` is susceptible to SQL injection attacks. The query is constructed using string concatenation which allows for potential injection of malicious SQL code. To address this, parameterized queries should be used to prevent SQL injection. For example, using prepared statements in the code to bind parameters securely.

2. **Redundant SQL Queries:**
   - The SQL queries in the file are repeated unnecessarily. The `select` queries for `variable_value` from `mo_catalog.mo_mysql_compatibility_mode` are duplicated. This redundancy can lead to maintenance issues and inefficiencies. It is recommended to refactor the code to eliminate duplication and improve maintainability.

3. **Lack of Comments or Documentation:**
   - The changes made in the file lack comments or documentation to explain the purpose of the queries or the changes being made. Adding clear comments or documentation can improve code readability and help other developers understand the intent behind the modifications.

#### Suggestions for Improvement:
1. **SQL Injection Prevention:**
   - Refactor the SQL queries to use parameterized queries or prepared statements to prevent SQL injection vulnerabilities. This involves binding parameters securely instead of concatenating strings directly in the query.

2. **Code Optimization:**
   - Remove the redundant SQL queries by consolidating them into a single query where possible. This will reduce duplication and make the code more concise and maintainable.

3. **Documentation:**
   - Add comments or documentation to explain the purpose of the SQL queries and any significant changes being made. This will help developers understand the code more easily and facilitate future maintenance.

4. **Testing:**
   - As mentioned in the PR body, ensure that appropriate test cases are added to cover the new configuration and any related functionality. Testing is crucial to validate the changes and ensure they work as expected.

By addressing these issues and implementing the suggested improvements, the codebase can be enhanced in terms of security, efficiency, maintainability, and readability.

**Review by iamlinjunhong — APPROVED** [review]

**Review by qingxinhome — APPROVED** [review]

**Review by daviszhen — COMMENTED** [review]
跑短链接测试和ci regression

**Comment by jensenojs** [comment]
> 跑短链接测试和ci regression

嗯, 等issue 16421 fix 后

**Review by heni02 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Comment by jensenojs** [comment]
短链接测试设计: 
```sql
create database if not exists t;
use t;
create table t ...
select * from t;
drop database if exists t;
```
10并发, 跑了一分钟, 结果如下所示

this pr : 
image

main : 
image

tps和qps没有明显波动

**Review by daviszhen — APPROVED** [review]

**Comment by jensenojs** [comment]
https://github.com/daviszhen/morunner?tab=readme-ov-file#测试oom

利用morunner测试短链接的oom, 跑了二十分钟后, 内存结果如下所示
企业微信截图_69a3f87e-0743-47e1-a80d-bc286d6cb75a

**Review by ouyuanning — APPROVED** [review]

**Pull request merged**
