### PR TITLE
fix [#8499]

### PR DESCRIPTION
**Pull request by triump2020**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8499 

## What this PR does / why we need it:

### CODE REVIEW

**Comment by triump2020** [comment]
@matrix-meow rerun failed

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by guguducken** [comment]
@mergifyio refresh

**Comment by triump2020** [comment]
@matrix-meow rerun failed.

**Comment by triump2020** [comment]
@matrix-meow rerun failed

**Comment by triump2020** [comment]
@matrix-meow rerun failed

**Pull request merged**
