### PR TITLE
Fix panic interface conversion

### PR DESCRIPTION
**Pull request by broccoliSpicy**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2789

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by yingfeng — CHANGES_REQUESTED** [review]
Still these `interface conversion` panics reported:

```
2022-06-09T02:37:52.2426392Z 2022-06-09 02:37:52 ERROR Executor:222 - [cases/expression/case_when.sql][select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
2022-06-09T02:37:52.2426967Z join t2 on t1.a=t2.c order by d;] is executed failed
2022-06-09T02:37:52.2427557Z 2022-06-09 02:37:52 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T02:37:52.2427892Z a	d
2022-06-09T02:37:52.2428173Z 1	4572794622775114594
2022-06-09T02:37:52.2428457Z 3	11120436154190595086
2022-06-09T02:37:52.2428757Z 2	18196094287899841997
2022-06-09T02:37:52.2429204Z 2022-06-09 02:37:52 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T02:37:52.2429939Z unknown error:Internal error: panic interface conversion: interface {} is []uint64, not []int64: goroutine 54954 [running]:



2022-06-09T02:37:54.4805945Z 2022-06-09 02:37:54 ERROR Executor:222 - [cases/function/builtin.sql][select b from t1 where acos(a*pi()/180)<=acos(b*pi()/180)  order by a;] is executed failed
2022-06-09T02:37:54.4806955Z 2022-06-09 02:37:54 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T02:37:54.4807912Z b
2022-06-09T02:37:54.4808444Z -20.0
2022-06-09T02:37:54.4809356Z 0.0
2022-06-09T02:37:54.4809961Z 2022-06-09 02:37:54 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T02:37:54.4811070Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not *types.Bytes: goroutine 58183 [running]:



2022-06-09T02:38:09.9096936Z 2022-06-09 02:38:09 ERROR Executor:222 - [cases/function/func_aggr_max.test][select (min(a4)+max(a4))/2 from t1;] is executed failed
2022-06-09T02:38:09.9097907Z 2022-06-09 02:38:09 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T02:38:09.9098399Z (min(a4)+max(a4))/2
2022-06-09T02:38:09.9098788Z 0.085
2022-06-09T02:38:09.9099529Z 2022-06-09 02:38:09 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T02:38:09.9100499Z unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64: goroutine 68508 [running]:


2022-06-09T02:38:56.0730296Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][select ceiling(5.5),ceiling(-5.5);] is executed failed
2022-06-09T02:38:56.0730892Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T02:38:56.0731099Z 
2022-06-09T02:38:56.0735328Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T02:38:56.0736728Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not []int64: goroutine 1382 [running]:


2022-06-09T02:38:56.0941137Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][SELECT ACOS(1.0);] is executed failed
2022-06-09T02:38:56.0941847Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T02:38:56.0942051Z 
2022-06-09T02:38:56.0944987Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T02:38:56.0945702Z unknown error:Internal error: panic interface conversion: interface {} is acos.AcosResult, not []float64: goroutine 1382 [running]:


2022-06-09T02:38:56.0988589Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][SELECT ACOS(0.2*5.0);] is executed failed
2022-06-09T02:38:56.0989318Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
2022-06-09T02:38:56.0989530Z 
2022-06-09T02:38:56.0989793Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
2022-06-09T02:38:56.0990313Z unknown error:Internal error: panic interface conversion: interface {} is acos.AcosResult, not []float64: goroutine 1382 [running]:
```

**Comment by m-schen** [comment]
> Still these `interface conversion` panics reported:
> 
> ```
> 2022-06-09T02:37:52.2426392Z 2022-06-09 02:37:52 ERROR Executor:222 - [cases/expression/case_when.sql][select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
> 2022-06-09T02:37:52.2426967Z join t2 on t1.a=t2.c order by d;] is executed failed
> 2022-06-09T02:37:52.2427557Z 2022-06-09 02:37:52 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:37:52.2427892Z a	d
> 2022-06-09T02:37:52.2428173Z 1	4572794622775114594
> 2022-06-09T02:37:52.2428457Z 3	11120436154190595086
> 2022-06-09T02:37:52.2428757Z 2	18196094287899841997
> 2022-06-09T02:37:52.2429204Z 2022-06-09 02:37:52 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:37:52.2429939Z unknown error:Internal error: panic interface conversion: interface {} is []uint64, not []int64: goroutine 54954 [running]:
> 
> 
> 
> 2022-06-09T02:37:54.4805945Z 2022-06-09 02:37:54 ERROR Executor:222 - [cases/function/builtin.sql][select b from t1 where acos(a*pi()/180)<=acos(b*pi()/180)  order by a;] is executed failed
> 2022-06-09T02:37:54.4806955Z 2022-06-09 02:37:54 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:37:54.4807912Z b
> 2022-06-09T02:37:54.4808444Z -20.0
> 2022-06-09T02:37:54.4809356Z 0.0
> 2022-06-09T02:37:54.4809961Z 2022-06-09 02:37:54 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:37:54.4811070Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not *types.Bytes: goroutine 58183 [running]:
> 
> 
> 
> 2022-06-09T02:38:09.9096936Z 2022-06-09 02:38:09 ERROR Executor:222 - [cases/function/func_aggr_max.test][select (min(a4)+max(a4))/2 from t1;] is executed failed
> 2022-06-09T02:38:09.9097907Z 2022-06-09 02:38:09 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:09.9098399Z (min(a4)+max(a4))/2
> 2022-06-09T02:38:09.9098788Z 0.085
> 2022-06-09T02:38:09.9099529Z 2022-06-09 02:38:09 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:09.9100499Z unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64: goroutine 68508 [running]:
> 
> 
> 2022-06-09T02:38:56.0730296Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][select ceiling(5.5),ceiling(-5.5);] is executed failed
> 2022-06-09T02:38:56.0730892Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:56.0731099Z 
> 2022-06-09T02:38:56.0735328Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:56.0736728Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not []int64: goroutine 1382 [running]:
> 
> 
> 2022-06-09T02:38:56.0941137Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][SELECT ACOS(1.0);] is executed failed
> 2022-06-09T02:38:56.0941847Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:56.0942051Z 
> 2022-06-09T02:38:56.0944987Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:56.0945702Z unknown error:Internal error: panic interface conversion: interface {} is acos.AcosResult, not []float64: goroutine 1382 [running]:
> 
> 
> 2022-06-09T02:38:56.0988589Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][SELECT ACOS(0.2*5.0);] is executed failed
> 2022-06-09T02:38:56.0989318Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:56.0989530Z 
> 2022-06-09T02:38:56.0989793Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:56.0990313Z unknown error:Internal error: panic interface conversion: interface {} is acos.AcosResult, not []float64: goroutine 1382 [running]:
> ```

I will fix case - when panic problem at another pull-request

**Comment by yingfeng** [comment]
> 

OK

**Comment by broccoliSpicy** [comment]
> Still these `interface conversion` panics reported:
> 
> ```
> 2022-06-09T02:37:52.2426392Z 2022-06-09 02:37:52 ERROR Executor:222 - [cases/expression/case_when.sql][select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
> 2022-06-09T02:37:52.2426967Z join t2 on t1.a=t2.c order by d;] is executed failed
> 2022-06-09T02:37:52.2427557Z 2022-06-09 02:37:52 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:37:52.2427892Z a	d
> 2022-06-09T02:37:52.2428173Z 1	4572794622775114594
> 2022-06-09T02:37:52.2428457Z 3	11120436154190595086
> 2022-06-09T02:37:52.2428757Z 2	18196094287899841997
> 2022-06-09T02:37:52.2429204Z 2022-06-09 02:37:52 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:37:52.2429939Z unknown error:Internal error: panic interface conversion: interface {} is []uint64, not []int64: goroutine 54954 [running]:
> 
> 
> 
> 2022-06-09T02:37:54.4805945Z 2022-06-09 02:37:54 ERROR Executor:222 - [cases/function/builtin.sql][select b from t1 where acos(a*pi()/180)<=acos(b*pi()/180)  order by a;] is executed failed
> 2022-06-09T02:37:54.4806955Z 2022-06-09 02:37:54 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:37:54.4807912Z b
> 2022-06-09T02:37:54.4808444Z -20.0
> 2022-06-09T02:37:54.4809356Z 0.0
> 2022-06-09T02:37:54.4809961Z 2022-06-09 02:37:54 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:37:54.4811070Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not *types.Bytes: goroutine 58183 [running]:
> 
> 
> 
> 2022-06-09T02:38:09.9096936Z 2022-06-09 02:38:09 ERROR Executor:222 - [cases/function/func_aggr_max.test][select (min(a4)+max(a4))/2 from t1;] is executed failed
> 2022-06-09T02:38:09.9097907Z 2022-06-09 02:38:09 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:09.9098399Z (min(a4)+max(a4))/2
> 2022-06-09T02:38:09.9098788Z 0.085
> 2022-06-09T02:38:09.9099529Z 2022-06-09 02:38:09 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:09.9100499Z unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64: goroutine 68508 [running]:
> 
> 
> 2022-06-09T02:38:56.0730296Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][select ceiling(5.5),ceiling(-5.5);] is executed failed
> 2022-06-09T02:38:56.0730892Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:56.0731099Z 
> 2022-06-09T02:38:56.0735328Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:56.0736728Z unknown error:Internal error: panic interface conversion: interface {} is []float64, not []int64: goroutine 1382 [running]:
> 
> 
> 2022-06-09T02:38:56.0941137Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][SELECT ACOS(1.0);] is executed failed
> 2022-06-09T02:38:56.0941847Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:56.0942051Z 
> 2022-06-09T02:38:56.0944987Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:56.0945702Z unknown error:Internal error: panic interface conversion: interface {} is acos.AcosResult, not []float64: goroutine 1382 [running]:
> 
> 
> 2022-06-09T02:38:56.0988589Z 2022-06-09 02:38:56 ERROR Executor:222 - [cases/function/func_math.test][SELECT ACOS(0.2*5.0);] is executed failed
> 2022-06-09T02:38:56.0989318Z 2022-06-09 02:38:56 ERROR Executor:223 - [EXPECT RESULT]:
> 2022-06-09T02:38:56.0989530Z 
> 2022-06-09T02:38:56.0989793Z 2022-06-09 02:38:56 ERROR Executor:224 - [ACTUAL RESULT]:
> 2022-06-09T02:38:56.0990313Z unknown error:Internal error: panic interface conversion: interface {} is acos.AcosResult, not []float64: goroutine 1382 [running]:
> ```

panic 1 will be handled by @m-schen 
panic 2 is caused by comparison operator, @jianwan0214, could you please tell me why would you use so many type assertions in comparison operator

panic 3 I cannot reproduce, 

the rest are fixed

**Pull request merged**
