### PR TITLE
Add log for cn panic which reported on issue 10193

### PR DESCRIPTION
**Pull request by cnutshell**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10193

## What this PR does / why we need it:
Add more log in order to record detailed information for cn panic.

### CODE REVIEW

**Review by XuPeng-SH — APPROVED** [review]

**Review by triump2020 — APPROVED** [review]

**Review by fengttt — CHANGES_REQUESTED** [review]
Why is this useful?   We already record panic in log.

**Comment by cnutshell** [comment]
> Why is this useful? We already record panic in log.

[the added log](https://github.com/cnutshell/matrixone/blob/d14d3c3525cbfd255cacfe5ae8a433a3542d19d6/pkg/vm/engine/disttae/txn_table.go#L1184) doesn't only report stack but also the goroutine ID which cleans `txn`.

**Comment by cnutshell** [comment]
@mergify requeue

**Comment by cnutshell** [comment]
@mergify refresh

**Comment by fengttt** [comment]
> > Why is this useful? We already record panic in log.
> 
> 
> 
> [the added log](https://github.com/cnutshell/matrixone/blob/d14d3c3525cbfd255cacfe5ae8a433a3542d19d6/pkg/vm/engine/disttae/txn_table.go#L1184) doesn't only report stack and its goroutine ID but also report the goroutine ID which cleans `txn`.

this is not true.   panic has stack.  it is in the issue.

**Comment by fengttt** [comment]
why goroutine id is useful anyway?

**Review by fengttt — APPROVED** [review]

**Pull request merged**
