### PR TITLE
do not check the privilege of the index table

### PR DESCRIPTION
**Pull request by daviszhen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7381 

## What this PR does / why we need it:
Do not check the privilege of the index table that is in the shadow.

### CODE REVIEW

**Review by sukki37 — COMMENTED** [review]
better to add some bvt cases

**Comment by DanielZhangQD** [comment]
With the latest commit 5e8b41364349c2a4e40fc9311cf70ac369a62299, even the primary key cannot be included in the update sql:
```
mysql> UPDATE `mo_instance` SET `id`='b7ef2718-01ef-42af-8ca3-919bbe6f9e87',`name`='bbbb',`created_by`='abxy',`created_at`='2006-01-02 15:04:05' WHERE id = 'b7ef2718-01ef-42af-8ca3-919bbe6f9e87' and account_id = 1;
ERROR 20101 (HY000): internal error: do not have privilege to execute the statement
```

**Comment by daviszhen** [comment]
> better to add some bvt cases

I have added the bvt cases.

**Review by heni02 — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by sukki37 — CHANGES_REQUESTED** [review]
I hope that the cases associated with the bug issue are added to the bvt, so could add one more bvt case which mentioned here: https://github.com/matrixorigin/matrixone/issues/7381#issuecomment-1367685546

**Review by sukki37 — APPROVED** [review]

**Pull request merged**
