### PR TITLE
fix a bug that some filters don't push to block filter for 1.1-dev

### PR DESCRIPTION
**Pull request by badboynt1**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #15286 

## What this PR does / why we need it:
fix a bug that some filters don't push to block filter

### CODE REVIEW

**Comment by matrix-meow** [comment]
@badboynt1 Thanks for your contributions!

### Pull Request Review:

#### Problem:
1. **Missing Parameter in Function Call:**
   - In the `estimateFilterBlockSelectivity` function, a new parameter `builder *QueryBuilder` has been added to the function signature. However, in the `calcScanStats` function, the call to `estimateFilterBlockSelectivity` is missing this new parameter, which will lead to a compilation error.

#### Suggestions to Address:
1. **Update Function Call:**
   - In the `calcScanStats` function, ensure that the `builder` parameter is passed to the `estimateFilterBlockSelectivity` function to match the updated function signature. This will prevent compilation errors and ensure the code functions correctly.

#### Optimization Suggestions:
1. **Consistency in Naming:**
   - Ensure consistent naming conventions are followed throughout the codebase to improve readability and maintainability. For example, consider using consistent naming for variables, functions, and parameters.

2. **Code Comments:**
   - Add or update comments to explain the purpose and functionality of the modified functions or parameters. This will help developers understand the code more easily and maintain it effectively.

3. **Code Refactoring:**
   - Consider refactoring the code to improve modularity and readability. Breaking down complex functions into smaller, more manageable units can enhance code maintainability and facilitate future updates.

By addressing the identified problem and considering the optimization suggestions, the codebase can be improved in terms of functionality, readability, and maintainability.

**Review by aunjgr — APPROVED** [review]

**Review by sukki37 — APPROVED** [review]

**Comment by guguducken** [comment]
@mergifyio refresh

**Comment by guguducken** [comment]
@mergify unqueue

**Comment by guguducken** [comment]
@mergify queue

**Pull request merged**
