### PR TITLE
[MatrixCamp] Add built-in func UTC_TIMESTAMP

### PR DESCRIPTION
**Pull request by noneback**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1976

**What this PR does / why we need it:**

Add UTC_Timestamp built-in function

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by noneback** [comment]
I do not consider the test failure has something to do with my code.Can I run CI and Test again ?

**Review by broccoliSpicy — APPROVED** [review]
excellent code

**Review by broccoliSpicy — CHANGES_REQUESTED** [review]
actually, I think what you've implemented here is the function now(), rather than utc_timestamp(), since time.Now() function returns the local time, rather than the utc_time

**Comment by noneback** [comment]
> actually, I think what you've implemented here is the function now(), rather than utc_timestamp(), since time.Now() function returns the local time, rather than the utc_time

Sorry. I will fix it.

**Comment by noneback** [comment]
I have fixed it. Plz review it at your convenience.

**Review by broccoliSpicy — APPROVED** [review]
looks good to me

**Comment by yingfeng** [comment]
Pls resolve the confliction before it's merged

**Comment by noneback** [comment]
> Pls resolve the confliction before it's merged

Resolved.

**Comment by domingozhang** [comment]
BVT passed

**Pull request merged**
