### PR TITLE
[feat] Connection pool mainly used for logservice.

### PR DESCRIPTION
**Pull request by volgariver6**
ConnPool is connection pool which manage connections. It enables connection reuse. After the connection is used, it is not released directly, but is returned to the connection pool for the next request. It has the following functions:

1. Initialize and create a certain number of idle connections in advance.
2. Acquire method is provides to get a connection.
3. If there is an idle connection in the connection pool, directly return it.
4. And if there is none, then judge whether the number of connections in the current connection pool exceeds the maximum threshold, if so, check if AllowOverUse is true. If it is true, return a temp connection, otherwise, wait.
5. If the maximum threshold is not exceeded, create a new connection and store it in the connection pool.
6. Release method is provided to release the connection. If the connection is temp, close it directly. Otherwise, put it back into the pool.

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

To replace the current connection pool in tae.

### CODE REVIEW

**Comment by fengttt** [comment]
I have a philosophical question.   Given that DN will connect to logservice on start and almost surely, won't disconnect during its life time, why do we need a pool?    A fixed array of connection seems just do fine.

**Comment by volgariver6** [comment]
> I have a philosophical question. Given that DN will connect to logservice on start and almost surely, won't disconnect during its life time, why do we need a pool? A fixed array of connection seems just do fine.

1. The connection pool can flexibly provide management of connections. At present, it may only be used by logservice, and there may be other modules used in the future? I don't know. At that time, it may be necessary to provide more complex connection pool management functions.
2. If the MaxSize and InitSize of the currently implemented connection pool are set equal, and MaxLifetime and MaxIdleTime are set to 0, then it is a fixed-size array, which is enough to meet the current needs.

**Comment by fengttt** [comment]
> > I have a philosophical question. Given that DN will connect to logservice on start and almost surely, won't disconnect during its life time, why do we need a pool? A fixed array of connection seems just do fine.
> 
> 1. The connection pool can flexibly provide management of connections. At present, it may only be used by logservice, and there may be other modules used in the future? I don't know. At that time, it may be necessary to provide more complex connection pool management functions.
> 2. If the MaxSize and InitSize of the currently implemented connection pool are set equal, and MaxLifetime and MaxIdleTime are set to 0, then it is a fixed-size array, which is enough to meet the current needs.

Why do we need to do this now?   Why not wait, and when "later we need it", we do it.

**Comment by volgariver6** [comment]
> > > I have a philosophical question. Given that DN will connect to logservice on start and almost surely, won't disconnect during its life time, why do we need a pool? A fixed array of connection seems just do fine.
> > 
> > 
> > 
> > 1. The connection pool can flexibly provide management of connections. At present, it may only be used by logservice, and there may be other modules used in the future? I don't know. At that time, it may be necessary to provide more complex connection pool management functions.
> > 2. If the MaxSize and InitSize of the currently implemented connection pool are set equal, and MaxLifetime and MaxIdleTime are set to 0, then it is a fixed-size array, which is enough to meet the current needs.
> 
> Why do we need to do this now? Why not wait, and when "later we need it", we do it.

OK.

**Review by fengttt — APPROVED** [review]

**Comment by volgariver6** [comment]
close it first. I will commit a new pr when it is needed.

**Pull request closed without merging**
