### PR TITLE
Migration of sql protocol (#1176)

### PR DESCRIPTION
**Pull request by iamlinjunhong**
**Which issue(s) this PR fixes:**

issue #1176

### CODE REVIEW

**Comment by nnsgmsone** [comment]
The structure of the scope has changed, so serialization needs to be refactored

**Comment by m-schen** [comment]
`vec1.Append(vec2)` function is `vector.Append(vec1, vec2)`
there's no need to add a new one.

**Comment by iamlinjunhong** [comment]
> `vec1.Append(vec2)` function is `vector.Append(vec1, vec2)` now there's no need to add a new one.

Avoid conflict when merge into main

**Comment by iamlinjunhong** [comment]
> The structure of the scope has changed, so serialization needs to be refactored

I need to be told the define of transformed scope

**Pull request closed without merging**
