### PR TITLE
add gomonkey to check if mo exit by it self

### PR DESCRIPTION
**Pull request by zhangxu19830126**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5727 

## What this PR does / why we need it:
hack os.Exit and panic, then we can found the call stack

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
Will this have any performance impact?   We just replaced os.Exit, or gomonkey will slow down everything?

**Comment by fengttt** [comment]
@jinqinghui please take a look as well.    is there a way to catch all exit at os level?

@zhangxu19830126 if it will not slow down everything, I suggest we just merge this one.   If it is too costly, isn't all you need is atexit?  Or let @jinqinghui help.

We need to solve those exits without a trace problem.    Need that in real production.

**Comment by zhangxu19830126** [comment]
> @jinqinghui please take a look as well. is there a way to catch all exit at os level?
> 
> @zhangxu19830126 if it will not slow down everything, I suggest we just merge this one. If it is too costly, isn't all you need is atexit? Or let @jinqinghui help.
> 
> We need to solve those exits without a trace problem. Need that in real production.

It will slow down everything.

**Comment by zhangxu19830126** [comment]
It's not mo's problem.

**Pull request closed without merging**
