### PR TITLE
[MatrixCamp] Add built-in function endswith

### PR DESCRIPTION
**Pull request by chaixuqing**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2118

**What this PR does / why we need it:**

Add built-in function endsWith

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by broccoliSpicy — APPROVED** [review]
lit

**Comment by domingozhang** [comment]
@chaixuqing 
the step of binary build failed. Please check.

**Comment by chaixuqing** [comment]
> @chaixuqing the step of binary build failed. Please check.
A newly merged pull request and my pull request define the same function name.

**Review by domingozhang — APPROVED** [review]
bvt passed

**Pull request merged**
