### PR TITLE
fix err handle

### PR DESCRIPTION
**Pull request by aptend**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6998 

## What this PR does / why we need it:

### CODE REVIEW

**Comment by fengttt** [comment]
What did you fix?   I see some syntax sugar, but did we really fix domething?

**Comment by aptend** [comment]
> What did you fix? I see some syntax sugar, but did we really fix something?

in this function, batch will be closed in defer function if any error happens. but if bat is declared in the return value, it will be assigned nil first and execute defer function, and then nil is accessed and panic. 
https://github.com/matrixorigin/matrixone/blob/10de8b3363c7c93db8d0478d8c4ebed106a5844d/pkg/vm/engine/tae/dataio/blockio/read.go#L155

**Comment by fengttt** [comment]
> 

Well.   Does the change in this PR has anything to do with that?    I see you changed from named return to a local variable, does it affect error handling?    I am not language expert but it is at least a surprise.

**Comment by aptend** [comment]
> > 
> 
> Well. Does the change in this PR has anything to do with that? I see you changed from named return to a local variable, does it affect error handling? I am not language expert but it is at least a surprise.

for example, if read s3 failed, the `return nil, err` won't affect the local variable `bat`, it can't be nil.
https://github.com/matrixorigin/matrixone/blob/10de8b3363c7c93db8d0478d8c4ebed106a5844d/pkg/vm/engine/tae/dataio/blockio/read.go#L178-L181

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Pull request merged**
