### PR TITLE
Release the buffer after WriteEnd is executed

### PR DESCRIPTION
**Pull request by LeftHandCold**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/59

## What this PR does / why we need it:
The buffer needs to be released at the end of WriteEnd
Because the outside may hold this writer
After WriteEnd is called, no more data can be written

### CODE REVIEW

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Review by fengttt — APPROVED** [review]

**Pull request merged**
