### PR TITLE
fix load composite primary key panic bug

### PR DESCRIPTION
**Pull request by bbbearxyz**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5329 

## What this PR does / why we need it:

### CODE REVIEW

**Review by ouyuanning — APPROVED** [review]

**Review by daviszhen — APPROVED** [review]

**Comment by bbbearxyz** [comment]
All failed jobs are rerun ----- @matrix-meow

**Comment by bbbearxyz** [comment]
All failed jobs are rerun ----- @matrix-meow

**Comment by gugutiger** [comment]
@matrix-meow rerun failed

**Comment by guguducken** [comment]
@matrix-meow rerun failed

**Comment by bbbearxyz** [comment]
@matrix-meow rerun failed

**Review by aunjgr — APPROVED** [review]

**Pull request merged**
