### PR TITLE
[MatrixCamp] Add new feature : now

### PR DESCRIPTION
**Pull request by ikenchina**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #https://github.com/matrixorigin/matrixone/issues/1830

**What this PR does / why we need it:**

Implemented now() function.
Notice : types.DateTime hasn't yet implemented fsp(fractional seconds precision), so, don't consider fsp when format DateTime to string.

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by broccoliSpicy — CHANGES_REQUESTED** [review]
huh...

**Comment by m-schen** [comment]
Why modify parser file, and set  NOW() at aggregate-function rule. 
I think now() is just a built-in function but not aggregate

**Comment by ikenchina** [comment]
it is necessary to modify parser because it can't parse `NOW()`.
I added NOW to wrong place, i will change it.

**Comment by broccoliSpicy** [comment]
> it is necessary to modify parser because it can't parse `NOW()`.
> I added NOW to wrong place, i will change it.

In my understanding of our code, the function name will be recognized as long as you follow the function registration procedure,

**Comment by ikenchina** [comment]
Do you mean `select_expression` rule in mysql_sql.y ? 
If so, i don't think it can match that rule.

**Comment by broccoliSpicy** [comment]
indeed getting the time in the function execution is not accurate, but adding a field to the process struct is the kind of decision that I don't have a say in, @nnsgmsone

**Comment by domingozhang** [comment]
In current MO syntax, this function cannot be verified directly with BVT.

**Comment by broccoliSpicy** [comment]
in matrixone, each node has its own process struct, and the query execute on which node is not deterministic, ergo, getting the time from the process struct is not accurate, we also need to distribute the timestamp in the process struct to other nodes,

**Comment by fengttt** [comment]
current_timestamp/now is folded in planner now.

**Pull request closed without merging**
