### PR TITLE
lockservice: fix data race

### PR DESCRIPTION
**Pull request by zhangxu19830126**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8479 

## What this PR does / why we need it:
Fix data race when close the local lock table

### CODE REVIEW

**Review by w-zr — APPROVED** [review]

**Comment by zhangxu19830126** [comment]
@mergifyio refresh

**Comment by zhangxu19830126** [comment]
https://github.com/Mergifyio refresh

**Comment by zhangxu19830126** [comment]
@mergifyio refresh

**Comment by zhangxu19830126** [comment]
@Mergifyio refresh

**Pull request merged**
