### PR TITLE
[RFC] implement ln builtin function

### PR DESCRIPTION
**Pull request by adlternative**
**What type of PR is this?**

- [x] Feature

**Which issue(s) this PR fixes:**

issue #1825

**What this PR does / why we need it:**

implement ln(x).

**Special notes for your reviewer:**

1. how can I output "NULL" for users if the x <= 0?

2. what if we have a table `p1` like this:
```
+------+--------+
| id   | score  |
+------+--------+
|    1 | 1.1000 |
|    2 | 2.2000 |
|   -1 | 3.3000 |
|    4 | 4.4000 |
+------+--------+

```

and use `select ln(id) from p1;`
show it output all enties like:
```
+--------+
| ln(id) | 
+--------+
| 0.0000 |
| 0.6931 |
| NULL   |
| 1.3862 |
+--------+
ERROR 1105 (HY000): unknown error:Invalid argument for logarithm
```
But for now, it will only output:
"ERROR 1105 (HY000): unknown error: Invalid argument for logarithm"
Is there any way to fix it?

### CODE REVIEW

**Comment by m-schen** [comment]
if you want to output NULL for negative numbers, you need to do range check for each number at vector. This may have a bad effect on the speed of the function.

And we are currently developing mainly with reference to the ANSI. (I'm not sure if it define the performance of this function, and return and NAN but not NULL may suitable? )
Therefore we prefer the performance of Postgres, it is acceptable to return an error message directly.

**Comment by m-schen** [comment]
if you want to output NULL for negative numbers.
You can additionally init and return a null structure in the function Ln (LnFloat32Pure and so on.) but not return an error directly.

and use the null to do adjustment work for result's nulls list by nulls.Or function. @adlternative

**Comment by WenhaoKong2001** [comment]
> **What type of PR is this?**
> 
> * [*] Feature
> 
> **Which issue(s) this PR fixes:**
> 
> issue #1825
> 
> **What this PR does / why we need it:**
> 
> implement ln(x).
> 
> **Special notes for your reviewer:**
> 
> 1. how can I output "NULL" for users if the x <= 0?
> 2. what if we have a table `p1` like this:
> 
> ```
> +------+--------+
> | id   | score  |
> +------+--------+
> |    1 | 1.1000 |
> |    2 | 2.2000 |
> |   -1 | 3.3000 |
> |    4 | 4.4000 |
> +------+--------+
> ```
> 
> and use `select ln(id) from p1;` show it output all enties like:
> 
> ```
> +--------+
> | ln(id) | 
> +--------+
> | 0.0000 |
> | 0.6931 |
> | NULL   |
> | 1.3862 |
> +--------+
> ERROR 1105 (HY000): unknown error:Invalid argument for logarithm
> ```
> 
> But for now, it will only output: "ERROR 1105 (HY000): unknown error: Invalid argument for logarithm" Is there any way to fix it?

I am implementing function log and have the same problem.I don't know how to use vectors and nulls.

**Comment by adlternative** [comment]
Now I use a new struct `LnResult` as the result of ln(x),

```go
type LnResult struct {
	Result []float64
	Nsp    *nulls.Nulls
}
```
if the x <= 0, set the rowId to null bitmap. But now it still have a little problem:
```
MySQL [adl]> select * from p1;
+------+---------+
| id   | score   |
+------+---------+
|    1 |  1.1000 |
|    2 |  2.2000 |
|   -1 |  3.3000 |
|    4 |  4.4000 |
| NULL |  1.1000 |
|    5 | -1.1000 |
+------+---------+
```
I hope it can output like:
```
MySQL [adl]> select ln(id),ln(score) from p1;
+--------+-----------+
| ln(id) | ln(score) |
+--------+-----------+
| 0.0000 |    0.0953 |
| 0.6931 |    0.7885 |
|   NULL |    1.1939 |
| 1.3863 |    1.4816 |
|   NULL |    0.0953 |
| 1.6094 |      NULL |
+--------+-----------+
```
but it output:
```
MySQL [adl]> select ln(id),ln(score) from p1;
+--------+-----------+
| ln(id) | ln(score) |
+--------+-----------+
| 0.0000 |    0.0953 |
| 0.6931 |    0.7885 |
|   NULL |    1.1939 |
| 1.3863 |    1.4816 |
|   NULL |    0.0953 |
| 1.6094 |    0.0000 |
+--------+-----------+
```

but only the the ln(id) column can output NULL whene the id < 0
because it have a NULL value before, but the ln(score) didn't have it.
so what's the wrong with it? @m-schen

**Comment by broccoliSpicy** [comment]
I think the cause here is perhaps this:
In your example, the column "score" doesn't contain any NULL values, so this column's original NULL map is nil, this may cause this line of your code invalid
```go
resultVector.Nsp.Or(lnResult.Nsp) // this resultVector.Nsp is nil in the "score" column,
```

I think add a patch like this might help:
```go
if !nulls.Any(resultVector.Nsp) {
						resultVector.Nsp = lnResult.Nsp
					} else {
						resultVector.Nsp.Or(lnResult.Nsp)
					}
```
I didn't really try it though.

**Comment by broccoliSpicy** [comment]
> > **What type of PR is this?**
> > 
> > * [*] Feature
> > 
> > **Which issue(s) this PR fixes:**
> > issue #1825
> > **What this PR does / why we need it:**
> > implement ln(x).
> > **Special notes for your reviewer:**
> > 
> > 1. how can I output "NULL" for users if the x <= 0?
> > 2. what if we have a table `p1` like this:
> > 
> > ```
> > +------+--------+
> > | id   | score  |
> > +------+--------+
> > |    1 | 1.1000 |
> > |    2 | 2.2000 |
> > |   -1 | 3.3000 |
> > |    4 | 4.4000 |
> > +------+--------+
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and use `select ln(id) from p1;` show it output all enties like:
> > ```
> > +--------+
> > | ln(id) | 
> > +--------+
> > | 0.0000 |
> > | 0.6931 |
> > | NULL   |
> > | 1.3862 |
> > +--------+
> > ERROR 1105 (HY000): unknown error:Invalid argument for logarithm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But for now, it will only output: "ERROR 1105 (HY000): unknown error: Invalid argument for logarithm" Is there any way to fix it?
> 
> I am implementing function log and have the same problem.I don't know how to use vectors and nulls.

MatrixOne uses a bitmap to store all NULL values in a column, we have same wrap up functions for this bitmap library [roaring](https://github.com/RoaringBitmap/roaring) in the directory  pkg/container/nulls, to add some new NULL values, you can initiate a new nulls.Nulls struct, store all new NULL values and "or" it with the original bitmap.

**Comment by adlternative** [comment]
> I think the cause here is perhaps this: In your example, the column "score" doesn't contain any NULL values, so this column's original NULL map is nil, this may cause this line of your code invalid
> 
> ```go
> resultVector.Nsp.Or(lnResult.Nsp) // this resultVector.Nsp is nil in the "score" column,
> ```
> 
> I think add a patch like this might help:
> 
> ```go
> if !nulls.Any(resultVector.Nsp) {
>     resultVector.Nsp = lnResult.Nsp
> } else {
>     resultVector.Nsp.Or(lnResult.Nsp)
> }
> ```
> 
> I didn't really try it though.

Thanks for help.I think it's work now! :+1:

**Review by broccoliSpicy — COMMENTED** [review]
flawless code...

**Review by m-schen — APPROVED** [review]
looks good to me. 
And please add license related code in the header of files. @WenhaoKong2001 
That's not a big problem.

**Review by broccoliSpicy — APPROVED** [review]

**Comment by yingfeng** [comment]
Pls add license information to each newly added header file before it is merged

**Pull request merged**
