### PR TITLE
fix issue#1914

### PR DESCRIPTION
**Pull request by broccoliSpicy**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1914 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by broccoliSpicy** [comment]
ohh, isn't this a ugly patch..., hoping the Golang generics would offer some neat solution for this kinds of redundant code

**Review by m-schen — CHANGES_REQUESTED** [review]
I think you can use `if vector.Length(lv) == 1 {lv = true}`  instead of it.

**Comment by m-schen** [comment]
you should merge main branch again.
because we change the expected result of bvt.
And this commit is good. @broccoliSpicy

**Review by m-schen — APPROVED** [review]
it's good

**Pull request merged**
