### PR TITLE
[BugFix]: Master Index `IN` support

### PR DESCRIPTION
**Pull request by arjunsk**
## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue # https://github.com/matrixorigin/matrixone/issues/14829

## What this PR does / why we need it:

Convert `c IN ("1", "2", "3")` to  `prefix_in(__mo_index_idx_col, serial_full("c","1")) OR prefix_in(__mo_index_idx_col, serial_full("c","2")) OR prefix_in(__mo_index_idx_col, serial_full("c","3"))`

```sql
create database a;
use a;

drop table if exists t1;
create table t1(a varchar(30), b varchar(30), c varchar(30));
create index idx1 using master on t1(a,b,c);
insert into t1 values("Congress","Lane", "1");
insert into t1 values("Juniper","Way", "2");
insert into t1 values("Nightingale","Lane", "3");

mysql> select * from t1 where a in ("Congress","Nightingale") and b="Lane" and c in("1","2","3");
+-------------+------+------+
| a           | b    | c    |
+-------------+------+------+
| Congress    | Lane | 1    |
| Nightingale | Lane | 3    |
+-------------+------+------+
2 rows in set (0.00 sec)

mysql> explain analyze select * from t1 where a in ("Congress","Nightingale") and b="Lane" and c in("1","2","3");
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Project                                                                                                                                                   |
|   Analyze: timeConsumed=0ms waitTime=0ms inputRows=2 outputRows=2 InputSize=144bytes OutputSize=144bytes MemorySize=144bytes                              |
|   ->  Join                                                                                                                                                |
|         Analyze: timeConsumed=0ms waitTime=6ms inputRows=4 outputRows=2 InputSize=176bytes OutputSize=144bytes MemorySize=16bytes                         |
|         Join Type: INDEX                                                                                                                                  |
|         Join Cond: (t1.__mo_fake_pk_col = #[1,0])                                                                                                         |
|         Runtime Filter Build: #[-1,0]                                                                                                                     |
|         ->  Table Scan on a.t1                                                                                                                            |
|               Analyze: timeConsumed=0ms waitTime=0ms inputRows=3 outputRows=2 InputSize=240bytes OutputSize=160bytes MemorySize=409bytes                  |
|               Filter Cond: (t1.b = 'Lane'), t1.c in ([1 2 3]), t1.a in ([Congress Nightingale])                                                           |
|               Block Filter Cond: t1.__mo_fake_pk_col in ([1 3])                                                                                           |
|               Runtime Filter Probe: t1.__mo_fake_pk_col                                                                                                   |
|         ->  Join                                                                                                                                          |
|               Analyze: timeConsumed=0ms waitTime=0ms inputRows=2 outputRows=2 InputSize=16bytes OutputSize=16bytes MemorySize=32898bytes                  |
|               Join Type: INNER                                                                                                                            |
|               Join Cond: (#[0,0] = #[1,0])                                                                                                                |
|               ->  Project                                                                                                                                 |
|                     Analyze: timeConsumed=0ms waitTime=0ms inputRows=2 outputRows=2 InputSize=16bytes OutputSize=16bytes MemorySize=16bytes               |
|                     ->  Table Scan on a.__mo_index_secondary_018e1c11-7558-7af2-b7dc-6c107f040c53                                                         |
|                           Analyze: timeConsumed=0ms waitTime=0ms inputRows=9 outputRows=2 InputSize=288bytes OutputSize=16bytes MemorySize=313bytes       |
|                           Filter Cond: prefix_in(#[0,0], [Fa FCongress  Fa FNightingale ])                                                            |
|               ->  Join                                                                                                                                    |
|                     Analyze: timeConsumed=0ms waitTime=0ms inputRows=2 outputRows=2 InputSize=16bytes OutputSize=16bytes MemorySize=32898bytes            |
|                     Join Type: INNER                                                                                                                      |
|                     Join Cond: (#[0,0] = #[1,0])                                                                                                          |
|                     ->  Project                                                                                                                           |
|                           Analyze: timeConsumed=0ms waitTime=0ms inputRows=3 outputRows=3 InputSize=24bytes OutputSize=24bytes MemorySize=24bytes         |
|                           ->  Table Scan on a.__mo_index_secondary_018e1c11-7558-7af2-b7dc-6c107f040c53                                                   |
|                                 Analyze: timeConsumed=0ms waitTime=0ms inputRows=9 outputRows=3 InputSize=288bytes OutputSize=24bytes MemorySize=321bytes |
|                                 Filter Cond: prefix_in(#[0,0], [Fc F1  Fc F2  Fc F3 ])                                                              |
|                     ->  Project                                                                                                                           |
|                           Analyze: timeConsumed=0ms waitTime=0ms inputRows=2 outputRows=2 InputSize=16bytes OutputSize=16bytes MemorySize=16bytes         |
|                           ->  Table Scan on a.__mo_index_secondary_018e1c11-7558-7af2-b7dc-6c107f040c53                                                   |
|                                 Analyze: timeConsumed=0ms waitTime=0ms inputRows=9 outputRows=2 InputSize=288bytes OutputSize=16bytes MemorySize=313bytes |
|                                 Filter Cond: prefix_eq(#[0,0], 'Fb FLane ')                                                                             |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
35 rows in set (0.00 sec)


```

### CODE REVIEW

**Comment by aunjgr** [comment]
> Convert `c IN ("1", "2", "3")` to `prefix_in(__mo_index_idx_col, serial_full("c","1")) OR prefix_in(__mo_index_idx_col, serial_full("c","2")) OR prefix_in(__mo_index_idx_col, serial_full("c","3"))`

That is wrong. The second argument of `prefix_in` should be a vector. An OR-list is very bad in performance.

Why not make it `prefix_in(__mo_index_idx_col, serial_full("c", ("1", "2", "3")))`? Our constant-folding can handle not only literal scalar but also literal vector.

**Comment by arjunsk** [comment]
> > Convert `c IN ("1", "2", "3")` to `prefix_in(__mo_index_idx_col, serial_full("c","1")) OR prefix_in(__mo_index_idx_col, serial_full("c","2")) OR prefix_in(__mo_index_idx_col, serial_full("c","3"))`
> 
> That is wrong. The second argument of `prefix_in` should be a vector. An OR-list is very bad in performance.
> 
> Why not make it `prefix_in(__mo_index_idx_col, serial_full("c", ("1", "2", "3")))`? Our constant-folding can handle not only literal scalar but also literal vector.

1. Got it. Yes, the second argument passed is a vector.

image

2. I am not sure if we do constant folding for this scenario
```sql

mysql> select * from `__mo_index_secondary_018e1831-8618-7f98-930a-0671f3e7077c`;
+-----------------------+--------------------+
| __mo_index_idx_col    | __mo_index_pri_col |
+-----------------------+--------------------+
| Fc F1 @           |                  1 |
| Fa FCongress @    |                  1 |
| Fb FLane @        |                  1 |
| Fc F2 @           |                  2 |
| Fa FJuniper @     |                  2 |
| Fb FWay @         |                  2 |
| Fc F3 @           |                  3 |
| Fb FLane @        |                  3 |
| Fa FNightingale @ |                  3 |
+-----------------------+--------------------+
9 rows in set (0.00 sec)

mysql> select prefix_in(__mo_index_idx_col, serial_full("c", ("1", "2", "3"))) from `__mo_index_secondary_018e1831-8618-7f98-930a-0671f3e7077c`;
Query OK (0.00 sec)


mysql> select serial_full("c", ("1", "2", "3"));
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [1] with length 1: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/sql/plan/function.SerialHelper
        /Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/function/func_builtin.go:1365
github.com/matrixorigin/matrixone/pkg/sql/plan/function.BuiltInSerialFull
        /Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/function/func_builtin.go:971
github.com/matrixorigin/matrixone/pkg/sql/colexe
No connection. Trying to reconnect...
Connection id:    1388
Current database: a

```

**Comment by aunjgr** [comment]
> ```sql
> mysql> select serial_full("c", ("1", "2", "3"));
> ```

You can't write it directly in the query. But you can pass a `LitVec` type expression to serial_full, as what the index code did to convert a `in` to a `prefix_in`.

**Comment by arjunsk** [comment]
> > ```sql
> > mysql> select serial_full("c", ("1", "2", "3"));
> > ```
> 
> You can't write it directly in the query. But you can pass a `LitVec` type expression to serial_full, as what the index code did to convert a `in` to a `prefix_in`.

Got it. I will try that out.

**Comment by arjunsk** [comment]
@aunjgr 

I tried out the following

1. prefix_in( __mo_index_idx_col, serial_full ( serial_full("a","1"), serial_full("a","2")) [NOT WORKING]
image


2. prefix_in(__mo_index_idx_col, ( serial_full("a","1"), serial_full("a","2") ) ) [NOT WORKING]
image

Both of them did not work. Any suggestions?

**Comment by arjunsk** [comment]
Hi @aunjgr 

`prefix_in(__mo_index_idx_col, serial_full("a", ("1","2")) )`  did not work as expected.

image


```error
{"level":"ERROR","time":"2024/03/07 15:56:59.310068 -0800","caller":"frontend/mysql_cmd_executor.go:4490","msg":"error: internal error: panic runtime error: index out of range [1] with length 1: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:114\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function.SerialHelper\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/function/func_builtin.go:1365\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function.BuiltInSerialFull\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/function/func_builtin.go:971\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.NewExpressionExecutor\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/colexec/evalExpression.go:207\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/colexec/evalExpression.go:241\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/utils.go:1132\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/utils.go:1121\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.bindFuncExprAndConstFold\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/base_binder.go:1225\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.makeIndexTblScan\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices_master.go:160\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFiltersUsingMasterIndex\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices_master.go:39\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFilters\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices.go:121\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndices\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices.go:44\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndices\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices.go:54\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).createQuery\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/query_builder.go:1476\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/build.go:42\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/build.go:88\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/optimize.go:56\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:2044\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/computation_wrapper.go:254\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:3706\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:4339\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:4520\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/routine.go:281\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/vendor/github.com/fagongzi/goetty/v2/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197","span":{"trace_id":"006d9136-3e93-0977-e9f6-6a160ad7bfec","span_id":"574bc42ea886da0d"}}
{"level":"ERROR","time":"2024/03/07 15:56:59.310174 -0800","name":"log-service.frontend","caller":"frontend/routine.go:282","msg":"Failed to execute request","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"internal error: panic runtime error: index out of range [1] with length 1: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:114\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function.SerialHelper\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/function/func_builtin.go:1365\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function.BuiltInSerialFull\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/function/func_builtin.go:971\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.NewExpressionExecutor\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/colexec/evalExpression.go:207\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/colexec/evalExpression.go:241\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/utils.go:1132\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/utils.go:1121\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.bindFuncExprAndConstFold\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/base_binder.go:1225\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.makeIndexTblScan\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices_master.go:160\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFiltersUsingMasterIndex\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices_master.go:39\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFilters\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices.go:121\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndices\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices.go:44\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndices\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/apply_indices.go:54\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).createQuery\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/query_builder.go:1476\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/build.go:42\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/build.go:88\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/sql/plan/optimize.go:56\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:2044\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/computation_wrapper.go:254\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:3706\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:4339\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/mysql_cmd_executor.go:4520\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/routine.go:281\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/Users/arjunsunilkumar/GolandProjects/matrixone/vendor/github.com/fagongzi/goetty/v2/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197","session_info":"connectionId 1603|127.0.0.1:55372|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 957|018e1b59-4616-72df-859c-56f0ba090b68","session_id":"018e1b59-4616-72df-859c-56f0ba090b68"}
{"level":"INFO","time":"2024/03/07 15:56:59.976545 -0800","name":"cn-service","caller":"cnservice/server_heartbeat.go:118","msg":"applying schedule command","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","command":"C/CreateTask dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"INFO","time":"2024/03/07 15:56:59.977329 -0800","caller":"frontend/internal_executor.go:173","msg":"internalExecutor new session","span":{},"session uuid":"018e1b59-48c9-7d4c-98fb-75856d36c0f6"}

```

However, I have removed the "Or Chaining logic" and did something similar to what you suggested. Please kindly have a look. Thank you.

**Review by aunjgr — APPROVED** [review]

**Review by heni02 — APPROVED** [review]

**Pull request merged**
