### PR TITLE
Add timestamp data type

### PR DESCRIPTION
**Pull request by broccoliSpicy**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2262 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by fengttt** [comment]
Some overall comment of our type system.
1. Adding one type, need to change 31 files -- this simply feels wrong.   But I am glad at least some are tests :)
2. For those le/ge/eq ... template files, 
     a.  why do we need the template file, if we need to code for a new type. 
     b. are those file all the same?   Other than switched < to >, etc.    Why not a compare function return -1, 0, 1 and we get rid of all these templates?

**Comment by broccoliSpicy** [comment]
> Some overall comment of our type system.
> 
> 1. Adding one type, need to change 31 files -- this simply feels wrong.   But I am glad at least some are tests :)
> 2. For those le/ge/eq ... template files,
>    a.  why do we need the template file, if we need to code for a new type.
>    b. are those file all the same?   Other than switched < to >, etc.    Why not a compare function return -1, 0, 1 and we get rid of all these templates?

1. there are actually more than 30 files that needs modification, I think the number is about 50, left out some storage layer code(zonemap, filter, etc.) to simplify one pr
2. ,
    a. I think we may apply generics as a new approach in lieu of  .template
    b. the difference in code is primarily caused by the difference of vector Type
        get a certain type vector, decode a certain type vector column, call a function of certain type, this kind of thing

**Review by nnsgmsone — COMMENTED** [review]
lgtm

**Review by iamlinjunhong — APPROVED** [review]

**Review by zzl200012 — APPROVED** [review]

**Comment by yingfeng** [comment]
Fix the conflict before it's merged

**Pull request merged**
