### PR TITLE
refactor mergeblocks

### PR DESCRIPTION
**Pull request by jiangxinmeng1**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
refactor mergeblocks

### CODE REVIEW

**Comment by jiangxinmeng1** [comment]
@matrix-meow rerun failed

**Review by fengttt — APPROVED** [review]
Much better, even though I still do not understand the follown g line
```
				toPos, toRow := entry.resolveAddr(fromPos-skippedCnt, row)
```

I will leave it to @XuPeng-SH .    Thank you very much.

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Comment by jiangxinmeng1** [comment]
When merge, rowID changes. `resolveAddr` find new rowID for the deletes.

`fromAddr` is start offset for each block. For example, if there're three blocks to merge, the length of each is 3,5,4, then, `fromAddr` is 0, 3, 8. 
`totalFromOffset` is the total offset. The total offset of 2nd row in blk[1] is 3(fromAddr[1])+2=5. 
`mapping` is the map of old offset and new offset genetated when merge. We can get the new total offset according to the map and the old offset. 
`toPos` is the offset of the block. `toOffset` is the offset in the new block. We bisearch and compare `totalToOffset` and `toAddr` to locate the block to find `toPos` and `toOffset`.  For example, when `toAddr` is 5,5,2,  the 8th row is in blk[1] and offset is 3.

**Pull request merged**
