### PR TITLE
Feature builtin-in function log

### PR DESCRIPTION
**Pull request by WenhaoKong2001**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1823

**What this PR does / why we need it:**
This PR implements built-in function log.
Suppose table tb looks like this
```SQL
mysql> select * from tb;
+------+------+
| a    | b    |
+------+------+
|    2 |   -2 |
|    4 |    7 |
|   -6 |   29 |
|   16 | NULL |
|   -2 |   -6 |
+------+------+
5 rows in set (0.06 sec)
```
Then **select log(a),log(b) from tb** will print like this:
```SQL
mysql> select log(a),log(b) from tb;
+--------+--------+
| Log(a) | Log(b) |
+--------+--------+
| 0.6931 |   NULL |
| 1.3863 | 1.9459 |
|   NULL | 3.3673 |
| 2.7726 |   NULL |
|   NULL |   NULL |
+--------+--------+
5 rows in set (0.04 sec)
```

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by broccoliSpicy — COMMENTED** [review]
impeccable

**Comment by yingfeng** [comment]
Pls add license information to each newly added header file before it is merged

**Comment by yingfeng** [comment]
Pls add license information to each newly added header file before it is merged

**Comment by WenhaoKong2001** [comment]
@yingfeng license information added.

**Pull request merged**
