### PR TITLE
remove log pkg usage on v0.8.0

### PR DESCRIPTION
**Pull request by xzxiong**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
fix sca check, remove log pkg usage by using logutil. image

> pick from #10668

### CODE REVIEW

**Review by zhangxu19830126 — DISMISSED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Comment by xzxiong** [comment]
@Mergifyio refresh

**Comment by xzxiong** [comment]
@mergify requeue

**Comment by xzxiong** [comment]
@mergify requeue

**Comment by xzxiong** [comment]
@mergify refresh

**Comment by xzxiong** [comment]
fix by https://github.com/matrixorigin/matrixone/pull/10802

**Pull request closed without merging**
