### PR TITLE
Support json type storage

### PR DESCRIPTION
**Pull request by mooleetzi**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [X] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #4121

**What this PR does / why we need it:**

Support json type storage

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by jianwan0214 — APPROVED** [review]

**Comment by jianwan0214** [comment]
this pr support the select and insert with json type

**Review by jianwan0214 — APPROVED** [review]

**Comment by yingfeng** [comment]
It's better to add[ bvt cases ](https://github.com/matrixorigin/matrixone/tree/main/test)to verify end-to-end testing

**Comment by mooleetzi** [comment]
> It's better to add[ bvt cases ](https://github.com/matrixorigin/matrixone/tree/main/test)to verify end-to-end testing

Okay, I've added that. Thx

**Review by jianwan0214 — APPROVED** [review]

**Review by daviszhen — CHANGES_REQUESTED** [review]
Have many conflicts with the main branch.

**Comment by mooleetzi** [comment]
> Have many conflicts with the main branch.
Ok, I've handled them already

**Review by daviszhen — APPROVED** [review]

**Pull request merged**
