### PR TITLE
move RecordRunningCompile and removeRunningCompile to compile.Run()

### PR DESCRIPTION
**Pull request by m-schen**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

https://github.com/matrixorigin/MO-Cloud/issues/4210

## What this PR does / why we need it:
1. move Record and Remove running query from runOnce to compile.Run.
2. once cn tn reconnection happens, pause compileService until all txn were flag to aborted.
3. remove some redundant codes.

### CODE REVIEW

**Comment by m-schen** [comment]
我先加个标签，等到自测通过再移除。

**Review by zhangxu19830126 — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by badboynt1 — APPROVED** [review]

**Review by qingxinhome — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Comment by m-schen** [comment]
有件很诡异的事情，我在ci-tester里起测试一直跑不起来。

**Comment by m-schen** [comment]
merge了最新的main后没有问题了。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/11322351222

**Pull request merged**
