### PR TITLE
Tae supports appendable block flush

### PR DESCRIPTION
**Pull request by LeftHandCold**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
Tae supports appendable block flush, keeps historical version records, and can access historical data according to ts

### CODE REVIEW

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Review by jiangxinmeng1 — APPROVED** [review]

**Comment by LeftHandCold** [comment]
@matrix-meow rerun failed

**Review by XuPeng-SH — APPROVED** [review]
lgtm

**Pull request merged**
