### PR TITLE
add  lastlog into txn

### PR DESCRIPTION
**Pull request by daviszhen**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11966 

## What this PR does / why we need it:

打开入口日志，记录sql。

### CODE REVIEW

**Review by fengttt — CHANGES_REQUESTED** [review]
This won't work.     Point select immediate drop 20%.

**Comment by daviszhen** [comment]
> This won't work. Point select immediate drop 20%.

......

**Review by reusee — APPROVED** [review]

**Review by zhangxu19830126 — APPROVED** [review]

**Comment by fengttt** [comment]
> > This won't work. Point select immediate drop 20%.
> 
> ......

Do you log EVERY query?

**Review by fengttt — APPROVED** [review]
I think now you know very well that we cannot log TOO much.   I will approve based on that the per query log has been removed.

**Review by nnsgmsone — APPROVED** [review]

**Pull request merged**
