### PR TITLE
finish migration of cos,atan,cot

### PR DESCRIPTION
**Pull request by JackTan25**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by fengttt — COMMENTED** [review]
Why do we need all these AtanInt64/Uint64 etc?    Why does planner not cast int to float64 for you?

**Comment by JackTan25** [comment]
> Why do we need all these AtanInt64/Uint64 etc? Why does planner not cast int to float64 for you?

Yeah, I make this according to func acos, and now we just think about int64, uint64, float64, maybe I need to check more details.

**Review by broccoliSpicy — APPROVED** [review]

**Comment by broccoliSpicy** [comment]
use "make fmt" in the matrixone directory may solve your formatting

**Comment by JackTan25** [comment]
> > Why do we need all these AtanInt64/Uint64 etc? Why does planner not cast int to float64 for you?
> 
> Yeah, I make this according to func acos, and now we just think about int64, uint64, float64, maybe I need to check more details.

Oh, because we don't use generics type in the bottom, the planner can't achieve the way， it need to be modified in the bottom.

**Comment by broccoliSpicy** [comment]
> > > Why do we need all these AtanInt64/Uint64 etc? Why does planner not cast int to float64 for you?
> > 
> > 
> > Yeah, I make this according to func acos, and now we just think about int64, uint64, float64, maybe I need to check more details.
> 
> I think what fengttt means is that we can drop the function implementation for int64/Uint64. they are essentially the same, planner matches it directly or planner do a cast for you

currently our casting logic has some bugs, you may see segmentation fault if you try testing it, that's okay, no modification needed here, your implementation is fine

**Review by yingfeng — CHANGES_REQUESTED** [review]
make format check pass

**Comment by yingfeng** [comment]
Fix the conflicts

**Comment by JackTan25** [comment]
> Fix the conflicts

ok

**Review by yingfeng — CHANGES_REQUESTED** [review]
Rewrite using generics, take a reference on sin implemented by @broccoliSpicy

**Comment by JackTan25** [comment]
> Rewrite using generics, take a reference on sin implemented by @broccoliSpicy

Ok

**Pull request merged**
