### PR TITLE
BuildPartitionExpression

### PR DESCRIPTION
**Pull request by qingxinhome**
## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5751

## What this PR does / why we need it:
Convert different types of partition structures into plan expressions, which are used to split partition table data.
Add: The index table needs to be hidden

### CODE REVIEW

**Review by zhangxu19830126 — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by fengttt — COMMENTED** [review]
Let me confirm, you build the partition expression as a list of expression or one expression?
How can optimizer and executor get this expression?

Again, we checked that all columns mentioned in the partition expr is a subset of primary key.
If the table has no primary key then can be any columns.

Finally if function expr appear in partition key, we should check if that it is not volatile.

**Comment by qingxinhome** [comment]
> 

First of all, your first question:
I build the expression for all partitions as an expression, not a list of expressions.
The optimizer and executor will get the partition expression in the table definition.

Your second question:
According to your requirements, if the primary key is defined in the table, the partitioning key/or the columns used in the partitioning function must come from the primary key (or part of the primary key)
In addition, according to the syntax requirements of MySQL, every unique key on the table must use every column in the table's partitioning expression. This also includes the table's primary key, since it is by definition a unique key

Your third question: 
Sorry,Dr Tian,I don't understand what type of function 'not volatile' refers to.

**Comment by qingxinhome** [comment]
> Let me confirm, you build the partition expression as a list of expression or one expression? How can optimizer and executor get this expression?
> 
> Again, we checked that all columns mentioned in the partition expr is a subset of primary key. If the table has no primary key then can be any columns.
> 
> Finally if function expr appear in partition key, we should check if that it is not volatile.
First of all, your first question:
I build the expression for all partitions as an expression, not a list of expressions.
The optimizer and executor will get the partition expression in the table definition.

Your second question:
According to your requirements, if the primary key is defined in the table, the partitioning key/or the columns used in the partitioning function must come from the primary key (or part of the primary key)
In addition, according to the syntax requirements of MySQL, every unique key on the table must use every column in the table's partitioning expression. This also includes the table's primary key, since it is by definition a unique key

Your third question: 
Sorry,Dr Tian,I don't understand what type of function 'not volatile' refers to.

**Comment by qingxinhome** [comment]
> Let me confirm, you build the partition expression as a list of expression or one expression? How can optimizer and executor get this expression?
> 
> Again, we checked that all columns mentioned in the partition expr is a subset of primary key. If the table has no primary key then can be any columns.
> 
> Finally if function expr appear in partition key, we should check if that it is not volatile.

First of all, 
your first question:
I build the expression for all partitions as an expression, not a list of expressions.
The optimizer and executor will get the partition expression in the table definition.

Your second question:
According to your requirements, if the primary key is defined in the table, the partitioning key/or the columns used in the partitioning function must come from the primary key (or part of the primary key)
In addition, according to the syntax requirements of MySQL, every unique key on the table must use every column in the table's partitioning expression. This also includes the table's primary key, since it is by definition a unique key

Your third question: 
Sorry,Dr Tian,I don't understand what type of function 'not volatile' refers to.

**Review by daviszhen — APPROVED** [review]

**Review by aunjgr — APPROVED** [review]

**Review by ouyuanning — APPROVED** [review]

**Review by iamlinjunhong — APPROVED** [review]

**Review by nnsgmsone — APPROVED** [review]

**Review by aressu1985 — APPROVED** [review]

**Review by fengttt — APPROVED** [review]

**Pull request merged**
